Repository open-telemetry/opentelemetry-go, pull requests merged in 2020-06, with the labels that each got.

#778 Add oterror package and implementation in api/global
  api/global/handler.go
  api/global/handler_test.go
  api/global/metric.go
  api/global/metric_test.go
  api/global/propagation.go
  api/global/trace.go
  api/global/trace_test.go
  api/metric/api_test.go
  api/metric/sync.go
  api/oterror/doc.go
  api/oterror/errors.go
  api/oterror/handler.go
Labels: API

#803 Remove Context arguments from Aggregator.Checkpoint and Integrator.Process
  api/global/internal/benchmark_test.go
  exporters/metric/stdout/stdout_test.go
  exporters/metric/test/test.go
  exporters/otlp/internal/transform/metric_test.go
  exporters/otlp/otlp_metric_test.go
  sdk/export/metric/metric.go
  sdk/metric/aggregator/array/array.go
  sdk/metric/aggregator/array/array_test.go
  sdk/metric/aggregator/ddsketch/ddsketch.go
  sdk/metric/aggregator/ddsketch/ddsketch_test.go
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
  sdk/metric/aggregator/lastvalue/lastvalue.go
  sdk/metric/aggregator/lastvalue/lastvalue_test.go
  sdk/metric/aggregator/minmaxsumcount/mmsc.go
  sdk/metric/aggregator/minmaxsumcount/mmsc_test.go
  sdk/metric/aggregator/sum/sum.go
  sdk/metric/aggregator/sum/sum_test.go
  sdk/metric/benchmark_test.go
  sdk/metric/correct_test.go
  sdk/metric/histogram_stress_test.go
  sdk/metric/integrator/simple/simple.go
  sdk/metric/integrator/simple/simple_test.go
  sdk/metric/integrator/test/test.go
  sdk/metric/minmaxsumcount_stress_test.go
  sdk/metric/sdk.go
  sdk/metric/stress_test.go
Labels: metrics

#805 Support Instrumentation Library Info in Trace Export Pipeline
  exporters/otlp/internal/transform/instrumentation.go
  exporters/otlp/internal/transform/span.go
  exporters/otlp/internal/transform/span_test.go
  exporters/otlp/otlp_span_test.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/stdout/stdout_test.go
  sdk/export/trace/trace.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
Labels: exporters, sdk, trace

#810 Changes AlwaysParentSample to ParentSample(fallback)
  sdk/trace/sampling.go
  sdk/trace/sampling_test.go
Labels: sdk, trace

#811 Metrics instrumentation version
  api/global/internal/benchmark_test.go
  api/global/internal/meter.go
  api/global/internal/meter_test.go
  api/global/metric.go
  api/global/metric_test.go
  api/metric/api_test.go
  api/metric/config.go
  api/metric/descriptor.go
  api/metric/meter.go
  api/metric/must.go
  api/metric/noop.go
  api/metric/registry/registry.go
  api/metric/sdkapi.go
  exporters/metric/stdout/example_test.go
  exporters/metric/stdout/stdout.go
  exporters/otlp/internal/transform/metric.go
  exporters/otlp/otlp_metric_test.go
  sdk/metric/example_test.go
Labels: API, exporters, metrics, sdk

#812 Single-state Aggregator and test refactor
  api/global/internal/benchmark_test.go
  exporters/metric/stdout/stdout_test.go
  exporters/metric/test/test.go
  exporters/metric/test/test_test.go
  exporters/otlp/internal/transform/metric_test.go
  exporters/otlp/otlp_metric_test.go
  sdk/export/metric/metric.go
  sdk/metric/aggregator/aggregator.go
  sdk/metric/aggregator/aggregator_test.go
  sdk/metric/aggregator/array/array.go
  sdk/metric/aggregator/array/array_test.go
  sdk/metric/aggregator/ddsketch/ddsketch.go
  sdk/metric/aggregator/ddsketch/ddsketch_test.go
  sdk/metric/aggregator/histogram/benchmark_test.go
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
  sdk/metric/aggregator/lastvalue/lastvalue.go
  sdk/metric/aggregator/lastvalue/lastvalue_test.go
  sdk/metric/aggregator/minmaxsumcount/mmsc.go
  sdk/metric/aggregator/minmaxsumcount/mmsc_test.go
  sdk/metric/aggregator/sum/sum.go
  sdk/metric/aggregator/sum/sum_test.go
  sdk/metric/benchmark_test.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/correct_test.go
  sdk/metric/histogram_stress_test.go
  sdk/metric/integrator/simple/simple.go
  sdk/metric/integrator/simple/simple_test.go
  sdk/metric/integrator/test/test.go
  sdk/metric/minmaxsumcount_stress_test.go
  sdk/metric/sdk.go
  sdk/metric/selector/simple/simple.go
  sdk/metric/selector/simple/simple_test.go
  sdk/metric/stress_test.go
Labels: metrics

#848 Bumps github.com/golang/protobuf from 1.3.2 to 1.4.2
  example/basic/go.sum
  example/grpc/go.mod
  example/grpc/go.sum
  example/http/go.sum
  example/jaeger/go.sum
  example/namedtracer/go.sum
  example/otel-collector/go.sum
  example/otlp/go.sum
  example/zipkin/go.sum
  exporters/otlp/go.mod
  exporters/otlp/go.sum
  exporters/trace/jaeger/go.sum
  exporters/trace/zipkin/go.sum
  go.mod
  go.sum
  instrumentation/grpctrace/interceptor.go
  instrumentation/grpctrace/interceptor_test.go
Labels: dependencies

#840 Support cumulative, delta, and pass-through exporters
  api/metric/kind.go
  api/metric/kind_test.go
  api/metric/number.go
  api/metric/number_test.go
  example/otlp/main.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/stdout/stdout.go
  exporters/metric/test/test.go
  exporters/otlp/internal/transform/metric.go
  exporters/otlp/otlp.go
  exporters/otlp/otlp_integration_test.go
  exporters/otlp/otlp_metric_test.go
  sdk/export/metric/aggregation/aggregation.go
  sdk/export/metric/exportkind_string.go
  sdk/export/metric/exportkind_test.go
  sdk/export/metric/metric.go
  sdk/metric/aggregator/ddsketch/ddsketch.go
  sdk/metric/aggregator/sum/sum.go
  sdk/metric/controller/pull/config.go
  sdk/metric/controller/pull/pull.go
  sdk/metric/controller/pull/pull_test.go
  sdk/metric/controller/push/config.go
  sdk/metric/controller/push/push.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/integrator/simple/simple.go
  sdk/metric/integrator/simple/simple_test.go
Labels: metrics

#857 Rename simple integrator to basic integrator
  exporters/otlp/otlp_integration_test.go
  sdk/metric/controller/pull/pull.go
  sdk/metric/controller/push/push.go
  sdk/metric/integrator/basic/basic.go
  sdk/metric/integrator/basic/basic_test.go
Labels: metrics

#858 Rename SynchronizedCopy to SynchronizedMove and update comment
  exporters/metric/stdout/stdout_test.go
  exporters/metric/test/test.go
  exporters/otlp/internal/transform/metric_test.go
  exporters/otlp/otlp_metric_test.go
  sdk/export/metric/metric.go
  sdk/metric/aggregator/array/array.go
  sdk/metric/aggregator/array/array_test.go
  sdk/metric/aggregator/ddsketch/ddsketch.go
  sdk/metric/aggregator/ddsketch/ddsketch_test.go
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
  sdk/metric/aggregator/lastvalue/lastvalue.go
  sdk/metric/aggregator/lastvalue/lastvalue_test.go
  sdk/metric/aggregator/minmaxsumcount/mmsc.go
  sdk/metric/aggregator/minmaxsumcount/mmsc_test.go
  sdk/metric/aggregator/sum/sum.go
  sdk/metric/aggregator/sum/sum_test.go
  sdk/metric/histogram_stress_test.go
  sdk/metric/integrator/basic/basic.go
  sdk/metric/minmaxsumcount_stress_test.go
  sdk/metric/sdk.go
Labels: metrics

#859 Rename AggregationSelector to AggregatorSelector
  api/global/internal/benchmark_test.go
  sdk/export/metric/metric.go
  sdk/metric/benchmark_test.go
  sdk/metric/controller/pull/pull.go
  sdk/metric/controller/push/push.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/correct_test.go
  sdk/metric/doc.go
  sdk/metric/integrator/basic/basic.go
  sdk/metric/integrator/basic/basic_test.go
  sdk/metric/integrator/test/test.go
  sdk/metric/sdk.go
  sdk/metric/selector/simple/simple.go
  sdk/metric/selector/simple/simple_test.go
  sdk/metric/stress_test.go
Labels: metrics

#856 Improve comments in simple aggregator
  sdk/metric/integrator/basic/basic.go
Labels: metrics

#863 Rename Metrics Integrator to Processor
  api/global/internal/benchmark_test.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/stdout/stdout.go
  exporters/metric/test/test.go
  exporters/otlp/otlp_integration_test.go
  sdk/export/metric/metric.go
  sdk/metric/benchmark_test.go
  sdk/metric/controller/pull/pull.go
  sdk/metric/controller/pull/pull_test.go
  sdk/metric/controller/push/push.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/correct_test.go
  sdk/metric/doc.go
  sdk/metric/processor/basic/basic.go
  sdk/metric/processor/basic/basic_test.go
  sdk/metric/processor/test/test.go
  sdk/metric/sdk.go
  sdk/metric/stress_test.go
Labels: metrics

#866 Upgrade OTLP exporter to opentelemetry-proto matching the opentelemetry-collector v0.4.0 release
  example/otel-collector/go.sum
  exporters/otlp/go.mod
  exporters/otlp/go.sum
  exporters/otlp/internal/transform/attribute.go
  exporters/otlp/internal/transform/attribute_test.go
  exporters/otlp/internal/transform/metric.go
  exporters/otlp/internal/transform/metric_test.go
  exporters/otlp/mock_collector_test.go
  exporters/otlp/otlp_integration_test.go
  exporters/otlp/otlp_metric_test.go
  exporters/otlp/otlp_span_test.go
Labels: bug, exporters, metrics

#873 Add Changelog
  CHANGELOG.md
Labels: doc

#861 Add default metrics to othttp instrumentation Fixes #542
  api/standard/http.go
  instrumentation/othttp/common.go
  instrumentation/othttp/config.go
  instrumentation/othttp/handler.go
  instrumentation/othttp/handler_example_test.go
  instrumentation/othttp/handler_test.go
Labels: metrics
