Repository open-telemetry/opentelemetry-go, pull requests merged in 2020-08, with the labels that each got.

#1016 Rename api/standard package to semconv
  CHANGELOG.md
  example/http/client/client.go
  example/http/server/server.go
  example/otel-collector/main.go
  instrumentation/grpctrace/interceptor.go
  instrumentation/grpctrace/interceptor_test.go
  instrumentation/httptrace/clienttrace.go
  instrumentation/httptrace/httptrace.go
  instrumentation/httptrace/httptrace_test.go
  instrumentation/othttp/handler.go
  instrumentation/othttp/handler_test.go
  instrumentation/othttp/transport.go
  semconv/doc.go
  semconv/http.go
  semconv/http_test.go
  semconv/resource.go
  semconv/trace.go
Labels: pkg:API, release:required-for-ga

#1032 Remove othttp and httptrace instrumentations that have moved to contrib
  example/basic/go.sum
  example/grpc/go.sum
  example/http/Dockerfile
  example/http/README.md
  example/http/client/client.go
  example/http/docker-compose.yml
  example/http/go.mod
  example/http/go.sum
  example/http/server/modd.conf
  example/http/server/server.go
  example/jaeger/go.sum
  example/namedtracer/go.sum
  example/otel-collector/go.sum
  example/prometheus/go.sum
  example/zipkin/go.sum
  exporters/metric/prometheus/go.sum
  exporters/otlp/go.sum
  exporters/stdout/go.sum
  exporters/trace/jaeger/go.sum
  exporters/trace/zipkin/go.sum
  go.mod
  go.sum
  instrumentation/httptrace/api.go
  instrumentation/httptrace/clienttrace.go
  instrumentation/httptrace/clienttrace_test.go
  instrumentation/httptrace/httptrace.go
  instrumentation/httptrace/httptrace_test.go
  instrumentation/othttp/common.go
  instrumentation/othttp/config.go
  instrumentation/othttp/config_test.go
  instrumentation/othttp/doc.go
  instrumentation/othttp/filters/filters.go
  instrumentation/othttp/filters/filters_test.go
  instrumentation/othttp/filters/header_go14.go
  instrumentation/othttp/filters/header_nongo14.go
  instrumentation/othttp/handler.go
  instrumentation/othttp/handler_example_test.go
  instrumentation/othttp/handler_test.go
  instrumentation/othttp/transport.go
  instrumentation/othttp/transport_example_test.go
  instrumentation/othttp/transport_test.go
  instrumentation/othttp/wrap.go
  sdk/go.sum
Labels: pkg:instrumentation

#1030 Add reminder to release contrib after this repo
  RELEASING.md
Labels: documentation

#1026 Remove the oterror package
  api/global/handler.go
  api/global/handler_test.go
  api/metric/api_test.go
  api/metric/sync.go
  api/oterror/doc.go
  api/oterror/handler.go
  error_handler.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/correct_test.go
  sdk/trace/trace_test.go
Labels: pkg:API, release:required-for-ga

#1027 Move grpctrace to contrib repo
  CHANGELOG.md
  example/grpc/README.md
  example/grpc/api/hello-service.pb.go
  example/grpc/api/hello-service.proto
  example/grpc/client/main.go
  example/grpc/config/config.go
  example/grpc/go.mod
  example/grpc/go.sum
  example/grpc/server/main.go
  instrumentation/grpctrace/example_interceptor_test.go
  instrumentation/grpctrace/grpctrace.go
  instrumentation/grpctrace/interceptor.go
  instrumentation/grpctrace/interceptor_test.go
Labels: pkg:instrumentation

#1043 Remove WithSpan method from Tracer interface
  CHANGELOG.md
  README.md
  api/global/internal/trace.go
  api/global/internal/trace_test.go
  api/testharness/harness.go
  api/trace/api.go
  api/trace/noop_trace.go
  api/trace/testtrace/tracer.go
  api/trace/testtrace/tracer_test.go
  bridge/opentracing/internal/mock.go
  bridge/opentracing/wrapper.go
  example/basic/main.go
  example/namedtracer/foo/foo.go
  example/namedtracer/main.go
  exporters/stdout/example_test.go
  internal/trace/mock_tracer.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  sdk/trace/tracer.go
Labels: area:trace, pkg:API

#1046 Remove google.golang.org/grpc/codes dependency from API by adding an equivalent codes package
  CHANGELOG.md
  api/testharness/harness.go
  api/trace/api.go
  api/trace/context_test.go
  api/trace/noop_span.go
  api/trace/testtrace/span.go
  api/trace/testtrace/span_test.go
  bridge/opentracing/bridge.go
  bridge/opentracing/go.mod
  bridge/opentracing/internal/mock.go
  codes/codes.go
  internal/trace/mock_span.go
  sdk/internal/codes.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  semconv/http.go
  semconv/http_test.go
Labels: area:trace, pkg:API

#1024 Change Metric Processor to merge multiple observations
  sdk/metric/controller/pull/pull_test.go
  sdk/metric/correct_test.go
  sdk/metric/processor/basic/basic.go
  sdk/metric/processor/basic/basic_test.go
  sdk/metric/processor/processortest/test.go
Labels: area:metrics

#1047 Add support for filtering metric label sets
  api/label/set.go
  api/label/set_test.go
Labels: area:metrics

#1055 Create a export.Checkpointer API; refactor metric export pipeline test helpers
  example/otel-collector/main.go
  exporters/metric/prometheus/prometheus.go
  exporters/stdout/exporter.go
  sdk/export/metric/metric.go
  sdk/export/metric/metrictest/test.go
  sdk/metric/controller/pull/pull.go
  sdk/metric/controller/pull/pull_test.go
  sdk/metric/controller/push/push.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/correct_test.go
  sdk/metric/processor/basic/basic.go
  sdk/metric/processor/processortest/test.go
  sdk/metric/processor/processortest/test_test.go
Labels: area:metrics

#1057 Add a dimensionality-reducing metric Processor
  sdk/metric/processor/reducer/doc.go
  sdk/metric/processor/reducer/reducer.go
  sdk/metric/processor/reducer/reducer_test.go
Labels: area:metrics

#1106 Update README.md
  README.md
Labels: documentation, priority:p3, release:required-for-ga

#1040 #872 Make metric test helpers public
  api/global/internal/meter_test.go
  api/metric/api_test.go
  api/metric/metrictest/async.go
  api/metric/metrictest/meter.go
  api/metric/metrictest/mock_test.go
  api/metric/metrictest/test_helpers.go
  api/metric/registry/registry_test.go
  sdk/metric/sdk.go
Labels: area:metrics, priority:p3, release:required-for-ga

#1102 Rename global SetTraceProvider and TraceProvider
  api/global/internal/state.go
  api/global/internal/trace.go
  api/global/internal/trace_test.go
  api/global/trace.go
  api/global/trace_test.go
  bridge/opentracing/mix_test.go
  example/namedtracer/main.go
  example/otel-collector/main.go
  example/zipkin/main.go
  exporters/otlp/README.md
  exporters/otlp/example_test.go
  exporters/stdout/example_test.go
  exporters/stdout/exporter.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/zipkin/zipkin.go
  exporters/trace/zipkin/zipkin_test.go
Labels: area:trace, pkg:API, priority:p1, release:required-for-ga
