Repository open-telemetry/opentelemetry-go, pull requests merged in 2020-12, with the labels that each got.

#1370 Build examples last
  Makefile
Labels: Skip Changelog

#1371 Rework proto generation
  .github/workflows/protogen.yml
  Makefile.proto
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: Skip Changelog

#1381 Metric Accumulator fix for SumObservers
  CHANGELOG.md
  sdk/export/metric/metric.go
  sdk/metric/aggregator/aggregatortest/test.go
  sdk/metric/aggregator/array/array.go
  sdk/metric/aggregator/array/array_test.go
  sdk/metric/aggregator/ddsketch/ddsketch.go
  sdk/metric/aggregator/ddsketch/ddsketch_test.go
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
  sdk/metric/aggregator/lastvalue/lastvalue.go
  sdk/metric/aggregator/lastvalue/lastvalue_test.go
  sdk/metric/aggregator/minmaxsumcount/mmsc.go
  sdk/metric/aggregator/minmaxsumcount/mmsc_test.go
  sdk/metric/aggregator/sum/sum.go
  sdk/metric/aggregator/sum/sum_test.go
  sdk/metric/correct_test.go
  sdk/metric/processor/basic/basic_test.go
  sdk/metric/sdk.go
Labels: area:metrics, bug

#1390 Fix typo in readme
  example/otel-collector/README.md
Labels: Skip Changelog

#1384 Call otel.Handle with non-nil errors
  sdk/trace/provider.go
  sdk/trace/provider_test.go
  sdk/trace/trace_test.go
Labels: Skip Changelog

#1402 Fix typo in comment
  internal/testing/alignment.go
  sdk/metric/sdk.go
Labels: Skip Changelog

#1403 Correct CI workflow syntax
  .github/workflows/ci.yml
Labels: Skip Changelog, bug

#1406 Mention the getting started guide
  README.md
  doc.go
Labels: Skip Changelog

#1409 Fix small typo
  propagation.go
Labels: Skip Changelog, documentation

#1410 Add @dashpole as a project Approver
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#1388 Add Versioning Documentation
  CHANGELOG.md
  README.md
  VERSIONING.md
Labels: documentation

#1425 Build script: Replace mapfile with read loop for old bash versions
  get_main_pkgs.sh
Labels: Skip Changelog

#1427 gitignore: remove unused example path
  .gitignore
Labels: Skip Changelog
