Repository open-telemetry/opentelemetry-go, pull requests merged in 2020-03, with the labels that each got.

#508 Make the default label encoding unique
  sdk/metric/correct_test.go
  sdk/metric/labelencoder.go
Labels: metrics

#474 Add observer metric
  api/global/internal/internal_test.go
  api/global/internal/meter.go
  api/global/internal/meter_test.go
  api/metric/api.go
  api/metric/api_test.go
  api/metric/doc.go
  api/metric/noop.go
  api/metric/sdkhelpers.go
  internal/metric/mock.go
  sdk/export/metric/kind_string.go
  sdk/export/metric/metric.go
  sdk/metric/benchmark_test.go
  sdk/metric/doc.go
  sdk/metric/sdk.go
  sdk/metric/selector/simple/simple.go
  sdk/metric/selector/simple/simple_test.go
Labels: metrics

#452 Remove the StackDriver trace exporter
  .gitignore
  example/http-stackdriver/client/client.go
  example/http-stackdriver/go.mod
  example/http-stackdriver/go.sum
  example/http-stackdriver/server/modd.conf
  example/http-stackdriver/server/server.go
  exporters/trace/stackdriver/go.mod
  exporters/trace/stackdriver/go.sum
  exporters/trace/stackdriver/stackdriver.go
  exporters/trace/stackdriver/stackdriver_test.go
  exporters/trace/stackdriver/trace.go
  exporters/trace/stackdriver/trace_proto.go
Labels: exporters, trace

#459 [tracing] add simplified export pipeline setup for Jaeger
  example/jaeger/main.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
Labels: exporters, trace

#537 Drop the gauge instrument
  api/global/internal/benchmark_test.go
  api/global/internal/meter.go
  api/global/internal/meter_test.go
  api/metric/api.go
  api/metric/api_test.go
  api/metric/doc.go
  api/metric/gauge.go
  api/metric/noop.go
  api/metric/sdkhelpers.go
  example/basic/main.go
  example/prometheus/main.go
  exporters/metric/internal/statsd/conn_test.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/prometheus/prometheus_test.go
  exporters/metric/stdout/stdout_test.go
  exporters/metric/test/test.go
  internal/metric/mock.go
  sdk/export/metric/aggregator/aggregator_test.go
  sdk/export/metric/kind_string.go
  sdk/export/metric/metric.go
  sdk/metric/aggregator/lastvalue/lastvalue.go
  sdk/metric/aggregator/lastvalue/lastvalue_test.go
  sdk/metric/batcher/defaultkeys/defaultkeys_test.go
  sdk/metric/batcher/test/test.go
  sdk/metric/batcher/ungrouped/ungrouped_test.go
  sdk/metric/benchmark_test.go
  sdk/metric/correct_test.go
  sdk/metric/doc.go
  sdk/metric/monotone_test.go
  sdk/metric/sdk.go
  sdk/metric/selector/simple/simple.go
  sdk/metric/selector/simple/simple_test.go
  sdk/metric/stress_test.go
Labels: API, metrics

#523 Use a variable-size array to represent ordered labels in maps
  sdk/metric/correct_test.go
  sdk/metric/list.go
  sdk/metric/sdk.go
Labels: metrics

#438 Make histogram aggregator checkpoint consistent
  sdk/internal/state_locker.go
  sdk/internal/state_locker_test.go
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
  sdk/metric/histogram_stress_test.go
Labels: exporters, metrics

#529 Introduce metric constructor errors, `MeterMust` wrapper
  api/global/internal/benchmark_test.go
  api/global/internal/meter.go
  api/global/internal/meter_test.go
  api/metric/api.go
  api/metric/api_test.go
  api/metric/common.go
  api/metric/must.go
  api/metric/noop.go
  api/metric/sdkhelpers.go
  example/basic/main.go
  example/prometheus/main.go
  exporters/metric/dogstatsd/example_test.go
  exporters/metric/stdout/example_test.go
  internal/metric/mock.go
  sdk/metric/benchmark_test.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/correct_test.go
  sdk/metric/example_test.go
  sdk/metric/sdk.go
  sdk/metric/stress_test.go
Labels: metrics

#541 Remove metric options; rename "counter" aggregator to "sum"
  api/global/internal/benchmark_test.go
  api/global/internal/meter.go
  api/global/internal/meter_test.go
  api/metric/api.go
  api/metric/api_test.go
  api/metric/must.go
  api/metric/noop.go
  api/metric/sdkhelpers.go
  exporters/metric/dogstatsd/dogstatsd_test.go
  exporters/metric/internal/statsd/conn_test.go
  exporters/metric/prometheus/prometheus_test.go
  exporters/metric/stdout/stdout_test.go
  exporters/metric/test/test.go
  internal/metric/mock.go
  sdk/export/metric/aggregator/aggregator.go
  sdk/export/metric/aggregator/aggregator_test.go
  sdk/export/metric/metric.go
  sdk/metric/aggregator/array/array_test.go
  sdk/metric/aggregator/ddsketch/ddsketch_test.go
  sdk/metric/aggregator/histogram/histogram_test.go
  sdk/metric/aggregator/lastvalue/lastvalue_test.go
  sdk/metric/aggregator/minmaxsumcount/mmsc_test.go
  sdk/metric/aggregator/sum/sum.go
  sdk/metric/aggregator/sum/sum_test.go
  sdk/metric/aggregator/test/test.go
  sdk/metric/batcher/defaultkeys/defaultkeys_test.go
  sdk/metric/batcher/test/test.go
  sdk/metric/batcher/ungrouped/ungrouped_test.go
  sdk/metric/benchmark_test.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/correct_test.go
  sdk/metric/histogram_stress_test.go
  sdk/metric/sdk.go
  sdk/metric/selector/simple/simple.go
  sdk/metric/selector/simple/simple_test.go
  sdk/metric/stress_test.go
Labels: metrics

#544 Add metrics support to the OTLP exporter
  exporters/otlp/internal/transform/metric.go
  exporters/otlp/internal/transform/metric_test.go
  exporters/otlp/mock_collector_test.go
  exporters/otlp/options.go
  exporters/otlp/otlp.go
  exporters/otlp/otlp_test.go
Labels: exporters, metrics

#560 Refactor the SDK helpers, create MeterImpl
  api/global/internal/benchmark_test.go
  api/global/internal/meter.go
  api/global/internal/meter_test.go
  api/metric/api.go
  api/metric/api_test.go
  api/metric/common.go
  api/metric/counter.go
  api/metric/doc.go
  api/metric/kind_string.go
  api/metric/measure.go
  api/metric/noop.go
  api/metric/observer.go
  api/metric/sdkhelpers.go
  example/basic/main.go
  example/prometheus/main.go
  exporters/metric/dogstatsd/dogstatsd_test.go
  exporters/metric/internal/statsd/conn_test.go
  exporters/metric/prometheus/prometheus_test.go
  exporters/metric/stdout/stdout_test.go
  exporters/metric/test/test.go
  exporters/otlp/internal/transform/metric.go
  exporters/otlp/internal/transform/metric_test.go
  exporters/otlp/otlp_test.go
  internal/metric/mock.go
  sdk/export/metric/aggregator/aggregator.go
  sdk/export/metric/aggregator/aggregator_test.go
  sdk/export/metric/metric.go
  sdk/metric/aggregator/array/array.go
  sdk/metric/aggregator/array/array_test.go
  sdk/metric/aggregator/ddsketch/ddsketch.go
  sdk/metric/aggregator/ddsketch/ddsketch_test.go
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
  sdk/metric/aggregator/lastvalue/lastvalue.go
  sdk/metric/aggregator/lastvalue/lastvalue_test.go
  sdk/metric/aggregator/minmaxsumcount/mmsc.go
  sdk/metric/aggregator/minmaxsumcount/mmsc_test.go
  sdk/metric/aggregator/sum/sum.go
  sdk/metric/aggregator/sum/sum_test.go
  sdk/metric/aggregator/test/test.go
  sdk/metric/batcher/defaultkeys/defaultkeys.go
  sdk/metric/batcher/defaultkeys/defaultkeys_test.go
  sdk/metric/batcher/test/test.go
  sdk/metric/batcher/ungrouped/ungrouped.go
  sdk/metric/batcher/ungrouped/ungrouped_test.go
  sdk/metric/benchmark_test.go
  sdk/metric/controller/push/push.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/correct_test.go
  sdk/metric/histogram_stress_test.go
  sdk/metric/minmaxsumcount_stress_test.go
  sdk/metric/sdk.go
  sdk/metric/selector/simple/simple.go
  sdk/metric/selector/simple/simple_test.go
  sdk/metric/stress_test.go
Labels: metrics

#580 Unique instrument checking
  api/global/internal/benchmark_test.go
  api/global/internal/meter.go
  api/global/internal/meter_test.go
  api/global/internal/registry_test.go
  api/global/internal/state.go
  api/metric/api.go
  api/metric/api_test.go
  api/metric/observer.go
  api/metric/registry/registry.go
  api/metric/registry/registry_test.go
  api/metric/sdkhelpers.go
  internal/metric/mock.go
  sdk/metric/benchmark_test.go
  sdk/metric/controller/push/push.go
  sdk/metric/correct_test.go
  sdk/metric/stress_test.go
Labels: metrics

#591 Remove dogstatsd and statsd support
  exporters/metric/dogstatsd/dogstatsd.go
  exporters/metric/dogstatsd/dogstatsd_test.go
  exporters/metric/dogstatsd/example_test.go
  exporters/metric/internal/statsd/conn.go
  exporters/metric/internal/statsd/conn_test.go
  exporters/metric/internal/statsd/labels.go
  exporters/metric/internal/statsd/labels_test.go
Labels: metrics

#594 Add a RecordBatch benchmark
  sdk/metric/benchmark_test.go
Labels: metrics

#599 Process the queue until no data but respect max batch size
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
Labels: trace
