Repository open-telemetry/opentelemetry-go, pull requests merged in 2020-05, with the labels that each got.

#683 fix interceptor regexp
  plugin/grpctrace/interceptor.go
  plugin/grpctrace/interceptor_test.go
Labels: bug

#710 Metric SDK renames to align with draft SDK spec
  api/global/internal/benchmark_test.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/stdout/stdout.go
  exporters/otlp/otlp_integration_test.go
  sdk/export/metric/metric.go
  sdk/metric/benchmark_test.go
  sdk/metric/controller/push/push.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/correct_test.go
  sdk/metric/doc.go
  sdk/metric/integrator/simple/simple.go
  sdk/metric/integrator/simple/simple_test.go
  sdk/metric/integrator/test/test.go
  sdk/metric/sdk.go
  sdk/metric/stress_test.go
Labels: metrics

#709 Make Meter a struct, simplify the global Meter
  api/global/global_test.go
  api/global/internal/meter.go
  api/global/internal/meter_test.go
  api/metric/api.go
  api/metric/noop.go
  api/metric/observer.go
  api/metric/sdkhelpers.go
Labels: metrics

#717 Batch Observer callback support
  api/global/internal/meter.go
  api/metric/api.go
  api/metric/api_test.go
  api/metric/must.go
  api/metric/observer.go
  api/metric/registry/registry.go
  api/metric/sdkhelpers.go
  internal/metric/async.go
  internal/metric/mock.go
  sdk/metric/correct_test.go
  sdk/metric/sdk.go
Labels: metrics

#727 Update correlation context header name
  api/correlation/correlation_context_propagator.go
  api/correlation/correlation_context_propagator_test.go
Labels: trace

#736 Histogram aggregator initial state (fix #735)
  exporters/metric/prometheus/example_test.go
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
Labels: metrics

#734 Rename Observer to ValueObserver
  api/global/internal/meter_test.go
  api/global/internal/registry_test.go
  api/metric/api_test.go
  api/metric/async.go
  api/metric/kind.go
  api/metric/kind_string.go
  api/metric/meter.go
  api/metric/must.go
  api/metric/observer.go
  api/metric/registry/registry_test.go
  api/metric/sync.go
  example/basic/main.go
  example/prometheus/main.go
  exporters/metric/prometheus/prometheus_test.go
  exporters/metric/stdout/stdout_test.go
  exporters/otlp/otlp_integration_test.go
  sdk/export/metric/aggregator/aggregator_test.go
  sdk/metric/aggregator/lastvalue/lastvalue_test.go
  sdk/metric/benchmark_test.go
  sdk/metric/correct_test.go
  sdk/metric/integrator/test/test.go
  sdk/metric/selector/simple/simple.go
  sdk/metric/selector/simple/simple_test.go
Labels: metrics

#739 Move Resource into the metric export Record
  exporters/metric/prometheus/example_test.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/prometheus/prometheus_test.go
  exporters/metric/stdout/stdout.go
  exporters/metric/stdout/stdout_test.go
  exporters/metric/test/test.go
  exporters/otlp/internal/transform/metric.go
  exporters/otlp/otlp.go
  exporters/otlp/otlp_metric_test.go
  sdk/export/metric/metric.go
  sdk/metric/config.go
  sdk/metric/controller/push/push.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/correct_test.go
  sdk/metric/integrator/simple/simple.go
  sdk/metric/integrator/simple/simple_test.go
  sdk/metric/integrator/test/test.go
  sdk/metric/sdk.go
Labels: metrics

#737 Refactor the api/metrics push controller; add CheckpointSet synchronization
  example/prometheus/main.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/prometheus/prometheus_test.go
  exporters/metric/stdout/example_test.go
  exporters/metric/stdout/stdout.go
  exporters/metric/test/test.go
  exporters/otlp/otlp_integration_test.go
  exporters/otlp/otlp_metric_test.go
  sdk/export/metric/metric.go
  sdk/metric/controller/push/config.go
  sdk/metric/controller/push/push.go
  sdk/metric/controller/push/push_test.go
  sdk/metric/controller/test/test.go
  sdk/metric/controller/time/time.go
  sdk/metric/example_test.go
  sdk/metric/integrator/simple/simple.go
  sdk/metric/integrator/simple/simple_test.go
  sdk/metric/sdk.go
Labels: metrics

#745 Add the UpDownCounter instrument
  api/metric/api_test.go
  api/metric/kind.go
  api/metric/kind_string.go
  api/metric/meter.go
  api/metric/must.go
  api/metric/sync.go
  api/metric/updowncounter.go
  sdk/metric/correct_test.go
Labels: metrics

#747 Add the SumObserver instrument
  api/metric/api_test.go
  api/metric/async.go
  api/metric/kind.go
  api/metric/kind_string.go
  api/metric/meter.go
  api/metric/must.go
  api/metric/observer.go
  sdk/export/metric/aggregator/aggregator.go
  sdk/metric/correct_test.go
Labels: metrics

#725 Support use of synchronous instruments in async callbacks
  api/global/internal/meter_test.go
  api/global/internal/registry_test.go
  api/metric/api_test.go
  api/metric/async.go
  api/metric/registry/registry_test.go
  example/basic/main.go
  example/prometheus/main.go
  exporters/otlp/otlp_integration_test.go
  internal/metric/async.go
  internal/metric/mock.go
  sdk/metric/benchmark_test.go
  sdk/metric/correct_test.go
  sdk/metric/sdk.go
Labels: metrics

#750 Add the UpDownSumObserver instrument
  api/metric/api_test.go
  api/metric/async.go
  api/metric/kind.go
  api/metric/kind_string.go
  api/metric/meter.go
  api/metric/must.go
  api/metric/observer.go
  sdk/metric/correct_test.go
  sdk/metric/sdk.go
Labels: metrics

#751 Add a pull controller, use it for Prometheus
  example/prometheus/main.go
  exporters/metric/prometheus/example_test.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/prometheus/prometheus_test.go
  sdk/metric/controller/pull/config.go
  sdk/metric/controller/pull/pull.go
  sdk/metric/controller/pull/pull_test.go
  sdk/metric/selector/simple/simple.go
Labels: metrics

#758 Use []float64 for histogram boundaries, not []metric.Number
  exporters/metric/prometheus/prometheus.go
  exporters/metric/prometheus/prometheus_test.go
  exporters/metric/test/test.go
  sdk/export/metric/aggregator/aggregator.go
  sdk/metric/aggregator/histogram/benchmark_test.go
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
  sdk/metric/aggregator/test/test.go
  sdk/metric/histogram_stress_test.go
  sdk/metric/selector/simple/simple.go
  sdk/metric/selector/simple/simple_test.go
Labels: metrics

#757 Add Prometheus resource support
  api/label/iterator.go
  api/label/iterator_test.go
  exporters/metric/prometheus/example_test.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/prometheus/prometheus_test.go
  sdk/resource/benchmark_test.go
  sdk/resource/resource.go
Labels: metrics

#761 Rename Register* to New*
  api/global/internal/meter_test.go
  api/global/internal/registry_test.go
  api/metric/api_test.go
  api/metric/meter.go
  api/metric/must.go
  api/metric/registry/registry_test.go
  example/basic/main.go
  example/prometheus/main.go
  exporters/otlp/otlp_integration_test.go
  sdk/metric/benchmark_test.go
  sdk/metric/correct_test.go
Labels: metrics

#781 Minor cleanups in sdk/metric/aggregator
  api/global/internal/benchmark_test.go
  exporters/metric/stdout/stdout_test.go
  sdk/metric/aggregator/ddsketch/ddsketch.go
  sdk/metric/aggregator/ddsketch/ddsketch_test.go
  sdk/metric/benchmark_test.go
  sdk/metric/integrator/simple/simple.go
  sdk/metric/selector/simple/simple.go
Labels: metrics
