Repository open-telemetry/opentelemetry-go, pull requests merged in 2020-09, with the labels that each got.

#1111 Make trace testhelpers public
  api/trace/tracetest/mock_span.go
  api/trace/tracetest/mock_tracer.go
  api/trace/tracetest/mock_tracer_test.go
  api/trace/tracetest/trace_context_propagator_benchmark_test.go
  api/trace/tracetest/trace_context_propagator_test.go
Labels: pkg:testing, priority:p1, release:required-for-ga

#1063 Add reconnecting udp connection type to jaeger exporter
  CHANGELOG.md
  example/jaeger/go.sum
  exporters/trace/jaeger/agent.go
  exporters/trace/jaeger/agent_test.go
  exporters/trace/jaeger/go.sum
  exporters/trace/jaeger/reconnecting_udp_client.go
  exporters/trace/jaeger/reconnecting_udp_client_test.go
  exporters/trace/jaeger/uploader.go
Labels: pkg:exporter

#1109 Update trace API TracerOption
  CHANGELOG.md
  api/trace/api.go
  api/trace/traceprovider_test.go
  api/trace/tracetest/provider.go
  sdk/trace/provider.go
Labels: area:trace, pkg:API, priority:p1, release:required-for-ga

#1108 Unify API Span Start/End Options
  CHANGELOG.md
  api/global/internal/trace.go
  api/trace/api.go
  api/trace/context_test.go
  api/trace/noop_span.go
  api/trace/noop_trace.go
  api/trace/span_test.go
  api/trace/tracetest/mock_span.go
  api/trace/tracetest/mock_tracer.go
  api/trace/tracetest/span.go
  api/trace/tracetest/span_test.go
  api/trace/tracetest/tracer.go
  api/trace/tracetest/tracer_test.go
  bridge/opentracing/bridge.go
  bridge/opentracing/internal/mock.go
  bridge/opentracing/wrapper.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  sdk/trace/tracer.go
Labels: area:trace, pkg:API, priority:p1, release:required-for-ga

#1118 Move propagators out of API and into their own package
  CHANGELOG.md
  api/global/internal/state.go
  api/trace/span_context.go
  propagators/b3.go
  propagators/b3_benchmark_test.go
  propagators/b3_data_test.go
  propagators/b3_example_test.go
  propagators/b3_integration_test.go
  propagators/b3_test.go
  propagators/doc.go
  propagators/propagators.go
  propagators/propagators_test.go
  propagators/trace_context.go
  propagators/trace_context_benchmark_test.go
  propagators/trace_context_example_test.go
  propagators/trace_context_test.go
Labels: pkg:API, priority:p1, release:required-for-ga

#1067 Add workflow to check for presence of CHANGELOG changes on PRs
  .github/workflows/changelog.yml
Labels: Skip Changelog

#1078 Correct SDK trace Exporter interface
  CHANGELOG.md
  example/namedtracer/main.go
  example/otel-collector/main.go
  exporters/otlp/README.md
  exporters/otlp/example_test.go
  exporters/otlp/otlp.go
  exporters/otlp/otlp_integration_test.go
  exporters/otlp/otlp_span_test.go
  exporters/otlp/otlp_test.go
  exporters/stdout/exporter.go
  exporters/stdout/trace.go
  exporters/stdout/trace_test.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/zipkin/zipkin.go
  exporters/trace/zipkin/zipkin_test.go
  sdk/export/trace/trace.go
  sdk/export/trace/tracetest/test.go
  sdk/export/trace/tracetest/test_test.go
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/benchmark_test.go
  sdk/trace/provider.go
  sdk/trace/simple_span_processor.go
  sdk/trace/simple_span_processor_test.go
  sdk/trace/trace_test.go
  sdk/trace/util_test.go
Labels: area:trace, pkg:SDK, priority:p1, release:required-for-ga

#1154 Document `make test` for testing
  CONTRIBUTING.md
Labels: Skip Changelog

#1156 Rename package.go to doc.go for consistency
  api/trace/tracetest/doc.go
Labels: Skip Changelog

#1157 Add the missing vanity import path directive
  codes/codes.go
Labels: Skip Changelog

#1159 Update CONTRIBUTING.md to reflect PR process-as-applied
  CONTRIBUTING.md
Labels: Skip Changelog, documentation

#1162 Allow up to 0.5% coverage change before failing build
  .github/codecov.yaml
Labels: Skip Changelog

#1176 Merge otel into one file and add package doc
  doc.go
  error_handler.go
  otel.go
Labels: Skip Changelog

#1185 Move api/unit to top level
  CHANGELOG.md
  api/metric/api_test.go
  api/metric/config.go
  api/metric/descriptor.go
  exporters/otlp/internal/transform/metric_test.go
  unit/doc.go
  unit/unit.go
Labels: pkg:API, priority:p1, release:required-for-ga

#1189 Remove flaky BatchSpanProcessor.ForceFlush() test
  sdk/trace/batch_span_processor_test.go
Labels: Skip Changelog

#1190 Rename *Provider names
  CHANGELOG.md
  api/global/internal/meter.go
  api/global/internal/meter_test.go
  api/global/internal/state.go
  api/global/internal/trace.go
  api/global/internal/trace_test.go
  api/global/metric.go
  api/global/metric_test.go
  api/global/trace.go
  api/global/trace_test.go
  api/metric/doc.go
  api/metric/meter.go
  api/metric/metrictest/meter.go
  api/metric/noop.go
  api/metric/registry/registry.go
  api/metric/registry/registry_test.go
  api/trace/api.go
  api/trace/noop_trace_provider.go
  api/trace/tracetest/provider.go
  api/trace/tracetest/span_test.go
  api/trace/tracetest/tracer_test.go
  bridge/opentracing/util.go
  bridge/opentracing/wrapper.go
  example/namedtracer/main.go
  example/otel-collector/main.go
  exporters/metric/prometheus/example_test.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/prometheus/prometheus_test.go
  exporters/otlp/README.md
  exporters/otlp/example_test.go
  exporters/otlp/otlp_integration_test.go
  exporters/stdout/exporter.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/zipkin/zipkin.go
  exporters/trace/zipkin/zipkin_test.go
  internal/trace/noop/noop.go
  sdk/metric/controller/pull/pull.go
  sdk/metric/controller/pull/pull_test.go
  sdk/metric/controller/push/push.go
  sdk/metric/controller/push/push_test.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/benchmark_test.go
  sdk/trace/provider.go
  sdk/trace/simple_span_processor_test.go
  sdk/trace/span_processor_test.go
  sdk/trace/trace_test.go
  sdk/trace/tracer.go
  sdk/trace/util_test.go
Labels: area:metrics, area:trace, pkg:API, pkg:SDK, priority:p1, release:required-for-ga

#1196 Add example test for a custom SpanProcessor
  sdk/trace/span_processor_example_test.go
Labels: Skip Changelog, documentation

#1207 Test benchmarks in precommit
  Makefile
  sdk/metric/benchmark_test.go
Labels: Skip Changelog
