Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-01, with the labels that each got.

#1430 Use uint64 Count consistently in metric aggregation
  CHANGELOG.md
  exporters/otlp/internal/transform/metric.go
  exporters/otlp/internal/transform/metric_test.go
  sdk/export/metric/aggregation/aggregation.go
  sdk/metric/aggregator/aggregatortest/test.go
  sdk/metric/aggregator/array/array.go
  sdk/metric/aggregator/array/array_test.go
  sdk/metric/aggregator/ddsketch/ddsketch.go
  sdk/metric/aggregator/ddsketch/ddsketch_test.go
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
  sdk/metric/aggregator/minmaxsumcount/mmsc.go
  sdk/metric/aggregator/minmaxsumcount/mmsc_test.go
  sdk/metric/correct_test.go
  sdk/metric/histogram_stress_test.go
  sdk/metric/minmaxsumcount_stress_test.go
Labels: area:metrics

#1436 Fix golint issue caused by typo in trace.go
  trace.go
Labels: Skip Changelog

#1438 Flush metric events before shutdown in collector example
  example/otel-collector/main.go
Labels: Skip Changelog

#1439 Remove CircleCI Builds
  .circleci/config.yml
Labels: Skip Changelog

#1440 Switch CircleCI badge to GitHub Actions
  README.md
Labels: Skip Changelog

#1441 Update exporters/otlp Readme.md
  exporters/otlp/README.md
Labels: Skip Changelog, bug, documentation

#1447 Handle tracestate in TraceContext propagator
  CHANGELOG.md
  propagation/trace_context.go
  propagation/trace_context_test.go
Labels: area:propagators, pkg:API

#1378 Combine the Push and Pull metric controllers
  .github/dependabot.yml
  .gitignore
  CHANGELOG.md
  example/basic/go.mod
  example/basic/go.sum
  example/basic/main.go
  example/otel-collector/main.go
  example/prom-collector/README.md
  example/prom-collector/go.mod
  example/prom-collector/go.sum
  example/prom-collector/main.go
  exporters/metric/prometheus/example_test.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/prometheus/prometheus_test.go
  exporters/otlp/internal/otlptest/otlptest.go
  exporters/otlp/otlpgrpc/example_test.go
  exporters/stdout/example_test.go
  exporters/stdout/exporter.go
  sdk/metric/controller/basic/config.go
  sdk/metric/controller/basic/config_test.go
  sdk/metric/controller/basic/controller.go
  sdk/metric/controller/basic/controller_test.go
  sdk/metric/controller/basic/pull_test.go
  sdk/metric/controller/basic/push_test.go
  sdk/metric/controller/pull/config.go
  sdk/metric/controller/pull/pull.go
  sdk/metric/controller/push/config.go
  sdk/metric/controller/push/push.go
  sdk/metric/sdk.go
Labels: area:metrics

#1435 Metric histogram aggregator: Swap in SynchronizedMove to avoid allocations
  CHANGELOG.md
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
Labels: area:metrics

#1452 Move Span Event to API
  CHANGELOG.md
  exporters/otlp/internal/otlptest/data.go
  exporters/otlp/internal/transform/span.go
  exporters/otlp/internal/transform/span_test.go
  exporters/stdout/trace_test.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/zipkin/model.go
  exporters/trace/zipkin/model_test.go
  sdk/export/trace/trace.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  trace/trace.go
Labels: area:trace, pkg:API, priority:p1, release:required-for-ga

#1468 Rename Makefile.proto to avoid interpretation as proto file
  .github/workflows/protogen.yml
  Makefile.protos
Labels: Skip Changelog

#1497 Update workflows to include main branch as trigger
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
Labels: Skip Changelog

#1481 Remove inaccurate and unnecessary import comment
  example/opencensus/main.go
Labels: Skip Changelog, documentation

#1498 Remove build flags for runtime/trace support
  sdk/trace/trace_go11.go
  sdk/trace/trace_nongo11.go
  sdk/trace/tracer.go
Labels: Skip Changelog
