Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-11, with the labels that each got.

#2369 Add Porto to dependancy list.
  Makefile
Labels: bug, Skip Changelog

#2355 Rephrase a sentence that has a typo in getting-started.md
  website_docs/getting-started.md
Labels: documentation, Skip Changelog

#2347 Minor grammatical fix
  website_docs/getting-started.md
Labels: documentation, Skip Changelog

#2370 Fix golint issue
  metric/sdkapi/noop.go
Labels: bug, documentation, Skip Changelog

#2376 Fix copy-paste error for noop SDK AsyncInstrument
  metric/sdkapi/noop.go
Labels: Skip Changelog

#2378 Upgrade packages
  .github/workflows/ci.yml
  bridge/opencensus/go.sum
  bridge/opencensus/test/go.sum
  example/opencensus/go.sum
  example/otel-collector/go.mod
  example/otel-collector/go.sum
  example/prometheus/go.sum
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/go.sum
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.sum
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/go.sum
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/go.sum
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.sum
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.sum
  exporters/prometheus/go.sum
  exporters/stdout/stdoutmetric/go.sum
  internal/tools/go.mod
  internal/tools/go.sum
  sdk/metric/go.mod
  sdk/metric/go.sum
Labels: Skip Changelog

#2373 Disables collectorConnectionDiesThenReconnects because it is flaky
  exporters/otlp/otlpmetric/otlpmetricgrpc/client_test.go
  exporters/otlp/otlptrace/otlptracegrpc/client_test.go
Labels: bug, Skip Changelog

#2380 [website_docs] Link to website spec pages
  website_docs/instrumentation.md
Labels: documentation, Skip Changelog

#2383 Fix imports in all files except generated files in jaeger exporter
  bridge/opencensus/exporter_test.go
  bridge/opentracing/internal/mock.go
  bridge/opentracing/mix_test.go
  bridge/opentracing/wrapper.go
  example/jaeger/main.go
  example/opencensus/main.go
  exporters/jaeger/agent.go
  exporters/jaeger/uploader.go
  exporters/otlp/otlpmetric/internal/connection/connection.go
  exporters/otlp/otlpmetric/internal/connection/connection_test.go
  exporters/otlp/otlpmetric/internal/metrictransform/attribute.go
  exporters/otlp/otlpmetric/internal/metrictransform/metric.go
  exporters/otlp/otlpmetric/internal/metrictransform/metric_test.go
  exporters/otlp/otlpmetric/internal/metrictransform/resource.go
  exporters/otlp/otlpmetric/internal/otlpconfig/options_test.go
  exporters/otlp/otlpmetric/internal/otlpmetrictest/otlptest.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/client.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/client_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/example_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/mock_collector_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/options.go
  exporters/otlp/otlpmetric/otlpmetrichttp/client.go
  exporters/otlp/otlpmetric/otlpmetrichttp/client_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/mock_collector_test.go
  exporters/otlp/otlptrace/exporter.go
  exporters/otlp/otlptrace/internal/connection/connection.go
  exporters/otlp/otlptrace/internal/connection/connection_test.go
  exporters/otlp/otlptrace/internal/otlpconfig/options_test.go
  exporters/otlp/otlptrace/internal/otlptracetest/otlptest.go
  exporters/otlp/otlptrace/internal/tracetransform/attribute.go
  exporters/otlp/otlptrace/internal/tracetransform/instrumentation.go
  exporters/otlp/otlptrace/internal/tracetransform/resource.go
  exporters/otlp/otlptrace/internal/tracetransform/span.go
  exporters/otlp/otlptrace/otlptracegrpc/client.go
  exporters/otlp/otlptrace/otlptracegrpc/client_test.go
  exporters/otlp/otlptrace/otlptracegrpc/mock_collector_test.go
  exporters/otlp/otlptrace/otlptracegrpc/options.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
  exporters/otlp/otlptrace/otlptracehttp/client_test.go
  exporters/otlp/otlptrace/otlptracehttp/mock_collector_test.go
  exporters/stdout/stdoutmetric/example_test.go
  exporters/stdout/stdoutmetric/metric_test.go
  exporters/zipkin/model.go
  metric/metric_test.go
  sdk/resource/os_unix_test.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/benchmark_test.go
  sdk/trace/provider.go
  sdk/trace/simple_span_processor_test.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  sdk/trace/tracer.go
  trace/trace_test.go
Labels: Skip Changelog

#2381 Fix TODO, use sync.Map to avoid blocking calls
  sdk/metric/controller/basic/controller.go
Labels: Skip Changelog

#2394 Update go.opentelemetry.io/proto/otel to v0.11.0
  example/otel-collector/go.sum
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/go.sum
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.sum
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/go.sum
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/go.sum
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.sum
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.sum
Labels: dependencies, go, Skip Changelog

#2395 Fix header level for Changed in Changelog
  CHANGELOG.md
Labels: documentation, Skip Changelog

#2398 [website_docs] Link to latest release
  website_docs/_index.md
Labels: documentation, Skip Changelog

#2400 Handle nil testSpanProcessor
  sdk/trace/span_processor_test.go
Labels: bug, Skip Changelog

#2397 [website_docs] Link to website page via path
  website_docs/getting-started.md
Labels: documentation, Skip Changelog

#2403 Fix golint issue
  exporters/otlp/otlpmetric/internal/metrictransform/metric.go
Labels: Skip Changelog

#2404 Make @MadVikingGod (Aaron Clawson) a maintainer
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#2409 Fix goroutine leaks in otlptracegrpc testing
  example/otel-collector/go.sum
  exporters/otlp/otlptrace/internal/connection/connection.go
  exporters/otlp/otlptrace/internal/otlptracetest/client.go
  exporters/otlp/otlptrace/internal/otlptracetest/otlptest.go
  exporters/otlp/otlptrace/otlptracegrpc/client_test.go
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.sum
  exporters/otlp/otlptrace/otlptracegrpc/mock_collector_test.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
Labels: bug, pkg:testing, Skip Changelog, pkg:exporter:otlp

#2405 Added Benchmarks around events
  sdk/trace/benchmark_test.go
Labels: Skip Changelog

#2407 Add a go version compatibility to the readme.
  README.md
Labels: documentation, Skip Changelog

#2411 Fix flaky test: TestExportSpansTimeoutHonored
  exporters/otlp/otlptrace/otlptracegrpc/client_test.go
Labels: bug, Skip Changelog

#2413 Update W3C Baggage specification link to latest stable
  propagation/baggage.go
  propagation/doc.go
Labels: documentation, Skip Changelog
