Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-08, with the labels that each got.

#2155 Remove `internal/semconv-gen`
  Makefile
  RELEASING.md
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/semconv-gen/generator.go
  internal/tools/tools.go
  semconv/template.j2
Labels: Skip Changelog, pkg:tooling

#2157 Update version.go
  version.go
Labels: Skip Changelog

#2159 Just a little typo fix in code documentation.
  trace/config.go
Labels: Skip Changelog, documentation

#2164 Add OpenCensus bridge internal package unit tests
  bridge/opencensus/internal/oc2otel/attributes_test.go
  bridge/opencensus/internal/oc2otel/tracer_start_options_test.go
  bridge/opencensus/internal/span_test.go
  bridge/opencensus/internal/tracer_test.go
Labels: pkg:bridges, Skip Changelog

#2165 Move OpenCensus bridge integration tests to their own module
  .github/dependabot.yml
  bridge/opencensus/go.mod
  bridge/opencensus/test/bridge_test.go
  bridge/opencensus/test/go.mod
  bridge/opencensus/test/go.sum
  bridge/opentracing/go.mod
  example/jaeger/go.mod
  example/namedtracer/go.mod
  example/opencensus/go.mod
  example/otel-collector/go.mod
  example/passthrough/go.mod
  example/prometheus/go.mod
  example/zipkin/go.mod
  exporters/jaeger/go.mod
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/prometheus/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  internal/metric/go.mod
  internal/tools/go.mod
  metric/go.mod
  oteltest/go.mod
  sdk/export/metric/go.mod
  sdk/go.mod
  sdk/metric/go.mod
  trace/go.mod
Labels: pkg:bridges, Skip Changelog

#2166 Deprecated the bridge/opencensus/utils package
  CHANGELOG.md
  bridge/opencensus/bridge.go
  bridge/opencensus/test/bridge_test.go
  bridge/opencensus/utils/utils.go
Labels: pkg:bridges

#2167 Refactor attributes benchmark tests
  attribute/benchmark_test.go
Labels: Skip Changelog

#2169 Add support for int32 in attribute.Any
  CHANGELOG.md
  attribute/kv.go
Labels: bug

#2168 Clarify the attribute package documentation and order/grouping
  attribute/key.go
  attribute/kv.go
  attribute/value.go
Labels: documentation, Skip Changelog

#2170 Unify the OTLP attribute transform
  exporters/otlp/otlpmetric/internal/metrictransform/attribute.go
  exporters/otlp/otlpmetric/internal/metrictransform/attribute_test.go
  exporters/otlp/otlpmetric/internal/metrictransform/metric.go
  exporters/otlp/otlpmetric/internal/metrictransform/metric_test.go
  exporters/otlp/otlpmetric/internal/metrictransform/resource_test.go
  exporters/otlp/otlptrace/internal/tracetransform/attribute.go
  exporters/otlp/otlptrace/internal/tracetransform/attribute_test.go
  exporters/otlp/otlptrace/internal/tracetransform/resource_test.go
  exporters/otlp/otlptrace/internal/tracetransform/span.go
  exporters/otlp/otlptrace/internal/tracetransform/span_test.go
Labels: Skip Changelog

#2178 Make the tracetest.SpanRecorder concurrent safe
  sdk/trace/tracetest/recorder.go
  sdk/trace/tracetest/recorder_test.go
Labels: Skip Changelog

#2120 Support a single Resource per MeterProvider in the SDK
  CHANGELOG.md
  bridge/opencensus/exporter.go
  bridge/opencensus/exporter_test.go
  exporters/otlp/otlpmetric/exporter.go
  exporters/otlp/otlpmetric/exporter_test.go
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/internal/metrictransform/metric.go
  exporters/otlp/otlpmetric/internal/metrictransform/metric_test.go
  exporters/otlp/otlpmetric/internal/otlpmetrictest/data.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/client_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/client_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/prometheus/prometheus.go
  exporters/stdout/stdoutmetric/metric.go
  exporters/stdout/stdoutmetric/metric_test.go
  sdk/export/metric/metric.go
  sdk/metric/benchmark_test.go
  sdk/metric/controller/basic/config.go
  sdk/metric/controller/basic/controller.go
  sdk/metric/controller/basic/controller_test.go
  sdk/metric/correct_test.go
  sdk/metric/processor/basic/basic.go
  sdk/metric/processor/basic/basic_test.go
  sdk/metric/processor/processortest/test.go
  sdk/metric/processor/processortest/test_test.go
  sdk/metric/processor/reducer/reducer.go
  sdk/metric/processor/reducer/reducer_test.go
  sdk/metric/sdk.go
  sdk/metric/stress_test.go
Labels: area:metrics

#2182 Add cross-module test coverage
  Makefile
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: Skip Changelog

#2189 Website: support GH page links to canonical src
  website_docs/_index.md
Labels: documentation, Skip Changelog

#2210 Update otel example guide
  example/otel-collector/README.md
Labels: bug, pkg:example, Skip Changelog

#2201 Fix typos in resource.go.
  CHANGELOG.md
  sdk/resource/resource.go
Labels: Skip Changelog

#2191 chore(exporter/zipkin): improves logging on invalid collector.
  exporters/zipkin/zipkin.go
  exporters/zipkin/zipkin_test.go
Labels: Skip Changelog
