Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-09, with the labels that each got.

#2212 Update trace API config creation functions
  CHANGELOG.md
  bridge/opencensus/internal/span_test.go
  bridge/opentracing/internal/mock.go
  internal/global/trace.go
  sdk/trace/tracer.go
  trace/config.go
  trace/config_test.go
Labels: bug

#2053 Verify and update OTLP trace exporter documentation
  exporters/otlp/otlptrace/README.md
  exporters/otlp/otlptrace/otlptracehttp/example_test.go
  exporters/otlp/otlptrace/otlptracehttp/go.mod
Labels: documentation, Skip Changelog, pkg:exporter:otlp

#2213 Refactor SDK span creation and implementation
  sdk/trace/span.go
  sdk/trace/trace_test.go
  sdk/trace/tracer.go
Labels: pkg:SDK, area:trace, Skip Changelog

#2222 otlptrace: Document supported environment variables
  exporters/otlp/otlptrace/README.md
Labels: documentation, Skip Changelog

#2224 Fix the import comments of otlpconfig
  exporters/otlp/otlptrace/internal/otlpconfig/options.go
Labels: Skip Changelog

#2227 Add tests for nil *Resource
  sdk/resource/resource.go
  sdk/resource/resource_test.go
Labels: Skip Changelog

#2239 Fix RC tags in docs
  VERSIONING.md
Labels: Skip Changelog

#2262 Bump google.golang.org/grpc in /exporters/otlp/otlp{metric,trace}/otlptracegrpc
  example/otel-collector/go.mod
  example/otel-collector/go.sum
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/go.sum
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.sum
  exporters/otlp/otlpmetric/otlpmetrichttp/go.sum
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/go.sum
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.sum
  exporters/otlp/otlptrace/otlptracehttp/go.sum
Labels: Skip Changelog

#2255 chore: adds vanity import check.
  .github/workflows/ci.yml
  Makefile
  attribute/type_string.go
  baggage/baggage.go
  bridge/opencensus/aggregation.go
  bridge/opencensus/bridge.go
  bridge/opencensus/exporter.go
  example/passthrough/handler/handler.go
  exporters/otlp/otlpmetric/exporter.go
  exporters/otlp/otlpmetric/options.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/options.go
  exporters/otlp/otlpmetric/otlpmetrichttp/client.go
  exporters/otlp/otlpmetric/otlpmetrichttp/options.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
  exporters/otlp/otlptrace/otlptracehttp/options.go
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
  metric/number/kind_string.go
  metric/sdkapi/instrumentkind_string.go
  sdk/export/metric/exportkind_string.go
  sdk/trace/event.go
  sdk/trace/snapshot.go
  semconv/v1.4.0/exception.go
  semconv/v1.4.0/schema.go
  trace/tracestate.go
Labels: Skip Changelog

#2263 Add go-1.17-compatible build directives
  exporters/jaeger/assertsocketbuffersize_test.go
  sdk/metric/stress_test.go
  sdk/resource/export_common_unix_test.go
  sdk/resource/os_unix.go
  sdk/resource/os_unix_test.go
Labels: Skip Changelog
