Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-04, with the labels that each got.

#1758 add partial support for env var config to otlp/HTTP
  CHANGELOG.md
  exporters/otlp/otlphttp/driver.go
  exporters/otlp/otlphttp/driver_test.go
  exporters/otlp/otlphttp/envconfig.go
  exporters/otlp/otlphttp/envconfig_test.go
  exporters/otlp/otlphttp/mock_collector_test.go
  exporters/otlp/otlphttp/options.go
  exporters/otlp/otlphttp/options_test.go
Labels: release:1.0.0-rc.1

#1761 Fix Jaeger span status reporting and unify tag keys
  CHANGELOG.md
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
Labels: pkg:exporter, release:1.0.0-rc.1

#1747 Add opentelemetry.io docs
  website_docs/_index.md
  website_docs/exporting_data.md
  website_docs/getting-started.md
  website_docs/instrumentation.md
Labels: Skip Changelog, documentation

#1492 Adds semantic conventions for exceptions
  CHANGELOG.md
  bridge/opentracing/internal/mock.go
  oteltest/span.go
  oteltest/span_test.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  semconv/exception.go
  trace/trace.go
Labels: release:1.0.0-rc.1

#1768 Update precedence of event name in Jaeger exporter
  CHANGELOG.md
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
Labels: pkg:exporter

#1775 Add Bug report issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Skip Changelog

#1470 Refactor prometheus exporter tests to match file headers as well
  exporters/metric/prometheus/prometheus_test.go
Labels: Skip Changelog

#1778 Merge sdk/export/trace into sdk/trace
  CHANGELOG.md
  example/opencensus/main.go
  exporters/otlp/internal/otlptest/data.go
  exporters/otlp/internal/transform/span.go
  exporters/otlp/internal/transform/span_test.go
  exporters/otlp/otlp.go
  exporters/otlp/otlp_span_test.go
  exporters/otlp/otlp_test.go
  exporters/otlp/otlpgrpc/driver.go
  exporters/otlp/otlpgrpc/otlp_integration_test.go
  exporters/otlp/otlphttp/driver.go
  exporters/otlp/protocoldriver.go
  exporters/stdout/exporter.go
  exporters/stdout/trace.go
  exporters/stdout/trace_test.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/zipkin/model.go
  exporters/trace/zipkin/model_test.go
  exporters/trace/zipkin/zipkin.go
  exporters/trace/zipkin/zipkin_test.go
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/provider.go
  sdk/trace/simple_span_processor.go
  sdk/trace/simple_span_processor_test.go
  sdk/trace/span.go
  sdk/trace/span_exporter.go
  sdk/trace/span_processor_example_test.go
  sdk/trace/trace_test.go
  sdk/trace/tracetest/test.go
  sdk/trace/tracetest/test_test.go
Labels: release:1.0.0-rc.1

#1688 Zipkin Exporter: Adjust span transformation to comply with the spec
  CHANGELOG.md
  exporters/trace/zipkin/model.go
  exporters/trace/zipkin/model_test.go
  exporters/trace/zipkin/zipkin_test.go
Labels: release:1.0.0-rc.1

#1795 Fix golint issue caused by incorrect comment
  attribute/value.go
Labels: Skip Changelog

#1804 Remove the abandoned Process struct in Jaeger exporter
  CHANGELOG.md
  exporters/trace/jaeger/jaeger.go
Labels: pkg:exporter:jaeger, release:1.0.0-rc.1

#1808 Remove options field from Jaeger exporter
  exporters/trace/jaeger/jaeger.go
Labels: Skip Changelog

#1814 Fix flaky OTLP exporter reconnect test
  exporters/otlp/otlpgrpc/otlp_integration_test.go
Labels: Skip Changelog, bug, pkg:exporter:otlp

#1811 add support for env var configuration to otlp/gRPC
  CHANGELOG.md
  exporters/otlp/internal/otlpconfig/envconfig.go
  exporters/otlp/internal/otlpconfig/envconfig_test.go
  exporters/otlp/internal/otlpconfig/options.go
  exporters/otlp/internal/otlpconfig/options_test.go
  exporters/otlp/optiontypes.go
  exporters/otlp/otlpgrpc/connection.go
  exporters/otlp/otlpgrpc/driver.go
  exporters/otlp/otlpgrpc/options.go
  exporters/otlp/otlpgrpc/otlp_integration_test.go
  exporters/otlp/otlphttp/driver.go
  exporters/otlp/otlphttp/driver_test.go
  exporters/otlp/otlphttp/options.go
  exporters/otlp/otlphttp/options_test.go
Labels: pkg:exporter:otlp, release:1.0.0-rc.1

#1816 Fix OTLP testing flake: signal connection from mock collector
  CHANGELOG.md
  exporters/otlp/otlpgrpc/mock_collector_test.go
  exporters/otlp/otlpgrpc/otlp_integration_test.go
Labels: bug, pkg:exporter:otlp

#1805 Add ExportSpans benchmark to Jaeger exporter
  exporters/trace/jaeger/jaeger_benchmark_test.go
Labels: Skip Changelog, pkg:exporter:jaeger, pkg:testing, release:1.0.0-rc.1

#1807 Remove locking from Jaeger exporter shutdown/export
  exporters/trace/jaeger/jaeger.go
Labels: Skip Changelog, pkg:exporter:jaeger

#1809 Build context pipeline into Jaeger upload process
  exporters/trace/jaeger/agent.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/jaeger/uploader.go
Labels: Skip Changelog, pkg:exporter:jaeger, release:1.0.0-rc.1

#1806 Remove the WithDisabled option from Jaeger exporter
  CHANGELOG.md
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
Labels: pkg:exporter:jaeger, release:1.0.0-rc.1

#1822 Update Jaeger exporter convenience functions
  CHANGELOG.md
  example/jaeger/main.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
Labels: pkg:exporter:jaeger, release:1.0.0-rc.1

#1821 Adds support for timeout on the otlp/gRPC exporter
  CHANGELOG.md
  exporters/otlp/otlpgrpc/driver.go
  exporters/otlp/otlpgrpc/mock_collector_test.go
  exporters/otlp/otlpgrpc/options.go
  exporters/otlp/otlpgrpc/otlp_integration_test.go
Labels: pkg:exporter:otlp, release:1.0.0-rc.1

#1826 Update function docs in sdk.go
  sdk/metric/sdk.go
Labels: Skip Changelog, area:metrics, documentation

#1825 Remove the WithSDKOptions from the Jaeger exporter
  CHANGELOG.md
  example/jaeger/main.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
Labels: pkg:exporter:jaeger, release:1.0.0-rc.1

#1733 Add SpanProcessor example for Span annotation on start
  sdk/trace/span_processor_annotator_example_test.go
  sdk/trace/span_processor_filter_example_test.go
Labels: Skip Changelog, documentation

#1785 Fix default merging of resource attributes from environment variable
  CHANGELOG.md
  sdk/metric/controller/basic/config.go
  sdk/metric/controller/basic/controller_test.go
  sdk/resource/resource.go
  sdk/trace/provider.go
  sdk/trace/trace_test.go
Labels: release:1.0.0-rc.1

#1829 Fix flaky global ErrorHandler delegation test
  handler_test.go
Labels: Skip Changelog, bug, pkg:testing

#1830 Remove bundler from Jaeger exporter
  CHANGELOG.md
  example/jaeger/go.sum
  exporters/trace/jaeger/go.mod
  exporters/trace/jaeger/go.sum
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_benchmark_test.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/jaeger/uploader.go
Labels: pkg:exporter:jaeger, release:1.0.0-rc.1

#1831 Add feature request issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Skip Changelog

#1835 Fix Links documents
  sdk/trace/span.go
Labels: Skip Changelog, documentation

#1798 Change NewSplitDriver paramater and initialization
  CHANGELOG.md
  exporters/otlp/example_test.go
  exporters/otlp/options.go
  exporters/otlp/otlp_test.go
  exporters/otlp/otlpgrpc/example_test.go
  exporters/otlp/otlpgrpc/otlp_integration_test.go
  exporters/otlp/protocoldriver.go
Labels: pkg:exporter:otlp, release:1.0.0-rc.1

#1838 Update website_docs to v0.20.0
  website_docs/exporting_data.md
  website_docs/getting-started.md
  website_docs/instrumentation.md
Labels: Skip Changelog, documentation

#1839 Minor typo fixes to existing CHANGELOG entries
  CHANGELOG.md
Labels: Skip Changelog

#1842 Markdownlint
  .markdownlint.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  RELEASING.md
Labels: Skip Changelog, documentation

#1847 Fix golint issue caused by typo
  oteltest/provider.go
Labels: Skip Changelog

#1843 Update RELEASING.md
  RELEASING.md
Labels: Skip Changelog, documentation

#1844 Document the SimpleSpanProcessor is not for production use
  sdk/trace/provider.go
  sdk/trace/simple_span_processor.go
Labels: Skip Changelog, documentation

#1851 Handle Resource env error when non-nil
  CHANGELOG.md
  sdk/resource/resource.go
Labels: area:resources, bug

#1841 Refine configuration design docs
  CONTRIBUTING.md
Labels: Skip Changelog, documentation

#1857 Fixed typo in CHANGELOG
  CHANGELOG.md
Labels: Skip Changelog

#1854 Replace spaces to tabs in Go code snippets
  CONTRIBUTING.md
  bridge/opencensus/README.md
  website_docs/exporting_data.md
  website_docs/instrumentation.md
Labels: Skip Changelog, documentation

#1849 Add markdown lint GitHub action
  .github/workflows/markdown.yml
Labels: Skip Changelog

#1856 Honor context deadline or cancellation in SimpleSpanProcessor.Shutdown
  CHANGELOG.md
  sdk/trace/simple_span_processor.go
  sdk/trace/simple_span_processor_test.go
Labels: pkg:SDK, release:1.0.0-rc.1

#1860 drop failed to exporter batches and return error when forcing flush a span processor
  CHANGELOG.md
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
Labels: area:trace, pkg:SDK, release:1.0.0-rc.1

#1846 Move the Event type from the API to the SDK
  CHANGELOG.md
  exporters/otlp/internal/otlptest/data.go
  exporters/otlp/internal/transform/span.go
  exporters/otlp/internal/transform/span_test.go
  exporters/stdout/trace_test.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/zipkin/model.go
  exporters/trace/zipkin/model_test.go
  sdk/trace/event.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  trace/trace.go
Labels: area:trace, pkg:API, pkg:SDK, release:1.0.0-rc.1

#1863 Fix BatchSpanProcessor context done tests
  sdk/trace/batch_span_processor_test.go
Labels: Skip Changelog, area:trace, bug, pkg:SDK

#1832 Implement retry policy for the OTLP/gRPC exporter
  CHANGELOG.md
  example/otel-collector/go.sum
  example/prom-collector/go.sum
  exporters/otlp/README.md
  exporters/otlp/go.mod
  exporters/otlp/go.sum
  exporters/otlp/internal/otlpconfig/options.go
  exporters/otlp/otlpgrpc/connection.go
  exporters/otlp/otlpgrpc/connection_test.go
  exporters/otlp/otlpgrpc/driver.go
  exporters/otlp/otlpgrpc/mock_collector_test.go
  exporters/otlp/otlpgrpc/options.go
  exporters/otlp/otlpgrpc/otlp_integration_test.go
  exporters/otlp/retry.go
Labels: pkg:exporter:otlp, release:1.0.0-rc.1

#1855 remove Set.Encoded(Encoder) enconding cache
  CHANGELOG.md
  attribute/set.go
Labels: release:1.0.0-rc.1

#1864 Add documentation for tracer.Start()
  trace/trace.go
Labels: Skip Changelog, documentation
