Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-07, with the labels that each got.

#2047 Add @pellared as an Approver
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#2082 Add documentation guidelines and improve Jaeger exporter readme
  CONTRIBUTING.md
  exporters/jaeger/README.md
Labels: Skip Changelog

#2093 Update otel.Meter to global.Meter in Getting Started Document.(#2087)
  website_docs/getting-started.md
Labels: Skip Changelog

#2094 Ensure sample code in website_docs getting started page works
  website_docs/getting-started.md
Labels: Skip Changelog

#2106 Update release URL
  CHANGELOG.md
Labels: bug, documentation

#2104 Performance improvement: avoid creating multiple same read-only objects
  sdk/trace/span.go
Labels: Skip Changelog

#2102 Correct status transform in OTLP exporter
  CHANGELOG.md
  exporters/otlp/otlptrace/internal/tracetransform/span.go
  exporters/otlp/otlptrace/internal/tracetransform/span_test.go
Labels: pkg:exporter:otlp

#2109 Simplify trace context benchmark test
  propagation/trace_context_benchmark_test.go
Labels: Skip Changelog, area:propagators

#2108 Simplify trace_context tests
  CHANGELOG.md
  propagation/trace_context.go
  propagation/trace_context_test.go
Labels: area:propagators

#2111 Update internal/global/trace testing
  go.mod
  internal/global/trace_test.go
Labels: Skip Changelog

#2095 Unify OTLP exporter retry logic
  CHANGELOG.md
  exporters/otlp/otlptrace/internal/connection/connection.go
  exporters/otlp/otlptrace/internal/connection/connection_test.go
  exporters/otlp/otlptrace/internal/otlpconfig/options.go
  exporters/otlp/otlptrace/internal/otlpconfig/optiontypes.go
  exporters/otlp/otlptrace/internal/retry/retry.go
  exporters/otlp/otlptrace/internal/retry/retry_test.go
  exporters/otlp/otlptrace/otlptracegrpc/client_test.go
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/options.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
  exporters/otlp/otlptrace/otlptracehttp/client_test.go
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.sum
  exporters/otlp/otlptrace/otlptracehttp/mock_collector_test.go
  exporters/otlp/otlptrace/otlptracehttp/options.go
Labels: pkg:exporter:otlp

#2128 Rename sdk/trace/tracetest test.go -> exporter.go
  sdk/trace/tracetest/exporter.go
  sdk/trace/tracetest/exporter_test.go
Labels: Skip Changelog

#2134 Use semconv.SchemaURL in STDOUT exporter example
  exporters/stdout/stdouttrace/example_test.go
Labels: Skip Changelog

#2135 nit doc fix
  propagation/propagation.go
Labels: Skip Changelog, documentation

#2136 rename assertsocketbuffersize.go to *_test
  exporters/jaeger/assertsocketbuffersize_test.go
  exporters/jaeger/assertsocketbuffersize_windows_test.go
Labels: Skip Changelog

#2132 Add a SpanRecorder to the sdk/trace/tracetest
  CHANGELOG.md
  sdk/trace/tracetest/recorder.go
  sdk/trace/tracetest/recorder_test.go
Labels: pkg:SDK

#2145 Update OpenCensus bridge docs with limitations
  bridge/opencensus/doc.go
Labels: Skip Changelog, documentation, pkg:bridges

#2147 Fix code sample in otel.GetTraceProvider
  trace.go
Labels: Skip Changelog
