Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-05, with the labels that each got.

#1869 Add markdown link check configuration and action
  .github/workflows/markdown.yml
  .markdown-link.json
Labels: Skip Changelog, documentation

#1876 Update README
  README.md
Labels: Skip Changelog, documentation

#1853 Split large jaeger span batch to admire the udp packet size limit
  CHANGELOG.md
  exporters/trace/jaeger/agent.go
  exporters/trace/jaeger/agent_test.go
  exporters/trace/jaeger/uploader.go
Labels: pkg:exporter:jaeger

#1873 Redefine ExportSpans of SpanExporter with ReadOnlySpan
  CHANGELOG.md
  exporters/otlp/internal/otlptest/data.go
  exporters/otlp/internal/transform/span.go
  exporters/otlp/internal/transform/span_test.go
  exporters/otlp/otlp.go
  exporters/otlp/otlp_span_test.go
  exporters/otlp/otlp_test.go
  exporters/otlp/otlpgrpc/driver.go
  exporters/otlp/otlpgrpc/otlp_integration_test.go
  exporters/otlp/otlphttp/driver.go
  exporters/otlp/otlphttp/driver_test.go
  exporters/otlp/protocoldriver.go
  exporters/stdout/trace.go
  exporters/stdout/trace_test.go
  exporters/trace/jaeger/agent_test.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_benchmark_test.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/zipkin/model.go
  exporters/trace/zipkin/model_test.go
  exporters/trace/zipkin/zipkin.go
  exporters/trace/zipkin/zipkin_test.go
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/simple_span_processor.go
  sdk/trace/simple_span_processor_test.go
  sdk/trace/snapshot.go
  sdk/trace/span.go
  sdk/trace/span_exporter.go
  sdk/trace/span_processor_filter_example_test.go
  sdk/trace/trace_test.go
  sdk/trace/tracetest/span.go
  sdk/trace/tracetest/test.go
  sdk/trace/tracetest/test_test.go
Labels: area:trace, pkg:SDK, release:1.0.0-rc.1

#1894 Fix some golint issues
  exporters/otlp/otlphttp/options.go
  oteltest/harness.go
Labels: Skip Changelog

#1899 Document functional options
  CONTRIBUTING.md
Labels: Skip Changelog

#1900 Remove the Tracer method from the Span API
  CHANGELOG.md
  bridge/opentracing/mix_test.go
  oteltest/harness.go
  oteltest/span.go
  oteltest/span_test.go
  sdk/trace/span.go
  trace/noop.go
  trace/noop_test.go
  trace/trace.go
Labels: area:trace, pkg:API, release:1.0.0-rc.1

#1901 Implement global default non-recording span
  CHANGELOG.md
  internal/global/trace.go
  internal/global/trace_test.go
Labels: area:trace, bug, release:1.0.0-rc.1

#1903 Move the unit package to the metric module
  CHANGELOG.md
  bridge/opencensus/exporter.go
  bridge/opencensus/exporter_test.go
  metric/config.go
  metric/metric.go
  metric/metric_test.go
  metric/unit/doc.go
  metric/unit/unit.go
Labels: area:metrics, release:1.0.0-rc.1

#1891 Semantic Convention generation tooling
  .github/dependabot.yml
  CHANGELOG.md
  Makefile
  RELEASING.md
  internal/tools/go.mod
  internal/tools/semconv-gen/generator.go
  internal/tools/semconv-gen/template.j2
  semconv/exception.go
  semconv/http.go
  semconv/http_test.go
  semconv/resource.go
  semconv/trace.go
Labels: release:1.0.0-rc.1

#1920 Create .gitattributes
  .gitattributes
Labels: Skip Changelog

#1906 Fix sporadic test failure in otlp exporter http driver
  exporters/otlp/otlphttp/driver_test.go
  exporters/otlp/otlphttp/mock_collector_test.go
Labels: Skip Changelog, bug

#1902 Add tracer option argument to global Tracer function
  CHANGELOG.md
  trace.go
Labels: area:trace, release:1.0.0-rc.1

#1923 Add @MadVikingGod as a project Approver
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#1931 Refactor Tracestate
  CHANGELOG.md
  exporters/otlp/go.mod
  exporters/otlp/internal/transform/span_test.go
  exporters/stdout/go.mod
  exporters/stdout/trace_test.go
  oteltest/go.mod
  oteltest/tracestate.go
  oteltest/tracestate_test.go
  propagation/trace_context.go
  propagation/trace_context_test.go
  sdk/trace/sampling_test.go
  sdk/trace/trace_test.go
  trace/trace.go
  trace/trace_test.go
  trace/tracestate.go
  trace/tracestate_test.go
Labels: area:trace, release:1.0.0-rc.1

#1947 Fix some golint issues
  sdk/metric/controller/basic/controller.go
  sdk/trace/tracetest/span.go
Labels: Skip Changelog

#1940 Add Codecov Badge
  README.md
Labels: Skip Changelog

#1949 Fix typo in doc
  website_docs/exporting_data.md
Labels: Skip Changelog

#1950 Small fixes on Span interface documentation headers
  trace/trace.go
Labels: Skip Changelog, documentation

#1922 OTLP trace gRPC exporter
  .github/dependabot.yml
  CHANGELOG.md
  Makefile
  bridge/opencensus/go.mod
  bridge/opentracing/go.mod
  example/jaeger/go.mod
  example/namedtracer/go.mod
  example/opencensus/go.mod
  example/otel-collector/go.mod
  example/passthrough/go.mod
  example/prom-collector/go.mod
  example/prometheus/go.mod
  example/zipkin/go.mod
  exporters/metric/prometheus/go.mod
  exporters/otlp/go.mod
  exporters/otlp/otlptrace/clients.go
  exporters/otlp/otlptrace/exporter.go
  exporters/otlp/otlptrace/exporter_test.go
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/go.sum
  exporters/otlp/otlptrace/internal/connection/alignment_test.go
  exporters/otlp/otlptrace/internal/connection/connection.go
  exporters/otlp/otlptrace/internal/connection/connection_test.go
  exporters/otlp/otlptrace/internal/otlpconfig/envconfig.go
  exporters/otlp/otlptrace/internal/otlpconfig/envconfig_test.go
  exporters/otlp/otlptrace/internal/otlpconfig/options.go
  exporters/otlp/otlptrace/internal/otlpconfig/options_test.go
  exporters/otlp/otlptrace/internal/otlpconfig/optiontypes.go
  exporters/otlp/otlptrace/internal/otlpconfig/tls.go
  exporters/otlp/otlptrace/internal/otlptracetest/client.go
  exporters/otlp/otlptrace/internal/otlptracetest/collector.go
  exporters/otlp/otlptrace/internal/otlptracetest/data.go
  exporters/otlp/otlptrace/internal/otlptracetest/otlptest.go
  exporters/otlp/otlptrace/internal/tracetransform/attribute.go
  exporters/otlp/otlptrace/internal/tracetransform/attribute_test.go
  exporters/otlp/otlptrace/internal/tracetransform/instrumentation.go
  exporters/otlp/otlptrace/internal/tracetransform/resource.go
  exporters/otlp/otlptrace/internal/tracetransform/resource_test.go
  exporters/otlp/otlptrace/internal/tracetransform/span.go
  exporters/otlp/otlptrace/internal/tracetransform/span_test.go
  exporters/otlp/otlptrace/otlptracegrpc/client.go
  exporters/otlp/otlptrace/otlptracegrpc/client_test.go
  exporters/otlp/otlptrace/otlptracegrpc/exporter.go
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.sum
  exporters/otlp/otlptrace/otlptracegrpc/mock_collector_test.go
  exporters/otlp/otlptrace/otlptracegrpc/options.go
  exporters/stdout/go.mod
  exporters/trace/jaeger/go.mod
  exporters/trace/zipkin/go.mod
  go.mod
  internal/tools/go.mod
  metric/go.mod
  oteltest/go.mod
  sdk/export/metric/go.mod
  sdk/go.mod
  sdk/metric/go.mod
  trace/go.mod
Labels: release:1.0.0-rc.1
