Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-03, with the labels that each got.

#1611 Update SpanProcessor docs
  sdk/trace/span_processor.go
Labels: Skip Changelog, documentation

#1610 Rename local var new to not collide with builtin
  sdk/trace/provider.go
Labels: Skip Changelog

#1634 Fix makefile ci target and coverage test packages
  Makefile
Labels: Skip Changelog, bug

#1607 Add TracerProvider tests to oteltest harness
  internal/matchers/expectation.go
  oteltest/harness.go
  sdk/trace/provider.go
  sdk/trace/trace_test.go
  trace/trace.go
Labels: Skip Changelog, pkg:testing

#1638 Unexport the simple and batch SpanProcessors
  CHANGELOG.md
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/simple_span_processor.go
Labels: pkg:SDK

#1586 Add HTTP/JSON to the otlp exporter
  CHANGELOG.md
  exporters/otlp/otlphttp/driver.go
  exporters/otlp/otlphttp/driver_test.go
  exporters/otlp/otlphttp/mock_collector_test.go
  exporters/otlp/otlphttp/options.go
Labels: release:required-for-ga

#1556 Add docs on when reviews should be cleared
  CONTRIBUTING.md
Labels: Skip Changelog, documentation

#1655 Add tests for propagation of Sampler Tracestate changes
  CHANGELOG.md
  sdk/trace/span.go
  sdk/trace/trace_test.go
Labels: area:trace, pkg:SDK, release:required-for-ga

#1626 Jaeger Exporter: Fix minor mapping discrepancies
  CHANGELOG.md
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
Labels: pkg:exporter, release:required-for-ga

#1612 Update the SimpleSpanProcessor
  CHANGELOG.md
  sdk/trace/simple_span_processor.go
  sdk/trace/simple_span_processor_test.go
Labels: release:required-for-ga

#1608 Add ForceFlush method to TracerProvider
  CHANGELOG.md
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/provider.go
  sdk/trace/provider_test.go
  sdk/trace/simple_span_processor.go
  sdk/trace/span_processor.go
  sdk/trace/span_processor_example_test.go
  sdk/trace/span_processor_test.go
Labels: area:trace, pkg:SDK, release:required-for-ga

#1566 chore(zipkin): improves zipkin example to not to depend on timeouts.
  example/zipkin/go.mod
  example/zipkin/main.go
Labels: Skip Changelog

#1676 Fix the examples target info messaging
  Makefile
Labels: Skip Changelog

#1633 Avoid overriding configuration of tracer provider
  CHANGELOG.md
  example/namedtracer/main.go
  example/otel-collector/main.go
  exporters/otlp/internal/otlptest/otlptest.go
  exporters/otlp/otlpgrpc/example_test.go
  exporters/otlp/otlpgrpc/otlp_integration_test.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
  sdk/trace/benchmark_test.go
  sdk/trace/provider.go
  sdk/trace/trace_test.go
  sdk/trace/util_test.go
Labels: area:trace, pkg:SDK

#1573 Make SpanContext Immutable
  CHANGELOG.md
  bridge/opencensus/bridge.go
  bridge/opencensus/bridge_test.go
  bridge/opencensus/utils/utils.go
  bridge/opencensus/utils/utils_test.go
  bridge/opentracing/internal/mock.go
  bridge/opentracing/mix_test.go
  exporters/otlp/internal/otlptest/data.go
  exporters/otlp/internal/transform/span.go
  exporters/otlp/internal/transform/span_test.go
  exporters/otlp/otlp_span_test.go
  exporters/stdout/trace_test.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/zipkin/model.go
  exporters/trace/zipkin/model_test.go
  exporters/trace/zipkin/zipkin_test.go
  oteltest/config.go
  oteltest/harness.go
  oteltest/tracer.go
  oteltest/tracer_test.go
  propagation/propagators_test.go
  propagation/trace_context.go
  propagation/trace_context_benchmark_test.go
  propagation/trace_context_test.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/benchmark_test.go
  sdk/trace/sampling.go
  sdk/trace/sampling_test.go
  sdk/trace/simple_span_processor_test.go
  sdk/trace/span.go
  sdk/trace/span_processor_test.go
  sdk/trace/trace_test.go
  trace/config_test.go
  trace/go.mod
  trace/trace.go
  trace/trace_test.go
Labels: pkg:SDK, release:required-for-ga

#1679 Remove trace prefix from trace_noop*.go
  trace/noop.go
  trace/noop_test.go
Labels: Skip Changelog

#1683 Update employer information for maintainers
  CONTRIBUTING.md
Labels: Skip Changelog

#1686 Fix synchronization issues in global trace delegate implementation
  CHANGELOG.md
  internal/global/trace.go
  internal/global/trace_test.go
Labels: bug

#1687 Fix issue #1490, apply same logic as in the SDK
  CHANGELOG.md
  internal/global/trace.go
  internal/global/trace_test.go
Labels: bug

#1665 Add a test to prove the Tracer is safe for concurrent calls
  internal/matchers/expectation.go
  internal/tools/tools.go
  oteltest/harness.go
Labels: Skip Changelog

#1720 Update the TraceContext.Extract docs
  propagation/trace_context.go
Labels: Skip Changelog, area:propagators, documentation

#1711 Remove makeSamplingDecision func
  sdk/trace/span.go
Labels: Skip Changelog

#1726 Remove links on NewRoot spans
  CHANGELOG.md
  bridge/opentracing/bridge.go
  bridge/opentracing/internal/mock.go
  internal/trace/parent/parent.go
  oteltest/tracer.go
  oteltest/tracer_test.go
  sdk/trace/span.go
  sdk/trace/tracer.go
Labels: release:1.0.0-rc.1

#1728 Remove hasRemoteParent field from SDK span
  sdk/trace/span.go
Labels: Skip Changelog

#1734 Reinstate @paivagustavo as an Approver
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#1745 Set @lizthegrey to emeritus status
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#1731 Store current Span instead of local and remote SpanContext in context.Context
  CHANGELOG.md
  bridge/opentracing/bridge.go
  bridge/opentracing/internal/mock.go
  oteltest/config.go
  oteltest/tracer.go
  oteltest/tracer_test.go
  propagation/propagators_test.go
  propagation/trace_context_test.go
  sdk/trace/span.go
  sdk/trace/span_processor_test.go
  trace/context.go
  trace/context_test.go
  trace/nonrecording.go
  trace/noop.go
  trace/trace.go
  trace/trace_test.go
Labels: release:1.0.0-rc.1

#1748 Update SpanSnapshot to use parent SpanContext
  CHANGELOG.md
  exporters/otlp/internal/otlptest/data.go
  exporters/otlp/internal/transform/span.go
  exporters/otlp/internal/transform/span_test.go
  exporters/otlp/otlp_span_test.go
  exporters/stdout/trace_test.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/zipkin/model.go
  exporters/trace/zipkin/model_test.go
  exporters/trace/zipkin/zipkin_test.go
  sdk/export/trace/trace.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
Labels: release:1.0.0-rc.1

#1749 Update SamplingParameters
  CHANGELOG.md
  sdk/trace/sampling.go
  sdk/trace/sampling_test.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  trace/context.go
  trace/context_test.go
Labels: release:1.0.0-rc.1
