Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-12, with the labels that each got.

#2427 Centralize the retry package for the otlp exporters
  .github/dependabot.yml
  bridge/opencensus/go.mod
  bridge/opencensus/test/go.mod
  bridge/opentracing/go.mod
  example/fib/go.mod
  example/jaeger/go.mod
  example/namedtracer/go.mod
  example/opencensus/go.mod
  example/otel-collector/go.mod
  example/passthrough/go.mod
  example/prometheus/go.mod
  example/zipkin/go.mod
  exporters/jaeger/go.mod
  exporters/otlp/internal/retry/go.mod
  exporters/otlp/internal/retry/go.sum
  exporters/otlp/internal/retry/retry.go
  exporters/otlp/internal/retry/retry_test.go
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/internal/otlpconfig/options.go
  exporters/otlp/otlpmetric/internal/retry/retry.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/client.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/options.go
  exporters/otlp/otlpmetric/otlpmetrichttp/client.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/options.go
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/internal/otlpconfig/options.go
  exporters/otlp/otlptrace/internal/retry/retry_test.go
  exporters/otlp/otlptrace/otlptracegrpc/client.go
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/options.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/otlptracehttp/options.go
  exporters/prometheus/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  internal/metric/go.mod
  internal/tools/go.mod
  metric/go.mod
  schema/go.mod
  sdk/export/metric/go.mod
  sdk/go.mod
  sdk/metric/go.mod
  trace/go.mod
Labels: Skip Changelog

#2424 Refactor ErrorHandler
  handler.go
  handler_test.go
Labels: Skip Changelog

#2433 Fix per-signal endpoint parsing in OTLP exporters
  CHANGELOG.md
  exporters/otlp/otlpmetric/internal/otlpconfig/envconfig.go
  exporters/otlp/otlpmetric/internal/otlpconfig/options_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/client.go
  exporters/otlp/otlptrace/README.md
  exporters/otlp/otlptrace/internal/otlpconfig/envconfig.go
  exporters/otlp/otlptrace/internal/otlpconfig/options_test.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
Labels: pkg:exporter:otlp

#2440 Fix Jaeger exporter status conversion
  CHANGELOG.md
  exporters/jaeger/jaeger.go
  exporters/jaeger/jaeger_test.go
Labels: bug, pkg:exporter:jaeger

#2446 Small nit in comments
  metric/sdkapi/sdkapi.go
Labels: documentation, area:metrics, Skip Changelog

#2437 Add 'Using instrumentation libraries' page for docs
  website_docs/manual_instrumentation.md
  website_docs/using_instrumentation_libraries.md
Labels: documentation, Skip Changelog

#2447 Remove unused internal interfaces
  internal/metric/global/meter.go
Labels: area:metrics, Skip Changelog

#2451 nit: Change metrics configs to have funcs on pointers
  metric/config.go
Labels: area:metrics, Skip Changelog

#2458 Update affiliation for Sam Xie
  CONTRIBUTING.md
Labels: Skip Changelog

#2448 nit: Simplify test condition in trace_test.go
  trace_test.go
Labels: Skip Changelog

#2445 Deprecate and add warning to remove AtomicFieldOffsets, unnecessary public func
  CHANGELOG.md
  sdk/metric/alignment_test.go
  sdk/metric/atomicfields.go
Labels: area:metrics

#2444 Move Aggregator interface to aggregator package
  exporters/otlp/otlpmetric/exporter_test.go
  exporters/otlp/otlpmetric/internal/metrictransform/metric_test.go
  sdk/export/metric/metric.go
  sdk/metric/aggregator/aggregator.go
  sdk/metric/aggregator/aggregatortest/test.go
  sdk/metric/aggregator/histogram/histogram.go
  sdk/metric/aggregator/histogram/histogram_test.go
  sdk/metric/aggregator/lastvalue/lastvalue.go
  sdk/metric/aggregator/lastvalue/lastvalue_test.go
  sdk/metric/aggregator/sum/sum.go
  sdk/metric/aggregator/sum/sum_test.go
  sdk/metric/correct_test.go
  sdk/metric/export/metric.go
  sdk/metric/processor/basic/basic.go
  sdk/metric/processor/basic/basic_test.go
  sdk/metric/processor/processortest/test.go
  sdk/metric/sdk.go
  sdk/metric/selector/simple/simple.go
  sdk/metric/selector/simple/simple_test.go
Labels: area:metrics, Skip Changelog

#2459 Fixes broken sdk/metric benchmarks
  sdk/metric/benchmark_test.go
Labels: Skip Changelog

#2477 Dependabot bump
  bridge/opencensus/go.sum
  bridge/opencensus/test/go.sum
  bridge/opentracing/go.sum
  example/fib/go.sum
  example/jaeger/go.sum
  example/namedtracer/go.mod
  example/namedtracer/go.sum
  example/opencensus/go.sum
  example/otel-collector/go.mod
  example/otel-collector/go.sum
  example/otel-collector/main.go
  example/passthrough/go.sum
  example/prometheus/go.sum
  example/zipkin/go.sum
  exporters/jaeger/go.sum
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/go.sum
  exporters/otlp/otlpmetric/internal/otlpconfig/options.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.sum
  exporters/otlp/otlpmetric/otlpmetrichttp/go.sum
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/go.sum
  exporters/otlp/otlptrace/internal/otlpconfig/options.go
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.sum
  exporters/otlp/otlptrace/otlptracehttp/go.sum
  exporters/prometheus/go.sum
  exporters/stdout/stdoutmetric/go.sum
  exporters/stdout/stdouttrace/go.sum
  exporters/zipkin/go.sum
  go.mod
  go.sum
  internal/metric/go.sum
  metric/go.sum
  sdk/export/metric/go.sum
  sdk/go.sum
  sdk/metric/go.sum
  trace/go.sum
Labels: Skip Changelog

#2452 Add sections to docs for current span and nested spans
  website_docs/manual_instrumentation.md
Labels: documentation, Skip Changelog

#2478 Update relref link for manual instrumentation
  website_docs/getting-started.md
Labels: documentation, Skip Changelog

#2479 Change markdown links to relref
  website_docs/manual_instrumentation.md
  website_docs/using_instrumentation_libraries.md
Labels: documentation, Skip Changelog

#2480 Rename manual_instrumentation and add redirects
  website_docs/exporting_data.md
  website_docs/getting-started.md
  website_docs/libraries.md
  website_docs/manual.md
Labels: documentation, Skip Changelog

#2461 Fixes the instrument kind for noop async instruments
  CHANGELOG.md
  metric/sdkapi/noop.go
Labels: bug, area:metrics

#2454 Remove Min/Max unused interfaces from the moved code
  sdk/export/metric/aggregation/aggregation.go
  sdk/metric/export/aggregation/aggregation.go
Labels: area:metrics, Skip Changelog

#2482 Update relref link in manual instrumentation
  website_docs/manual.md
Labels: documentation, Skip Changelog

#2481 Add section in docs for initializing a tracer
  website_docs/manual.md
Labels: documentation, Skip Changelog

#2486 Update docs: don't reference `WithBuiltinDetectors`
  website_docs/exporting_data.md
Labels: Skip Changelog
