Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-06, with the labels that each got.

#1933 Generate semantic conventions according to specification version
  RELEASING.md
  internal/tools/go.mod
  internal/tools/semconv-gen/generator.go
  internal/tools/semconv-gen/template.j2
Labels: Skip Changelog

#1969 sdk/resource: honor OTEL_SERVICE_NAME in fromEnv resource detector
  CHANGELOG.md
  sdk/resource/env.go
  sdk/resource/env_test.go
Labels: area:resources, pkg:SDK, release:1.0.0-rc.1

#1967 Add baggage implementation based on the W3C and OpenTelemetry specification
  CHANGELOG.md
  baggage/baggage.go
  baggage/baggage_test.go
  baggage/context.go
  baggage/context_test.go
  bridge/opentracing/bridge.go
  bridge/opentracing/internal/mock.go
  bridge/opentracing/mix_test.go
  example/namedtracer/main.go
  internal/baggage/baggage.go
  internal/baggage/baggage_test.go
  internal/baggage/context.go
  internal/baggage/context_test.go
  propagation/baggage.go
  propagation/baggage_test.go
Labels: area:baggage, release:1.0.0-rc.1

#1930 Use mock server as jaeger agent listener
  exporters/trace/jaeger/agent_test.go
Labels: Skip Changelog

#1946 Replaces golint by revive and fix newly reported linter issues
  .golangci.yml
  baggage/context.go
  bridge/opentracing/internal/mock.go
  exporters/otlp/internal/otlpconfig/tls.go
  exporters/otlp/otlphttp/driver.go
  internal/matchers/temporal_matcher.go
  internal/metric/async.go
  metric/unit/unit.go
  propagation/propagation_test.go
  sdk/export/metric/aggregation/aggregation.go
  sdk/export/metric/metric.go
  sdk/export/metric/metrictest/test.go
  sdk/metric/aggregator/aggregatortest/test.go
  sdk/metric/controller/basic/controller.go
  sdk/metric/processor/basic/basic.go
  sdk/metric/sdk.go
  sdk/resource/resource.go
  sdk/trace/batch_span_processor.go
  sdk/trace/sampling.go
  sdk/trace/sampling_test.go
  sdk/trace/trace_test.go
  semconv/http.go
  trace/config.go
  trace/trace.go
  trace/tracestate.go
Labels: Skip Changelog

#1977 Fix generator.go call typo in RELEASING.md
  RELEASING.md
Labels: Skip Changelog

#1983 Add caveat about installing opencensus bridge
  bridge/opencensus/README.md
Labels: Skip Changelog, documentation

#1982 Test BatchSpanProcessor export timeout directly
  sdk/trace/batch_span_processor_test.go
Labels: Skip Changelog, bug

#1985 Refactor exporter creation functions
  CHANGELOG.md
  bridge/opencensus/README.md
  example/jaeger/main.go
  example/namedtracer/main.go
  example/opencensus/main.go
  example/otel-collector/main.go
  example/passthrough/README.md
  example/passthrough/main.go
  example/prom-collector/main.go
  example/prometheus/go.mod
  example/prometheus/main.go
  example/zipkin/main.go
  exporters/metric/prometheus/example_test.go
  exporters/metric/prometheus/prometheus.go
  exporters/metric/prometheus/prometheus_test.go
  exporters/otlp/README.md
  exporters/otlp/example_test.go
  exporters/otlp/otlp.go
  exporters/otlp/otlp_test.go
  exporters/otlp/otlpgrpc/example_test.go
  exporters/otlp/otlpgrpc/otlp_integration_test.go
  exporters/otlp/otlphttp/driver_test.go
  exporters/otlp/otlptrace/exporter.go
  exporters/otlp/otlptrace/exporter_test.go
  exporters/otlp/otlptrace/internal/otlptracetest/client.go
  exporters/otlp/otlptrace/otlptracegrpc/client_test.go
  exporters/otlp/otlptrace/otlptracegrpc/exporter.go
  exporters/otlp/otlptrace/otlptracehttp/client_test.go
  exporters/otlp/otlptrace/otlptracehttp/exporter.go
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/stdout/example_test.go
  exporters/stdout/exporter.go
  exporters/stdout/metric_test.go
  exporters/stdout/trace_test.go
  exporters/trace/jaeger/agent_test.go
  exporters/trace/jaeger/env_test.go
  exporters/trace/jaeger/jaeger.go
  exporters/trace/jaeger/jaeger_benchmark_test.go
  exporters/trace/jaeger/jaeger_test.go
  exporters/trace/zipkin/zipkin.go
  exporters/trace/zipkin/zipkin_test.go
  sdk/metric/controller/basic/controller_test.go
  sdk/metric/controller/basic/push_test.go
  sdk/metric/processor/basic/basic_test.go
  sdk/metric/processor/processortest/test.go
  sdk/metric/processor/processortest/test_test.go
  sdk/metric/processor/reducer/reducer_test.go
  website_docs/getting-started.md
Labels: pkg:example, pkg:exporter:jaeger, pkg:exporter:otlp, pkg:exporter:prometheus, pkg:exporter:stdout, pkg:exporter:zipkin, release:1.0.0-rc.1

#1978 Moved internal/tools duplicated findRepoRoot function to common package
  internal/tools/common.go
  internal/tools/crosslink/crosslink.go
  internal/tools/semconv-gen/generator.go
Labels: Skip Changelog

#1997 remove WithTrace* options from otlptrace exporters
  exporters/otlp/otlptrace/internal/otlpconfig/envconfig.go
  exporters/otlp/otlptrace/internal/otlpconfig/options.go
  exporters/otlp/otlptrace/internal/otlpconfig/options_test.go
  exporters/otlp/otlptrace/otlptracegrpc/options.go
  exporters/otlp/otlptrace/otlptracehttp/options.go
Labels: Skip Changelog

#2006 Update codecov ignore
  .github/codecov.yaml
Labels: Skip Changelog

#2007 Replace WithSyncer with WithBatcher in opencensus example
  example/opencensus/main.go
Labels: Skip Changelog, pkg:example

#2004 Add more tests for trace package.
  trace/trace_test.go
Labels: Skip Changelog

#2012 Interface stability documentation
  CONTRIBUTING.md
  VERSIONING.md
  error_handler.go
  exporters/otlp/otlptrace/clients.go
  propagation/propagation.go
  sdk/resource/auto.go
  sdk/trace/id_generator.go
  sdk/trace/sampling.go
  sdk/trace/span.go
  sdk/trace/span_exporter.go
  sdk/trace/span_processor.go
  trace/trace.go
Labels: Skip Changelog, documentation

#2017 Update project status in README
  README.md
Labels: Skip Changelog, documentation

#2029 Fix documentation for trace.Status
  sdk/trace/span.go
Labels: Skip Changelog, documentation

#2030 Update OpenTracing bridge godoc
  bridge/opentracing/doc.go
Labels: Skip Changelog, documentation

#2034 Fix docs on otel-collector example
  example/otel-collector/README.md
Labels: Skip Changelog

#2033 semconv-gen: fix capitalization at word boundaries, add stability/deprecation indicators
  internal/tools/semconv-gen/generator.go
  internal/tools/semconv-gen/template.j2
  semconv/v1.4.0/resource.go
  semconv/v1.4.0/trace.go
Labels: Skip Changelog

#2032 When using WithNewRoot, don't use the parent context for sampling
  CHANGELOG.md
  sdk/trace/span.go
  sdk/trace/trace_test.go
Labels: area:trace
