Repository open-telemetry/opentelemetry-go, pull requests merged in 2021-02, with the labels that each got.

#1487 Fix golint error of package comment form
  bridge/opentracing/doc.go
  bridge/opentracing/migration/api.go
  exporters/trace/jaeger/reconnecting_udp_client.go
  sdk/export/trace/tracetest/test.go
Labels: Skip Changelog

#1510 nit: Fix comment to be up-to-date
  trace.go
Labels: Skip Changelog, documentation

#1488 Code Improvement - Error strings should not be capitalized
  exporters/otlp/otlphttp/driver.go
  metric/registry/registry.go
Labels: Skip Changelog

#1543 SDK span no modification after ended
  sdk/trace/span.go
Labels: Skip Changelog

#1552 Remove vendor exclude from license-check
  Makefile
Labels: Skip Changelog

#1554 Update docs from gitter to slack for communication
  CONTRIBUTING.md
  README.md
Labels: Skip Changelog, documentation

#1577 Fix Windows build of Jaeger tests
  CHANGELOG.md
  exporters/trace/jaeger/assertsocketbuffersize.go
  exporters/trace/jaeger/assertsocketbuffersize_windows.go
  exporters/trace/jaeger/reconnecting_udp_client_test.go
Labels: bug

#1580 Unify the Added sections of the unreleased changes
  CHANGELOG.md
Labels: documentation

#1579 Make timestamps sequential in lastvalue agg check
  CHANGELOG.md
  sdk/metric/aggregator/lastvalue/lastvalue_test.go
Labels: bug

#1581 Fix validation for tracestate with vendor and add tests
  CHANGELOG.md
  trace/trace.go
  trace/trace_test.go
Labels: area:trace, pkg:API, release:required-for-ga
