Repository open-telemetry/opentelemetry-go, pull requests merged in 2022-01, with the labels that each got.

#2493 fix specify explicit buckets in example
  CHANGELOG.md
  example/prometheus/main.go
Labels: pkg:example

#2496 Fix sporadic test failure in otlp exporter http client tests
  exporters/otlp/otlpmetric/otlpmetrichttp/client_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/mock_collector_test.go
  exporters/otlp/otlptrace/otlptracehttp/client_test.go
  exporters/otlp/otlptrace/otlptracehttp/mock_collector_test.go
Labels: bug, Skip Changelog

#2487 Add Float64CounterObserver and Float64UpDownCounterObserver Tests
  exporters/prometheus/prometheus_test.go
Labels: Skip Changelog

#2506 Remove old release bash scripts
  RELEASING.md
  pre_release.sh
  tag.sh
Labels: Skip Changelog

#2524 Fix typo in jaeger example
  example/jaeger/main.go
Labels: Skip Changelog

#2520 Fix some typos in docs for Go libraries
  website_docs/libraries.md
Labels: documentation, blocked:CLA, Skip Changelog

#2527 Fix getting-started.md Run function
  example/fib/app.go
  website_docs/getting-started.md
Labels: Skip Changelog

#2545 Bump github.com/google/go-cmp from 0.5.6 to 0.5.7 across the project
  bridge/opencensus/go.sum
  bridge/opencensus/test/go.sum
  bridge/opentracing/go.sum
  example/fib/go.sum
  example/jaeger/go.sum
  example/namedtracer/go.sum
  example/opencensus/go.sum
  example/otel-collector/go.sum
  example/passthrough/go.sum
  example/prometheus/go.sum
  example/zipkin/go.sum
  exporters/jaeger/go.mod
  exporters/jaeger/go.sum
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/go.sum
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.sum
  exporters/otlp/otlpmetric/otlpmetrichttp/go.sum
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/go.sum
  exporters/otlp/otlptrace/otlptracegrpc/go.sum
  exporters/otlp/otlptrace/otlptracehttp/go.sum
  exporters/prometheus/go.sum
  exporters/stdout/stdoutmetric/go.sum
  exporters/stdout/stdouttrace/go.sum
  exporters/zipkin/go.mod
  exporters/zipkin/go.sum
  go.mod
  go.sum
  internal/metric/go.sum
  metric/go.mod
  metric/go.sum
  sdk/export/metric/go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/metric/go.sum
  trace/go.mod
  trace/go.sum
Labels: Skip Changelog

#2549 Remove unused sdk/internal/santize
  sdk/internal/sanitize.go
  sdk/internal/sanitize_test.go
Labels: Skip Changelog

#2551 Add links to code examples and docs in the getting started website docs
  website_docs/getting-started.md
Labels: documentation, Skip Changelog

#2556 Optimize evictedQueue implementation and use
  sdk/trace/evictedqueue.go
  sdk/trace/span.go
Labels: Skip Changelog

#2562 Fix TestBackoffRetry in otlp/internal/retry package
  exporters/otlp/internal/retry/retry_test.go
Labels: bug, pkg:testing, Skip Changelog
