Repository open-telemetry/opentelemetry-go, pull requests merged in 2022-03, with the labels that each got.

#2643 Remove old prom-collector depandence
  .gitignore
  bridge/opencensus/go.mod
  bridge/opentracing/go.mod
  example/jaeger/go.mod
  example/namedtracer/go.mod
  example/opencensus/go.mod
  example/otel-collector/go.mod
  example/passthrough/go.mod
  example/prometheus/go.mod
  example/zipkin/go.mod
  exporters/jaeger/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/prometheus/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  internal/metric/go.mod
  metric/go.mod
  sdk/export/metric/go.mod
  sdk/go.mod
  sdk/metric/go.mod
  trace/go.mod
Labels: Skip Changelog

#2652 Fix typo in go libraries
  website_docs/libraries.md
Labels: Skip Changelog

#2649 Double benchmark alert threshold
  .github/workflows/benchmark.yml
Labels: Skip Changelog

#2662 Update otel-collector example readme
  example/otel-collector/README.md
Labels: documentation, pkg:example, Skip Changelog

#2666 [website_docs] Fix link intra-site link refs
  .markdown-link.json
  website_docs/libraries.md
Labels: documentation, Skip Changelog

#2710 Update versions of dependences
  bridge/opencensus/go.sum
  bridge/opencensus/test/go.sum
  bridge/opentracing/go.sum
  example/fib/go.sum
  example/jaeger/go.sum
  example/namedtracer/go.sum
  example/opencensus/go.sum
  example/otel-collector/go.sum
  example/passthrough/go.sum
  example/prometheus/go.sum
  example/zipkin/go.sum
  exporters/jaeger/go.mod
  exporters/jaeger/go.sum
  exporters/otlp/internal/retry/go.mod
  exporters/otlp/internal/retry/go.sum
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/go.sum
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.sum
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/go.sum
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/go.sum
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.sum
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.sum
  exporters/prometheus/go.mod
  exporters/prometheus/go.sum
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdoutmetric/go.sum
  exporters/stdout/stdouttrace/go.mod
  exporters/stdout/stdouttrace/go.sum
  exporters/zipkin/go.mod
  exporters/zipkin/go.sum
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/go.sum
  metric/go.sum
  schema/go.mod
  schema/go.sum
  sdk/export/metric/go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/metric/go.mod
  sdk/metric/go.sum
  trace/go.mod
  trace/go.sum
Labels: dependencies, Skip Changelog

#2713 Use upstream dbotconf
  .github/dependabot.yml
  Makefile
  internal/tools/dbotconf/dbotconf.go
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: Skip Changelog

#2721 fix typo in changelog
  CHANGELOG.md
Labels: documentation

#2719 Apply fix from #2674 to all applicable lines
  exporters/otlp/otlpmetric/internal/otlpconfig/options_test.go
Labels: Skip Changelog

#2726 fix(doc): Link to the Go otel package
  README.md
Labels: documentation, Skip Changelog

#2727 Document Resource options that potentially leak secrets
  sdk/resource/config.go
Labels: documentation, Skip Changelog

#2751 Remove removed module from dependabot conf
  .github/dependabot.yml
Labels: Skip Changelog

#2750 Add back global metric Meter function
  CHANGELOG.md
  metric/global/global.go
Labels: area:metrics

#2754 run ResetForTest during cleanup
  internal/global/benchmark_test.go
  internal/global/propagator_test.go
  internal/global/state.go
  internal/global/state_test.go
  internal/global/trace_test.go
Labels: Skip Changelog
