Repository open-telemetry/opentelemetry-go, pull requests merged in 2022-12, with the labels that each got.

#3495 change jaeger tag version in otel-collector
  example/otel-collector/Makefile
Labels: pkg:example, Skip Changelog

#3509 Fix a typo in the manual reader
  sdk/metric/manual_reader.go
Labels: Skip Changelog

#3521 Fix changelog header
  CHANGELOG.md
Labels: documentation

#3522 Allow multi-instrument callbacks to be unregistered
  CHANGELOG.md
  example/prometheus/main.go
  metric/example_test.go
  metric/internal/global/meter.go
  metric/internal/global/meter_test.go
  metric/internal/global/meter_types_test.go
  metric/meter.go
  metric/noop.go
  sdk/metric/meter.go
  sdk/metric/meter_test.go
  sdk/metric/pipeline.go
Labels: pkg:API, pkg:SDK, area:metrics

#3541 Update OpenCensus metric bridge to use the metric.Producer interface
  CHANGELOG.md
  bridge/opencensus/metric.go
  bridge/opencensus/metric_test.go
  example/opencensus/main.go
Labels: pkg:bridges

#3553 Fix ParentBased comment formatting
  sdk/trace/sampling.go
Labels: documentation, Skip Changelog
