Repository open-telemetry/opentelemetry-go, pull requests merged in 2023-09, with the labels that each got.

#4396 Document public metric SDK interfaces to remain stable
  sdk/metric/exporter.go
  sdk/metric/reader.go
Labels: documentation, pkg:SDK, area:metrics, Skip Changelog

#4466 Collector example: add metrics and use official port
  example/otel-collector/go.mod
  example/otel-collector/main.go
Labels: Skip Changelog

#4487 Revert "Collector example: add metrics and use official port (#4466)"
  example/otel-collector/go.mod
  example/otel-collector/main.go
Labels: Skip Changelog

#4504 Add metrics examples
  exporters/otlp/otlptrace/otlptracehttp/example_test.go
  exporters/stdout/stdoutmetric/example_test.go
  exporters/stdout/stdouttrace/example_test.go
  metric/example_test.go
  sdk/metric/doc.go
  sdk/metric/example_test.go
  sdk/metric/view_test.go
Labels: Skip Changelog

#4517 otlptracegrpc: Check error on Shutdown in tests
  exporters/otlp/otlptrace/otlptracegrpc/client_test.go
Labels: Skip Changelog

#4518 Add Base2ExponentialHistogram example
  sdk/metric/aggregation.go
  sdk/metric/example_test.go
Labels: documentation, pkg:SDK, area:metrics, Skip Changelog

#4527 Add ExampleNewView_attributeFilter and refine ExampleNewView_drop
  sdk/metric/example_test.go
Labels: Skip Changelog

#4529 sdk/metric: Fix comment in ExampleNewView_attributeFilter
  sdk/metric/example_test.go
Labels: documentation, Skip Changelog

#4535 Upgrade gopkg.io/yaml from v2 to v3 in schema
  schema/go.mod
  schema/go.sum
  schema/v1.0/parser.go
  schema/v1.0/parser_test.go
  schema/v1.0/testdata/unknown-field.yaml
  schema/v1.1/parser.go
Labels: Skip Changelog

#4542 Update codeql analysis frequency
  .github/workflows/codeql-analysis.yml
Labels: Skip Changelog

#4540 sdk/metric: Update package example
  sdk/metric/example_test.go
Labels: Skip Changelog

#4544 stdouttrace: Fix WithPrettyPrint comment
  exporters/stdout/stdouttrace/config.go
Labels: Skip Changelog

#4553 Fix typos in comments
  exporters/prometheus/config_test.go
  sdk/metric/reader.go
Labels: Skip Changelog

#4507 stdoutmetric: Add WithWriter and WithPrettyPrint options
  CHANGELOG.md
  exporters/stdout/stdoutmetric/config.go
  exporters/stdout/stdoutmetric/exporter_test.go
Labels: pkg:exporter:stdout

#4561 Opencensus bridge: migrate from README to Go docs
  bridge/opencensus/README.md
  bridge/opencensus/doc.go
  bridge/opencensus/example_test.go
  bridge/opencensus/trace.go
Labels: Skip Changelog

#4569 [chore] Update project status
  .gitignore
  README.md
Labels: Skip Changelog
