Repository open-telemetry/opentelemetry-go, pull requests merged in 2023-04, with the labels that each got.

#3942 TracerProvider cleanups
  sdk/trace/provider.go
  sdk/trace/provider_test.go
  sdk/trace/span.go
  sdk/trace/span_processor.go
  sdk/trace/tracer.go
Labels: Skip Changelog

#3916 Add embedded private method interfaces in metric API
  .golangci.yml
  CHANGELOG.md
  internal/global/instruments.go
  internal/global/instruments_test.go
  internal/global/meter.go
  internal/global/meter_types_test.go
  metric/doc.go
  metric/embedded/embedded.go
  metric/instrument/asyncfloat64.go
  metric/instrument/asyncfloat64_test.go
  metric/instrument/asyncint64.go
  metric/instrument/asyncint64_test.go
  metric/instrument/syncfloat64.go
  metric/instrument/syncint64.go
  metric/meter.go
  metric/noop/noop.go
  metric_test.go
  sdk/metric/instrument.go
  sdk/metric/internal/aggregator_example_test.go
  sdk/metric/meter.go
  sdk/metric/pipeline.go
  sdk/metric/provider.go
Labels: pkg:API, area:metrics

#3957 Guard zero value Set methods
  attribute/set.go
  attribute/set_test.go
Labels: bug, Skip Changelog, pkg:attribute

#3975 Add go.work.sum to .gitignore file
  .gitignore
Labels: Skip Changelog

#3982 Fix embedded documentation links
  metric/embedded/embedded.go
Labels: documentation, Skip Changelog

#3980 docs(typos): Run codespell to fix typos
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  bridge/opencensus/internal/oc2otel/span_context_test.go
  bridge/opencensus/internal/otel2oc/span_context_test.go
  bridge/opencensus/internal/span.go
  bridge/opencensus/test/bridge_test.go
  bridge/opentracing/util.go
  exporters/jaeger/internal/third_party/thrift/lib/go/thrift/exception.go
  exporters/jaeger/internal/third_party/thrift/lib/go/thrift/transport.go
  exporters/jaeger/internal/third_party/thrift/lib/go/thrift/type.go
  exporters/jaeger/reconnecting_udp_client_test.go
  exporters/otlp/otlpmetric/internal/otest/collector.go
  exporters/prometheus/exporter_test.go
  exporters/stdout/stdouttrace/trace.go
  metric/meter.go
  propagation/trace_context_test.go
  sdk/metric/benchmark_test.go
  sdk/metric/cache.go
  sdk/metric/instrument.go
  sdk/metric/internal/aggregator_test.go
  sdk/metric/meter_test.go
  sdk/metric/metricdata/metricdatatest/comparisons.go
  sdk/metric/reader_test.go
  sdk/trace/batch_span_processor.go
  sdk/trace/span.go
  sdk/trace/span_exporter.go
  sdk/trace/trace_test.go
  trace/config_test.go
  trace/noop.go
Labels: Skip Changelog

#3986 Move global metric back to `otel/metric/global` for minor release
  CHANGELOG.md
  bridge/opentracing/go.mod
  bridge/opentracing/test/go.mod
  example/fib/go.mod
  example/jaeger/go.mod
  example/namedtracer/go.mod
  example/otel-collector/go.mod
  example/passthrough/go.mod
  example/zipkin/go.mod
  exporters/jaeger/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/example_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/example_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  internal/global/state.go
  internal/global/state_test.go
  internal/global/util_test.go
  metric/example_test.go
  metric/global/metric.go
  metric/global/metric_test.go
  metric/internal/global/instruments.go
  metric/internal/global/instruments_test.go
  metric/internal/global/meter.go
  metric/internal/global/meter_test.go
  metric/internal/global/meter_types_test.go
  metric/internal/global/state.go
  metric/internal/global/state_test.go
  sdk/go.mod
  sdk/metric/example_test.go
  sdk/metric/meter_test.go
  trace/go.mod
Labels: pkg:API, area:metrics

#3994 Fix Version test in otel/sdk
  sdk/version_test.go
Labels: Skip Changelog

#3992 Refine the metric SDK benchmarks
  sdk/metric/benchmark_test.go
Labels: Skip Changelog

#3971 Add options to measurement methods
  CHANGELOG.md
  example/prometheus/main.go
  example/view/main.go
  exporters/prometheus/exporter_test.go
  metric/example_test.go
  metric/instrument/asyncfloat64.go
  metric/instrument/asyncfloat64_test.go
  metric/instrument/asyncint64.go
  metric/instrument/asyncint64_test.go
  metric/instrument/instrument.go
  metric/instrument/instrument_test.go
  metric/instrument/syncfloat64.go
  metric/instrument/syncint64.go
  metric/internal/global/instruments.go
  metric/internal/global/instruments_test.go
  metric/internal/global/meter_types_test.go
  metric/meter.go
  metric/noop/noop.go
  sdk/metric/benchmark_test.go
  sdk/metric/instrument.go
  sdk/metric/instrument_test.go
  sdk/metric/internal/aggregator_example_test.go
  sdk/metric/meter.go
  sdk/metric/meter_test.go
Labels: pkg:API, area:metrics

#4024 move jmacd to emeritus
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#4019 Remove the histogram from metric API async example
  metric/example_test.go
Labels: pkg:API, area:metrics, Skip Changelog

#4034 Fix broken link
  exporters/jaeger/README.md
Labels: Skip Changelog

#4018 Unify metric API into the one `otel/metric` package
  CHANGELOG.md
  example/prometheus/main.go
  example/view/main.go
  exporters/prometheus/exporter_test.go
  metric/asyncfloat64.go
  metric/asyncfloat64_test.go
  metric/asyncint64.go
  metric/asyncint64_test.go
  metric/doc.go
  metric/embedded/embedded.go
  metric/example_test.go
  metric/instrument.go
  metric/instrument/deprecation.go
  metric/instrument/doc.go
  metric/instrument_test.go
  metric/internal/global/instruments.go
  metric/internal/global/instruments_test.go
  metric/internal/global/meter.go
  metric/internal/global/meter_test.go
  metric/internal/global/meter_types_test.go
  metric/meter.go
  metric/noop/noop.go
  metric/noop/noop_test.go
  metric/syncfloat64.go
  metric/syncfloat64_test.go
  metric/syncint64.go
  metric/syncint64_test.go
  sdk/metric/benchmark_test.go
  sdk/metric/instrument.go
  sdk/metric/internal/aggregator_example_test.go
  sdk/metric/meter.go
  sdk/metric/meter_test.go
Labels: pkg:API, area:metrics, proposal

#4015 Move readFile and execCommand to seperate files
  sdk/resource/host_id.go
  sdk/resource/host_id_exec.go
  sdk/resource/host_id_readfile.go
Labels: Skip Changelog
