Repository open-telemetry/opentelemetry-go, pull requests merged in 2023-02, with the labels that each got.

#3635 Add a benchmark for histogram allocations
  sdk/metric/benchmark_test.go
Labels: Skip Changelog

#3638 [docs] Use new canonical path to OTel registry in libraries.md
  website_docs/libraries.md
Labels: documentation, Skip Changelog

#3684 Update dependabot config
  .github/dependabot.yml
Labels: Skip Changelog

#3683 Use semconv creation functions
  bridge/opentracing/internal/mock.go
  example/fib/main.go
  example/jaeger/main.go
  example/otel-collector/main.go
  example/zipkin/main.go
  exporters/jaeger/jaeger.go
  exporters/jaeger/jaeger_test.go
  exporters/otlp/otlpmetric/internal/transform/metricdata_test.go
  exporters/otlp/otlptrace/otlptracehttp/example_test.go
  exporters/prometheus/exporter_test.go
  exporters/stdout/stdoutmetric/example_test.go
  exporters/stdout/stdouttrace/example_test.go
  exporters/zipkin/model_test.go
  exporters/zipkin/zipkin_test.go
  sdk/metric/example_test.go
  sdk/resource/builtin.go
  sdk/resource/container.go
  sdk/resource/env.go
  sdk/resource/env_test.go
  sdk/resource/os.go
  sdk/resource/process.go
  sdk/resource/resource_test.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  website_docs/getting-started.md
  website_docs/manual.md
Labels: Skip Changelog

#3694 Bump default Go version to 1.19
  .github/workflows/ci.yml
Labels: pkg:tooling, Skip Changelog

#3639 WithContainerID: Document ECS limitation.
  sdk/resource/config.go
Labels: documentation, Skip Changelog

#3721 Update dmathieu's affiliation
  CONTRIBUTING.md
Labels: Skip Changelog

#3695 No memory leakage in attributes filter
  sdk/metric/internal/filter.go
Labels: bug, Skip Changelog

#3734 Rename instrumentationName param of Meter method
  metric/meter.go
Labels: pkg:API, documentation, area:metrics, Skip Changelog

#3735 Rename instrumentID to streamID in metric SDK
  sdk/metric/cache.go
  sdk/metric/instrument.go
  sdk/metric/meter.go
  sdk/metric/pipeline.go
  sdk/metric/pipeline_registry_test.go
Labels: pkg:SDK, area:metrics, Skip Changelog

#3736 Remove leftover instrument provider from noop
  metric/noop.go
Labels: pkg:API, area:metrics, Skip Changelog

#3738 Accept scope attributes during Meter creation
  CHANGELOG.md
  metric/config.go
  metric/config_test.go
Labels: pkg:API, area:metrics

#3754 Add "[chore]" PR prefix to skip changelog check
  .github/workflows/changelog.yml
  .github/workflows/scripts/dependabot-pr.sh
Labels: Skip Changelog

#3724 Merge instrument cache to inserter
  CHANGELOG.md
  sdk/metric/cache.go
  sdk/metric/meter.go
  sdk/metric/pipeline.go
  sdk/metric/pipeline_registry_test.go
  sdk/metric/pipeline_test.go
Labels: bug, pkg:SDK, area:metrics

#3585 Restructure Website documentation
  website_docs/exporters.md
  website_docs/exporting_data.md
  website_docs/getting-started.md
  website_docs/libraries.md
  website_docs/resources.md
  website_docs/sampling.md
Labels: Skip Changelog

#3758 [website_docs] Fix link to Go logo
  website_docs/_index.md
Labels: Skip Changelog

#3739 Accept scope attributes during Tracer creation
  CHANGELOG.md
  trace/config.go
  trace/config_test.go
Labels: pkg:API, area:trace

#3570 Implement IsSampled for OpenTelemetry bridgeSpanContext
  CHANGELOG.md
  bridge/opentracing/README.md
  bridge/opentracing/bridge.go
  bridge/opentracing/bridge_test.go
  bridge/opentracing/internal/mock.go
Labels: pkg:bridges

#3762 Run website formatter over website_docs
  .lycheeignore
  website_docs/_index.md
  website_docs/exporters.md
  website_docs/getting-started.md
  website_docs/libraries.md
  website_docs/manual.md
  website_docs/resources.md
Labels: Skip Changelog

#3763 Support OTEL_METRIC_EXPORT_INTERVAL and OTEL_METRIC_EXPORT_TIMEOUT
  CHANGELOG.md
  sdk/metric/env.go
  sdk/metric/periodic_reader.go
  sdk/metric/periodic_reader_test.go
  sdk/metric/reader.go
Labels: pkg:SDK, area:metrics

#3774 Fix `global.MeterProvider` documentation
  metric/global/global.go
Labels: documentation, Skip Changelog

#3776 Deprecate `metric/unit` and use a `string` for units in the metric API/SDK
  CHANGELOG.md
  bridge/opencensus/go.mod
  bridge/opencensus/internal/ocmetric/metric.go
  bridge/opencensus/internal/ocmetric/metric_test.go
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/internal/otest/client.go
  exporters/otlp/otlpmetric/internal/transform/metricdata_test.go
  exporters/prometheus/exporter.go
  exporters/prometheus/exporter_test.go
  exporters/stdout/stdoutmetric/example_test.go
  exporters/stdout/stdoutmetric/go.mod
  metric/example_test.go
  metric/instrument/asyncfloat64.go
  metric/instrument/asyncfloat64_test.go
  metric/instrument/asyncint64.go
  metric/instrument/asyncint64_test.go
  metric/instrument/instrument.go
  metric/instrument/syncfloat64.go
  metric/instrument/syncfloat64_test.go
  metric/instrument/syncint64.go
  metric/instrument/syncint64_test.go
  metric/unit/doc.go
  metric/unit/unit.go
  sdk/metric/instrument.go
  sdk/metric/meter.go
  sdk/metric/metricdata/data.go
  sdk/metric/metricdata/metricdatatest/assertion_test.go
  sdk/metric/pipeline.go
  sdk/metric/pipeline_test.go
  sdk/metric/reader_test.go
  sdk/metric/view_test.go
Labels: pkg:API, pkg:SDK, area:metrics

#3779 Restructure compatibility testing
  .github/workflows/ci.yml
Labels: Skip Changelog

#3807 [docs] fix link to traces concept page
  website_docs/exporters.md
Labels: documentation, Skip Changelog
