Repository open-telemetry/opentelemetry-go, pull requests merged in 2023-03, with the labels that each got.

#3843 Update metrics project status to beta
  README.md
Labels: documentation, Skip Changelog

#3844 Wrap errors returned from `Detect` and `New` in `sdk/resource`
  CHANGELOG.md
  sdk/resource/auto.go
  sdk/resource/resource.go
  sdk/resource/resource_test.go
Labels: enhancement, area:resources

#3760 Reuse memory in metric pipelines
  sdk/metric/internal/reuse_slice.go
  sdk/metric/manual_reader.go
  sdk/metric/periodic_reader.go
  sdk/metric/pipeline.go
  sdk/metric/pipeline_test.go
  sdk/metric/reader.go
  sdk/metric/reader_test.go
Labels: pkg:SDK, area:metrics, Skip Changelog

#3849 Add `Exemplar` to metricdata package
  CHANGELOG.md
  bridge/opencensus/internal/ocmetric/metric.go
  bridge/opencensus/internal/ocmetric/metric_test.go
  exporters/otlp/otlpmetric/internal/transform/metricdata.go
  exporters/otlp/otlpmetric/internal/transform/metricdata_test.go
  exporters/prometheus/exporter.go
  exporters/stdout/stdoutmetric/example_test.go
  exporters/stdout/stdoutmetric/exporter.go
  sdk/metric/internal/histogram.go
  sdk/metric/internal/histogram_test.go
  sdk/metric/meter_test.go
  sdk/metric/metricdata/data.go
  sdk/metric/metricdata/metricdatatest/assertion.go
  sdk/metric/metricdata/metricdatatest/assertion_fail_test.go
  sdk/metric/metricdata/metricdatatest/assertion_test.go
  sdk/metric/metricdata/metricdatatest/comparisons.go
Labels: pkg:SDK, area:metrics

#3869 Update SIG meeting notes URL
  CONTRIBUTING.md
Labels: documentation, Skip Changelog

#3850 Update go directive value in go.mod files to 1.19
  Makefile
  bridge/opencensus/go.mod
  bridge/opencensus/metric.go
  bridge/opencensus/test/go.mod
  bridge/opentracing/go.mod
  bridge/opentracing/test/go.mod
  example/fib/go.mod
  example/jaeger/go.mod
  example/namedtracer/go.mod
  example/opencensus/go.mod
  example/otel-collector/go.mod
  example/passthrough/go.mod
  example/prometheus/go.mod
  example/view/go.mod
  example/zipkin/go.mod
  exporters/jaeger/go.mod
  exporters/otlp/internal/retry/go.mod
  exporters/otlp/otlpmetric/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/prometheus/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  internal/tools/go.mod
  metric/go.mod
  schema/go.mod
  sdk/go.mod
  sdk/metric/go.mod
  trace/go.mod
Labels: Skip Changelog

#3868 Update "How to Get PRs Merged" section of CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Skip Changelog

#3892 Remove Synchronous and rename Asynchronous
  CHANGELOG.md
  internal/global/instruments.go
  internal/global/instruments_test.go
  internal/global/meter.go
  internal/global/meter_types_test.go
  metric/instrument/asyncfloat64.go
  metric/instrument/asyncfloat64_test.go
  metric/instrument/asyncint64.go
  metric/instrument/asyncint64_test.go
  metric/instrument/instrument.go
  metric/instrument/syncfloat64.go
  metric/instrument/syncint64.go
  metric/meter.go
  metric/noop.go
  sdk/metric/instrument.go
  sdk/metric/internal/aggregator_example_test.go
  sdk/metric/meter.go
  sdk/metric/meter_test.go
  sdk/metric/pipeline.go
Labels: pkg:API, area:metrics

#3896 Update metric API documentation
  metric/doc.go
  metric/instrument/doc.go
  metric/meter.go
Labels: pkg:API, documentation, area:metrics, Skip Changelog

#3705 [doc] replace ` jaeger exporter` with `otlp http exporter`
  website_docs/exporters.md
Labels: Skip Changelog

#3893 Move metric No-Op to `metric/noop`
  CHANGELOG.md
  internal/global/instruments_test.go
  internal/global/meter_test.go
  internal/global/state_test.go
  metric/noop.go
  metric/noop/example_test.go
  metric/noop/noop.go
  metric/noop/noop_test.go
  metric/noop_test.go
  metric_test.go
Labels: pkg:API, area:metrics

#3921 Revert "Move metric No-Op to metric/noop (#3893)"
  CHANGELOG.md
  internal/global/instruments_test.go
  internal/global/meter_test.go
  internal/global/state_test.go
  metric/example_test.go
  metric/noop.go
  metric/noop/noop.go
  metric/noop/noop_test.go
  metric/noop_test.go
  metric_test.go
Labels: pkg:API, area:metrics

#3929 Fix benchmark action
  .github/workflows/benchmark.yml
Labels: Skip Changelog

#3927 metric: Refactor examples to use otel.Meter
  metric/example_test.go
  metric/go.mod
  metric/go.sum
Labels: pkg:API, documentation, area:metrics, Skip Changelog

#3931 Typo in getting-started.md
  website_docs/getting-started.md
Labels: documentation, Skip Changelog

#3926 Switch atomic.Value to atomic.Pointer for spanProcessorStates
  sdk/trace/provider.go
  sdk/trace/provider_test.go
  sdk/trace/span.go
  sdk/trace/tracer.go
Labels: Skip Changelog

#3941 Move metric No-Op to `metric/noop`
  CHANGELOG.md
  internal/global/instruments_test.go
  internal/global/meter_test.go
  internal/global/state_test.go
  metric/noop.go
  metric/noop/noop.go
  metric/noop/noop_test.go
  metric/noop_test.go
  metric_test.go
Labels: pkg:API, area:metrics

#3870 Update Histogram Extrema and Sum to be generic
  CHANGELOG.md
  exporters/otlp/otlpmetric/internal/transform/metricdata.go
  exporters/otlp/otlpmetric/internal/transform/metricdata_test.go
  exporters/prometheus/exporter.go
  sdk/metric/internal/aggregator_test.go
  sdk/metric/internal/histogram.go
  sdk/metric/internal/histogram_test.go
  sdk/metric/internal/lastvalue_test.go
  sdk/metric/internal/sum_test.go
  sdk/metric/meter_test.go
  sdk/metric/metricdata/data.go
  sdk/metric/metricdata/metricdatatest/assertion.go
  sdk/metric/metricdata/metricdatatest/assertion_test.go
  sdk/metric/metricdata/metricdatatest/comparisons.go
Labels: pkg:SDK, area:metrics
