Repository open-telemetry/opentelemetry-go, pull requests merged in 2023-10, with the labels that each got.

#4574 Replace otlptracehttp example to use otlptracehttp instead of otlptrace
  exporters/otlp/otlptrace/otlptracehttp/example_test.go
Labels: Skip Changelog

#4583 opencensus.NewMetricProducer returns a struct instead of the metric.Producer interface
  CHANGELOG.md
  bridge/opencensus/metric.go
Labels: enhancement, pkg:bridges

#4598 enh: add golvulncheck in linting job
  Makefile
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: Skip Changelog

#4602 Fix WithoutCounterSuffixes documentation
  exporters/prometheus/config.go
Labels: Skip Changelog

#4584 Add scope version to opencensus trace and metric bridges
  CHANGELOG.md
  bridge/opencensus/metric.go
  bridge/opencensus/metric_test.go
  bridge/opencensus/trace.go
  bridge/opencensus/trace_test.go
  bridge/opencensus/version.go
Labels: enhancement, pkg:bridges

#4599 Migrate opencensus bridge to errors.Join
  bridge/opencensus/internal/ocmetric/metric.go
  bridge/opencensus/internal/ocmetric/metric_test.go
Labels: enhancement, pkg:bridges, Skip Changelog

#4607 Update go version to v1.21.3/1.20.10 for CI
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/create-dependabot-pr.yml
  .github/workflows/dependabot.yml
Labels: Skip Changelog

#4604 sdk/trace: Fix ParentBased comment
  sdk/trace/sampling.go
Labels: Skip Changelog

#4620 Add embedded package to trace API
  CHANGELOG.md
  bridge/opencensus/config_test.go
  bridge/opencensus/internal/tracer_test.go
  bridge/opentracing/bridge.go
  bridge/opentracing/internal/mock.go
  bridge/opentracing/provider.go
  bridge/opentracing/provider_test.go
  bridge/opentracing/wrapper.go
  internal/global/state_test.go
  internal/global/trace.go
  internal/global/trace_test.go
  sdk/trace/provider.go
  sdk/trace/span.go
  sdk/trace/tracer.go
  trace/doc.go
  trace/embedded/embedded.go
  trace/noop.go
  trace/noop/noop.go
  trace/noop/noop_test.go
  trace/trace.go
  trace_test.go
Labels: pkg:API, area:trace

#4648 Prometheus exporter no longer collects metrics after shutdown
  CHANGELOG.md
  exporters/prometheus/exporter.go
  exporters/prometheus/exporter_test.go
Labels: bug, pkg:exporter:prometheus

#4622 Add summary data type to metricdata
  CHANGELOG.md
  sdk/metric/metricdata/data.go
  sdk/metric/metricdata/metricdatatest/assertion.go
  sdk/metric/metricdata/metricdatatest/assertion_test.go
  sdk/metric/metricdata/metricdatatest/comparisons.go
Labels: enhancement, area:metrics

#4603 Add WithExplicitBucketBoundaries Histogram option to the metric api
  CHANGELOG.md
  metric/example_test.go
  metric/instrument.go
  metric/syncfloat64.go
  metric/syncfloat64_test.go
  metric/syncint64.go
  metric/syncint64_test.go
Labels: enhancement, pkg:API, area:metrics

#4585 Add exemplar support to OpenCensus bridge
  CHANGELOG.md
  bridge/opencensus/doc.go
  bridge/opencensus/internal/ocmetric/metric.go
  bridge/opencensus/internal/ocmetric/metric_test.go
Labels: enhancement, pkg:bridges

#4605 Implement WithExplicitBucketBoundaries option in the metric SDK
  CHANGELOG.md
  sdk/metric/meter.go
  sdk/metric/meter_test.go
  sdk/metric/pipeline.go
  sdk/metric/pipeline_registry_test.go
  sdk/metric/pipeline_test.go
Labels: enhancement, pkg:SDK, area:metrics

#4664 Reduce regexp memory use in tracestate
  trace/tracestate.go
  trace/tracestate_test.go
Labels: Skip Changelog
