Repository open-telemetry/opentelemetry-go, pull requests merged in 2023-06, with the labels that each got.

#4152 sdk/metrics: Fix MeterProvider.Meter Go doc
  sdk/metric/provider.go
Labels: documentation, pkg:SDK, area:metrics, Skip Changelog

#4153 sdk/metric: Log empty meter name
  sdk/metric/provider.go
  sdk/metric/provider_test.go
Labels: pkg:SDK, area:metrics, Skip Changelog

#4154 Return noop meters once the provider has been shutdown
  CHANGELOG.md
  sdk/metric/provider.go
  sdk/metric/provider_test.go
Labels: pkg:SDK, area:metrics

#4202 Warn instead of Info log instrument conflict
  CHANGELOG.md
  sdk/metric/pipeline.go
Labels: pkg:SDK, area:metrics

#4226 Replace uses unsafe with atomic with the generic atomic.Pointer
  internal/global/handler.go
  internal/global/internal_logging.go
Labels: Skip Changelog

#4219 Drop website_docs since it has moved to OTel website
  RELEASING.md
  website_docs/_index.md
  website_docs/api.md
  website_docs/examples.md
  website_docs/exporters.md
  website_docs/getting-started.md
  website_docs/libraries.md
  website_docs/manual.md
  website_docs/resources.md
  website_docs/sampling.md
Labels: Skip Changelog

#3968 Add decision about v2 API
  CONTRIBUTING.md
Labels: Skip Changelog

#4242 Fix Go doc comments in internal transform package
  exporters/otlp/otlpmetric/internal/transform/metricdata.go
Labels: Skip Changelog

#4244 sdk/metric: Reader factories return structs
  CHANGELOG.md
  sdk/metric/manual_reader.go
  sdk/metric/periodic_reader.go
Labels: pkg:SDK, area:metrics

#4252 sdk/metric: Document reader and exporter concurrent safety
  sdk/metric/exporter.go
  sdk/metric/manual_reader.go
  sdk/metric/periodic_reader.go
  sdk/metric/reader.go
Labels: documentation, pkg:SDK, area:metrics, Skip Changelog

#4221 Count the Collect duration towards the PeriodicReader timeout, and document the behavior
  CHANGELOG.md
  sdk/metric/periodic_reader.go
Labels: pkg:SDK, area:metrics

#4256 Update OTel Demo during release
  RELEASING.md
Labels: Skip Changelog

#4251 Document f in RegisterCallback needs to be concurrent safe
  metric/meter.go
Labels: Skip Changelog

#4267 Document and test honoring context in metric readers Collect
  sdk/metric/manual_reader.go
  sdk/metric/manual_reader_test.go
  sdk/metric/periodic_reader.go
  sdk/metric/periodic_reader_test.go
  sdk/metric/reader.go
Labels: Skip Changelog

#4273 Fix dependabot-check and vanity-import-check targets
  .github/dependabot.yml
  Makefile
Labels: Skip Changelog
