Repository open-telemetry/opentelemetry-go, pull requests merged in 2023-05, with the labels that each got.

#4038 Revert "Move the metric API back to experimental-metrics (#3987)"
  CHANGELOG.md
  versions.yaml
Labels: pkg:API, area:metrics

#4039 Revert "Move global metric back to otel/metric/global for minor release (#3986)"
  CHANGELOG.md
  bridge/opentracing/go.mod
  bridge/opentracing/test/go.mod
  example/fib/go.mod
  example/jaeger/go.mod
  example/namedtracer/go.mod
  example/otel-collector/go.mod
  example/passthrough/go.mod
  example/zipkin/go.mod
  exporters/jaeger/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/example_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/example_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  internal/global/instruments.go
  internal/global/instruments_test.go
  internal/global/meter.go
  internal/global/meter_test.go
  internal/global/meter_types_test.go
  internal/global/state.go
  internal/global/state_test.go
  internal/global/util_test.go
  metric.go
  metric/example_test.go
  metric/internal/global/state.go
  metric/internal/global/state_test.go
  metric_test.go
  sdk/go.mod
  sdk/metric/example_test.go
  sdk/metric/meter_test.go
  trace/go.mod
Labels: pkg:API, area:metrics

#4055 Remove the deprecated `metric/instrument` package
  CHANGELOG.md
  metric/instrument/deprecation.go
Labels: pkg:API, area:metrics

#4056 Update metric interface warnings
  metric/asyncfloat64.go
  metric/asyncint64.go
  metric/syncfloat64.go
  metric/syncint64.go
Labels: documentation, area:metrics, Skip Changelog

#4059 Add comment on all uses of embedded types
  metric/asyncfloat64.go
  metric/asyncint64.go
  metric/meter.go
  metric/syncfloat64.go
  metric/syncint64.go
Labels: documentation, area:metrics, Skip Changelog

#4057 Fix the broken [Option] link in metric docs
  metric/asyncfloat64.go
  metric/asyncint64.go
  metric/syncfloat64.go
  metric/syncint64.go
Labels: documentation, area:metrics, Skip Changelog

#4054 Fix article in metric API docs
  metric/instrument.go
Labels: documentation, area:metrics, Skip Changelog

#4058 Document how to pass attributes for all record methods
  metric/asyncfloat64.go
  metric/asyncint64.go
  metric/syncfloat64.go
  metric/syncint64.go
Labels: pkg:API, documentation, area:metrics, Skip Changelog

#4074 feat(gh-workflows): Use cache-dependency-path in actions/setup-go for CI workflow
  .github/workflows/ci.yml
Labels: Skip Changelog

#4053 Add measurement docs to metric API
  metric/doc.go
  metric/meter.go
Labels: documentation, area:metrics, Skip Changelog

#4080 sdk/resource: Add Telemetry Stability label
  sdk/resource/doc.go
Labels: Skip Changelog

#4084 [website_docs] Update path to spec, run formatter
  CONTRIBUTING.md
  website_docs/exporters.md
  website_docs/getting-started.md
  website_docs/libraries.md
  website_docs/manual.md
Labels: documentation, Skip Changelog

#4043 [SDK][Trace] Add tests for default id generator
  sdk/trace/id_generator_test.go
Labels: Skip Changelog

#3996 feat(ci): Add codespell to Makefile and GitHub Actions
  .codespellignore
  .codespellrc
  .github/workflows/codespell.yaml
  .gitignore
  .golangci.yml
  CONTRIBUTING.md
  Makefile
  requirements.txt
Labels: Skip Changelog

#4086 sdk/metric: Fix import comments
  sdk/metric/manual_reader_test.go
  sdk/metric/reader_test.go
Labels: Skip Changelog

#4129 Marked Metrics as stable
  README.md
Labels: documentation, Skip Changelog

#4138 Add @pellared as maintainer
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#4137 Move @Aneurysm9 to approver
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#4140 [chore] Clarify that internal and test packages do not need docs
  CONTRIBUTING.md
Labels: documentation
