Repository open-telemetry/opentelemetry-go, pull requests merged in 2024-11, with the labels that each got.

#5940 docs: updating outdated comments
  sdk/resource/builtin.go
Labels: Skip Changelog

#5937 prometheus: Refactor getAttrs
  exporters/prometheus/exporter.go
Labels: Skip Changelog

#5942 log: Update package documentation
  log/DESIGN.md
  log/doc.go
  log/logger.go
Labels: pkg:API, documentation, Skip Changelog

#5900 Fix incorrect metrics getting generated from multiple readers
  CHANGELOG.md
  sdk/metric/meter.go
  sdk/metric/pipeline.go
  sdk/metric/pipeline_test.go
Labels: bug, pkg:SDK, area:metrics

#5960 Release v1.32.0/v0.54.0/v0.8.0/v0.0.11
  CHANGELOG.md
  bridge/opencensus/go.mod
  bridge/opencensus/test/go.mod
  bridge/opencensus/version.go
  bridge/opentracing/go.mod
  bridge/opentracing/test/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/version.go
  exporters/otlp/otlplog/otlploghttp/go.mod
  exporters/otlp/otlplog/otlploghttp/version.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/version.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/version.go
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/version.go
  exporters/prometheus/go.mod
  exporters/stdout/stdoutlog/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  log/go.mod
  metric/go.mod
  sdk/go.mod
  sdk/log/go.mod
  sdk/metric/go.mod
  sdk/metric/version.go
  sdk/version.go
  trace/go.mod
  version.go
  versions.yaml
Labels: Unlock Released Changelog

#5967 Fix lint issues for golangci-lint 1.62.0
  attribute/key_test.go
  baggage/baggage.go
  baggage/baggage_test.go
  bridge/opentracing/mix_test.go
  exporters/otlp/otlplog/otlploghttp/client_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/otest/client.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/otest/collector.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/otest/client.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/otest/collector.go
  internal/shared/otlp/otlpmetric/otest/client.go.tmpl
  internal/shared/otlp/otlpmetric/otest/collector.go.tmpl
  metric/example_test.go
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/histogram_test.go
  sdk/resource/resource_test.go
Labels: Skip Changelog

#5983 Add toolchain check
  .github/workflows/ci.yml
  Makefile
Labels: Skip Changelog

#5984 [chore] Fix VERSIONING.md missing parenthesis
  VERSIONING.md
Labels: documentation

#5995 Escape exemplar keys to fix invalid key errors
  CHANGELOG.md
  exporters/prometheus/exporter.go
  exporters/prometheus/exporter_test.go
Labels: bug, pkg:exporter:prometheus
