Repository open-telemetry/opentelemetry-go, pull requests merged in 2024-10, with the labels that each got.

#5856 Move @MadVikingGod to Emeritus status
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#5862 Rename SampledFilter to TraceBasedFilter
  CHANGELOG.md
  sdk/metric/exemplar.go
  sdk/metric/exemplar/filter.go
  sdk/metric/exemplar/filter_test.go
Labels: area:metrics

#5865 Authenticate link checking requests
  .github/workflows/links-fail-fast.yml
  .github/workflows/links.yml
Labels: Skip Changelog

#5871 [doc] sdk/log: Do not create instances of Record
  sdk/log/record.go
Labels: documentation, pkg:SDK, area:logs, Skip Changelog

#5863 Move @hanyuancheung to Emeritus status
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#5883 Release v1.31.0/v0.53.0/v0.7.0/v0.0.10
  CHANGELOG.md
  bridge/opencensus/go.mod
  bridge/opencensus/test/go.mod
  bridge/opencensus/version.go
  bridge/opentracing/go.mod
  bridge/opentracing/test/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/version.go
  exporters/otlp/otlplog/otlploghttp/go.mod
  exporters/otlp/otlplog/otlploghttp/version.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/version.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/version.go
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/version.go
  exporters/prometheus/go.mod
  exporters/stdout/stdoutlog/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  log/go.mod
  metric/go.mod
  sdk/go.mod
  sdk/log/go.mod
  sdk/metric/go.mod
  sdk/metric/version.go
  sdk/version.go
  trace/go.mod
  version.go
  versions.yaml
Labels: Unlock Released Changelog

#5879 Run the test compatibility check even if tests failed
  .github/workflows/ci.yml
Labels: Skip Changelog

#5887 Remove company from emeritus
  CONTRIBUTING.md
Labels: Skip Changelog

#5881 otel: conceal unwrapping for global async instrument registration
  CHANGELOG.md
  internal/global/alternate_meter_test.go
  internal/global/instruments.go
  internal/global/instruments_test.go
  internal/global/meter.go
  sdk/metric/meter.go
Labels: pkg:API

#5894 Generate `semconv/v1.27.0`
  CHANGELOG.md
  Makefile
  semconv/capitalizations.txt
  semconv/v1.27.0/README.md
  semconv/v1.27.0/attribute_group.go
  semconv/v1.27.0/doc.go
  semconv/v1.27.0/exception.go
  semconv/v1.27.0/metric.go
  semconv/v1.27.0/schema.go
Labels: pkg:semconv

#5899 Cleanup interaction of exemplar and aggregation
  sdk/metric/exemplar.go
  sdk/metric/instrument_test.go
  sdk/metric/internal/aggregate/aggregate.go
  sdk/metric/internal/aggregate/aggregate_test.go
  sdk/metric/internal/aggregate/drop.go
  sdk/metric/internal/aggregate/drop_test.go
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/exponential_histogram_test.go
  sdk/metric/internal/aggregate/filtered_reservoir.go
  sdk/metric/internal/aggregate/histogram.go
  sdk/metric/internal/aggregate/histogram_test.go
  sdk/metric/internal/aggregate/lastvalue.go
  sdk/metric/internal/aggregate/lastvalue_test.go
  sdk/metric/internal/aggregate/sum.go
  sdk/metric/internal/aggregate/sum_test.go
  sdk/metric/pipeline.go
Labels: area:metrics, Skip Changelog

#5923 Switch arm builds out of actuated and into the CNCF runners
  .github/workflows/ci.yml
Labels: Skip Changelog

#5922 Add Cheng-Zhen as a triager
  CONTRIBUTING.md
Labels: Skip Changelog
