Repository open-telemetry/opentelemetry-go, pull requests merged in 2024-07, with the labels that each got.

#5543 sdk/log: Add filtering Processor example
  sdk/log/example_test.go
Labels: documentation, pkg:SDK, area:logs, Skip Changelog

#5545 Move time.Now call into exemplar reservoir to improve performance
  CHANGELOG.md
  sdk/metric/exemplar.go
  sdk/metric/internal/aggregate/aggregate.go
  sdk/metric/internal/aggregate/aggregate_test.go
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/exponential_histogram_test.go
  sdk/metric/internal/aggregate/histogram.go
  sdk/metric/internal/aggregate/histogram_test.go
  sdk/metric/internal/aggregate/lastvalue.go
  sdk/metric/internal/aggregate/lastvalue_test.go
  sdk/metric/internal/aggregate/sum.go
  sdk/metric/internal/aggregate/sum_test.go
  sdk/metric/internal/exemplar/drop.go
  sdk/metric/internal/exemplar/drop_test.go
  sdk/metric/internal/exemplar/filter.go
  sdk/metric/internal/exemplar/filter_test.go
  sdk/metric/internal/exemplar/filtered_reservoir.go
  sdk/metric/pipeline.go
Labels: enhancement, pkg:SDK

#5558 Add @XSAM and @dmathieu as repository maintainers
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#5570 Upgrade Go versions in CI
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
Labels: Skip Changelog

#5572 Implement otlploggrpc gRPC client
  exporters/otlp/otlplog/otlploggrpc/client.go
  exporters/otlp/otlplog/otlploggrpc/client_test.go
  exporters/otlp/otlplog/otlploggrpc/go.mod
Labels: Skip Changelog

#5527 Enable benchmark summary for release
  .github/workflows/benchmark.yml
Labels: Skip Changelog

#5579 sdk/log: Add package example
  sdk/log/example_test.go
Labels: documentation, pkg:SDK, area:logs, Skip Changelog

#5560 Protect released changelog in CI
  .github/workflows/protect-released-changelog.yml
  CHANGELOG.md
  RELEASING.md
  verify_released_changelog.sh
Labels: Skip Changelog, Unlock Released Changelog

#5591 Add TestSpanStartConfigAttributeMutability
  trace/config_test.go
Labels: Skip Changelog

#5598 log: Add missing notice to Bytes, Slice, Map doc comment
  log/keyvalue.go
Labels: pkg:API, documentation, pkg:SDK, Skip Changelog

#5607 sdk/log: Refine BenchmarkProcessor
  sdk/log/bench_test.go
Labels: pkg:SDK, area:logs, Skip Changelog

#5578 sdk/log: Simple processor may be useful for production
  exporters/otlp/otlplog/otlploggrpc/exporter.go
  exporters/otlp/otlplog/otlploghttp/exporter.go
  sdk/log/DESIGN.md
  sdk/log/simple.go
Labels: documentation, pkg:SDK, area:logs, Skip Changelog

#5616 Fix verify_released_changelog.sh
  verify_released_changelog.sh
Labels: Skip Changelog

#5602 Add resource metrics transform benchmarks
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/transform/metricdata_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/transform/metricdata_test.go
  internal/shared/otlp/otlpmetric/transform/metricdata_test.go.tmpl
Labels: Skip Changelog

#5601 Add benchmark for turning readonly spans into their proto struct
  exporters/otlp/otlptrace/internal/tracetransform/span_test.go
Labels: Skip Changelog

#5609 sdk/log: Package documentation
  sdk/log/doc.go
Labels: documentation, pkg:SDK, area:logs, Skip Changelog

#5613 Document Logger name and version recommendations
  log/provider.go
Labels: documentation, Skip Changelog

#5606 Add comment to other observable instruments about repeated creation with callbacks
  sdk/metric/doc.go
  sdk/metric/meter.go
Labels: area:metrics, Skip Changelog

#5612 Update example instrumentation names
  CHANGELOG.md
  example/dice/rolldice.go
  example/namedtracer/foo/foo.go
  example/namedtracer/main.go
  example/opencensus/main.go
  example/otel-collector/main.go
  example/passthrough/handler/handler.go
  example/passthrough/main.go
  example/prometheus/main.go
  example/zipkin/main.go
Labels: pkg:example

#5614 Add integration tests for otlploggrpc exporter
  exporters/otlp/otlplog/otlploggrpc/exporter_test.go
Labels: Skip Changelog

#5615 Add example test for otlploggrpc
  exporters/otlp/otlplog/otlploggrpc/example_test.go
Labels: Skip Changelog

#5600 Refactor Batch Processor benchmark to really test OnEnd
  sdk/trace/batch_span_processor_test.go
Labels: Skip Changelog

#5620 Separate trace API components into own files
  trace/provider.go
  trace/span.go
  trace/span_test.go
  trace/trace.go
  trace/trace_test.go
  trace/tracer.go
Labels: Skip Changelog

#5622 Add `otlploggrpc` package documentation
  exporters/otlp/otlplog/otlploggrpc/doc.go
  exporters/otlp/otlplog/otlploggrpc/exporter.go
Labels: Skip Changelog

#5631 Rely on net/http error content rather than unreliable deadline exceeded
  exporters/otlp/otlptrace/otlptracehttp/client_test.go
Labels: Skip Changelog

#5634 baggage: fix grammar error
  baggage/baggage.go
Labels: Skip Changelog

#5632 Fix otlp grpc exporters doc to require a scheme
  exporters/otlp/otlplog/otlploggrpc/doc.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/doc.go
  exporters/otlp/otlptrace/otlptracegrpc/doc.go
Labels: Skip Changelog

#5635 Use actuated runner to run benchmark
  .github/workflows/benchmark.yml
Labels: Skip Changelog

#5649 typo: fix docs
  sdk/metric/reader.go
Labels: documentation, Skip Changelog

#5657 Fix benchmark ci
  .github/workflows/benchmark.yml
Labels: Skip Changelog

#5653 [chore] Add asasalint linter
  .golangci.yml
  log/keyvalue_test.go
  sdk/log/provider_test.go
Labels: Skip Changelog
