Repository open-telemetry/opentelemetry-go, pull requests merged in 2024-02, with the labels that each got.

#4888 Fix callback registration bug
  CHANGELOG.md
  sdk/metric/meter.go
  sdk/metric/meter_test.go
Labels: bug, area:metrics

#4887 resource: Add testable example
  sdk/resource/example_test.go
Labels: documentation, area:resources, Skip Changelog

#4809 log: Add design doc
  Makefile
  log/DESIGN.md
Labels: Skip Changelog

#4895 sdk/metrics: Move experimental docs to x package
  CHANGELOG.md
  sdk/metric/doc.go
  sdk/metric/internal/x/README.md
Labels: Skip Changelog

#4900 Add exemplar support to the OTLP HTTP and gRPC exporters
  CHANGELOG.md
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/transform/metricdata.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/transform/metricdata_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/transform/metricdata.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/transform/metricdata_test.go
  internal/shared/otlp/otlpmetric/transform/metricdata.go.tmpl
  internal/shared/otlp/otlpmetric/transform/metricdata_test.go.tmpl
Labels: enhancement, area:metrics, pkg:exporter:otlp

#4897 [chore] Update Project Status for Logs
  README.md
Labels: Skip Changelog

#4917 Link logs RC in project status of README
  README.md
Labels: documentation, Skip Changelog

#4918 [docs] Log design fix
  log/DESIGN.md
Labels: documentation, area:logs, Skip Changelog

#4920 internal/global,trace: fix spelling error
  internal/global/state.go
Labels: documentation, Skip Changelog

#4907 Add initial Logs Bridge API scaffolding
  .github/dependabot.yml
  log/doc.go
  log/go.mod
  log/go.sum
  log/keyvalue.go
  log/kind_string.go
  log/logger.go
  log/provider.go
  log/record.go
  log/severity.go
  log/severity_string.go
  versions.yaml
Labels: area:logs, Skip Changelog

#4940 Fix typos in docs and comments
  .codespellignore
  Makefile
  README.md
  log/DESIGN.md
  sdk/metric/exemplar.go
  sdk/metric/internal/exemplar/reservoir_test.go
  sdk/metric/meter_test.go
  sdk/trace/trace_test.go
Labels: documentation, Skip Changelog

#4932 Add the `log/embedded` package
  log/embedded/embedded.go
  log/logger.go
  log/provider.go
Labels: Skip Changelog

#4935 Update `otel/log` package docs
  log/doc.go
Labels: documentation, area:logs, Skip Changelog

#4936 Rename log List value kind to Slice
  log/DESIGN.md
  log/keyvalue.go
  log/kind_string.go
Labels: area:logs, Skip Changelog

#4937 Implement the `LoggerConfig` and add the `LoggerOption`s
  log/go.mod
  log/go.sum
  log/logger.go
  log/logger_test.go
Labels: area:logs, Skip Changelog

#4938 Test `Severity` constants match OTel specified values and short names
  log/severity_test.go
Labels: area:logs, Skip Changelog

#4944 Fix test name in `trace/noop` package
  trace/noop/noop_test.go
Labels: area:trace, Skip Changelog

#4939 Implement the log Record type
  log/record.go
  log/record_test.go
Labels: area:logs, Skip Changelog

#4947 doc: fix godoc for WithEndpointURL and WithEndpoint
  exporters/otlp/otlptrace/otlptracegrpc/options.go
  exporters/otlp/otlptrace/otlptracehttp/options.go
Labels: documentation, Skip Changelog, pkg:exporter:otlp

#4948 design: log value accessors must not panic
  log/DESIGN.md
Labels: area:logs, Skip Changelog

#4949 log: Implement Value and KeyValue types
  log/go.mod
  log/go.sum
  log/keyvalue.go
  log/keyvalue_test.go
Labels: area:logs, Skip Changelog

#4958 log: Add benchmark tests
  log/keyvalue_bench_test.go
  log/record_bench_test.go
Labels: area:logs, Skip Changelog

#4956 Fix output exponential histogram negative buckets
  CHANGELOG.md
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/exponential_histogram_test.go
Labels: bug, area:metrics

#4961 Add experimental-logs module set
  CHANGELOG.md
  versions.yaml
Labels: area:logs

#4970 Add links to log documentation
  log/doc.go
  log/embedded/embedded.go
  log/noop/noop.go
Labels: documentation, Skip Changelog

#4982 Utilize the new slices package in `sdk/metric`
  sdk/metric/aggregation.go
  sdk/metric/exemplar.go
  sdk/metric/internal/aggregate/histogram.go
  sdk/metric/internal/exemplar/hist.go
  sdk/metric/internal/exemplar/rand_test.go
Labels: area:metrics, Skip Changelog

#4981 Clear aggregate value maps instead of deleting entries
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/histogram.go
  sdk/metric/internal/aggregate/lastvalue.go
  sdk/metric/internal/aggregate/sum.go
Labels: area:metrics, Skip Changelog

#4984 [chore] log: Remove resolved issue from DESIGN.md
  log/DESIGN.md
Labels: documentation, Skip Changelog

#4988 Use `slices.Sort` in Prometheus exporter instead of `sort.Slice`
  exporters/prometheus/exporter.go
Labels: Skip Changelog, pkg:exporter:prometheus

#4990 Use `slices.SortFunc` in OpenCensus bridge instead of `sort` package
  bridge/opencensus/internal/ocmetric/metric.go
  bridge/opencensus/internal/ocmetric/metric_test.go
Labels: Skip Changelog

#4991 Use `slices.Sort` in propagators test instead of `sort.Slice`
  propagation/propagation_test.go
Labels: area:propagators, Skip Changelog

#4992 Use `slices.Sort` in baggage test instead of `sort.Slice`
  baggage/baggage_test.go
Labels: Skip Changelog, area:baggage
