Repository open-telemetry/opentelemetry-go, pull requests merged in 2024-03, with the labels that each got.

#5025 Fix dependabot-pr.sh
  .github/workflows/scripts/dependabot-pr.sh
Labels: pkg:tooling, Skip Changelog

#5027 Use Distinct instead of Set for map keys
  CHANGELOG.md
  attribute/set.go
  attribute/value_test.go
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/exponential_histogram_test.go
  sdk/metric/internal/aggregate/histogram.go
  sdk/metric/internal/aggregate/histogram_test.go
  sdk/metric/internal/aggregate/lastvalue.go
  sdk/metric/internal/aggregate/limit.go
  sdk/metric/internal/aggregate/limit_test.go
  sdk/metric/internal/aggregate/sum.go
  sdk/metric/meter_test.go
Labels: area:metrics, pkg:attribute

#5050 exporters/otlp: fix spelling errors
  exporters/otlp/otlpmetric/otlpmetrichttp/client.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
Labels: Skip Changelog

#5048 chore: remove repetitive words
  semconv/v1.10.0/trace.go
  semconv/v1.11.0/trace.go
  semconv/v1.12.0/trace.go
  semconv/v1.13.0/trace.go
  semconv/v1.14.0/trace.go
  semconv/v1.15.0/trace.go
  semconv/v1.16.0/trace.go
  semconv/v1.4.0/trace.go
  semconv/v1.5.0/trace.go
  semconv/v1.6.1/trace.go
  semconv/v1.7.0/trace.go
  semconv/v1.8.0/trace.go
  semconv/v1.9.0/trace.go
Labels: Skip Changelog

#4954 sdk/log: Add design doc
  sdk/log/DESIGN.md
Labels: pkg:SDK, area:logs, Skip Changelog

#5068 sdk/log: Scaffolding
  .github/dependabot.yml
  sdk/log/DESIGN.md
  sdk/log/batch.go
  sdk/log/doc.go
  sdk/log/exporter.go
  sdk/log/go.mod
  sdk/log/go.sum
  sdk/log/logger.go
  sdk/log/processor.go
  sdk/log/provider.go
  sdk/log/record.go
  sdk/log/simple.go
  versions.yaml
Labels: Skip Changelog

#5073 Implement `sdk/log.Record`
  sdk/log/go.mod
  sdk/log/go.sum
  sdk/log/record.go
  sdk/log/record_test.go
Labels: area:logs, Skip Changelog

#5072 Add SeverityUndefined to `otel/log`
  CHANGELOG.md
  log/severity.go
  log/severity_string.go
  log/severity_test.go
Labels: area:logs

#5076 logs: Add empty value for KeyValue
  CHANGELOG.md
  log/keyvalue.go
  log/keyvalue_test.go
Labels: area:logs

#5071 Add the Enabled method to the Logger
  CHANGELOG.md
  log/logger.go
  log/noop/noop.go
  sdk/log/batch.go
  sdk/log/logger.go
  sdk/log/processor.go
  sdk/log/simple.go
Labels: area:logs

#5074 Implement the providerConfig
  sdk/log/provider.go
  sdk/log/provider_test.go
Labels: area:logs, Skip Changelog

#5077 Simplify log design docs
  log/DESIGN.md
  sdk/log/DESIGN.md
Labels: documentation, area:logs, Skip Changelog

#5079 Implement the SimpleProcessor
  sdk/log/exporter.go
  sdk/log/simple.go
  sdk/log/simple_test.go
Labels: area:logs, Skip Changelog

#5080 Implement the LoggerProvider
  sdk/log/go.mod
  sdk/log/logger.go
  sdk/log/provider.go
  sdk/log/provider_test.go
Labels: area:logs, Skip Changelog

#5081 Implement logger
  sdk/log/logger.go
  sdk/log/logger_test.go
  sdk/log/provider_test.go
Labels: Skip Changelog

#5083 Return a single instance of the noop exporter
  sdk/log/exporter.go
  sdk/log/simple.go
Labels: area:logs, Skip Changelog

#5085 Add global log package
  CHANGELOG.md
  log/global/log.go
  log/global/log_test.go
  log/internal/global/log.go
  log/internal/global/log_test.go
  log/internal/global/state.go
  log/internal/global/state_test.go
Labels: pkg:API, area:logs

#5091 sdk/log: ObservedTimestamp should be set
  sdk/log/logger.go
  sdk/log/logger_test.go
Labels: area:logs, Skip Changelog

#5096 fix: default http endpoint port to 4318 in documentation of otlptracehttp package
  exporters/otlp/otlpmetric/otlpmetrichttp/config.go
  exporters/otlp/otlptrace/otlptracehttp/options.go
Labels: documentation, Skip Changelog

#5097 Fix spelling errors in batch.go
  sdk/log/batch.go
Labels: documentation, area:logs, Skip Changelog

#4996 sdk/trace: fix grammar errors
  sdk/trace/simple_span_processor.go
Labels: Skip Changelog

#5088 Implement the BatchingProcessor configuration
  sdk/log/batch.go
  sdk/log/batch_test.go
  sdk/log/provider.go
  sdk/log/provider_test.go
  sdk/log/setting.go
  sdk/log/setting_test.go
Labels: area:logs, Skip Changelog

#5106 Refactor testing of batching config
  sdk/log/batch_test.go
Labels: area:logs, Skip Changelog

#5101 Add benchmark for logger
  sdk/log/logger_bench_test.go
  sdk/log/logger_test.go
Labels: Skip Changelog

#5105 Add export sync
  sdk/log/exporter.go
  sdk/log/exporter_test.go
Labels: area:logs, Skip Changelog

#5110 fix benchmarks action
  .github/workflows/benchmark.yml
Labels: Skip Changelog
