Repository open-telemetry/opentelemetry-go, pull requests merged in 2024-08, with the labels that each got.

#5636 sdk/log: Processor.OnEmit accetps a Record pointer
  CHANGELOG.md
  sdk/log/DESIGN.md
  sdk/log/batch.go
  sdk/log/batch_test.go
  sdk/log/bench_test.go
  sdk/log/example_test.go
  sdk/log/logger.go
  sdk/log/logger_norace_test.go
  sdk/log/processor.go
  sdk/log/provider.go
  sdk/log/provider_test.go
  sdk/log/simple.go
  sdk/log/simple_test.go
Labels: pkg:SDK, area:logs

#5667 Fix membership link
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#5664 Fix benchmark that does not compare the exact result from the previous commit
  .github/workflows/benchmark.yml
Labels: Skip Changelog

#5665 sdk/log: SimpleProcessor to not panic for zero value
  CHANGELOG.md
  sdk/log/simple.go
  sdk/log/simple_test.go
Labels: pkg:SDK, area:logs

#5658 Fix interfaces doc formatting
  metric/meter.go
  sdk/log/exporter.go
  sdk/log/processor.go
Labels: documentation, Skip Changelog

#5670 Fix stdoutlog import path
  exporters/stdout/stdoutlog/exporter_test.go
Labels: documentation, Skip Changelog

#5666 sdk/log: SimpleProcessor synchronizes OnEmit calls
  CHANGELOG.md
  sdk/log/exporter.go
  sdk/log/simple.go
  sdk/log/simple_test.go
Labels: pkg:SDK, area:logs

#5693 Ensure exported struct in `sdk/log` are not comparable
  CHANGELOG.md
  sdk/log/batch.go
  sdk/log/provider.go
  sdk/log/record.go
  sdk/log/simple.go
Labels: pkg:SDK, area:logs

#5695 Use self hosted runner to run benchmark
  .github/workflows/benchmark.yml
Labels: Skip Changelog

#5694 Save benchmark cache even the job is failed
  .github/workflows/benchmark.yml
Labels: Skip Changelog

#5132 baggage: Accept non-ASCII keys
  CHANGELOG.md
  baggage/baggage.go
  baggage/baggage_test.go
Labels: area:baggage

#5717 Stabilize benchmark result of `BenchmarkValueEqual`
  log/keyvalue_bench_test.go
Labels: Skip Changelog

#5692 Move `log.Processor.Enabled` to independent `FilterProcessor` interfaced type
  CHANGELOG.md
  sdk/log/batch.go
  sdk/log/batch_test.go
  sdk/log/doc.go
  sdk/log/example_test.go
  sdk/log/internal/x/README.md
  sdk/log/internal/x/x.go
  sdk/log/logger.go
  sdk/log/logger_test.go
  sdk/log/processor.go
  sdk/log/provider.go
  sdk/log/provider_test.go
  sdk/log/simple.go
  sdk/log/simple_test.go
Labels: pkg:SDK, area:logs

#5732 Release v1.29.0/v0.51.0/v0.5.0
  CHANGELOG.md
  bridge/opencensus/go.mod
  bridge/opencensus/test/go.mod
  bridge/opencensus/version.go
  bridge/opentracing/go.mod
  bridge/opentracing/test/go.mod
  example/dice/go.mod
  example/namedtracer/go.mod
  example/opencensus/go.mod
  example/otel-collector/go.mod
  example/passthrough/go.mod
  example/prometheus/go.mod
  example/zipkin/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/version.go
  exporters/otlp/otlplog/otlploghttp/go.mod
  exporters/otlp/otlplog/otlploghttp/version.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/version.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/version.go
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/version.go
  exporters/prometheus/go.mod
  exporters/stdout/stdoutlog/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  log/go.mod
  metric/go.mod
  sdk/go.mod
  sdk/log/go.mod
  sdk/metric/go.mod
  sdk/metric/version.go
  sdk/version.go
  trace/go.mod
  version.go
  versions.yaml
Labels: Unlock Released Changelog

#5754 Fix duplicate instrumentation memory leak
  CHANGELOG.md
  internal/global/meter.go
  internal/global/meter_test.go
Labels: bug, area:metrics
