Repository open-telemetry/opentelemetry-go, pull requests merged in 2024-01, with the labels that each got.

#4804 baggage: Add NewMemberRaw and NewKeyValuePropertyRaw
  CHANGELOG.md
  baggage/baggage.go
  baggage/baggage_test.go
  bridge/opentracing/bridge.go
  bridge/opentracing/bridge_test.go
  bridge/opentracing/mix_test.go
  example/namedtracer/main.go
  propagation/baggage_test.go
Labels: pkg:bridges, area:baggage

#4822 chore(docs): explicitly mark lizthegrey emeritus
  CONTRIBUTING.md
Labels: documentation, Skip Changelog

#4828 Fix link changes from instrumentation to languages
  README.md
  RELEASING.md
  doc.go
Labels: Skip Changelog

#4830 Add @dashpole (David Ashpole) as a maintainer
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#4833 docs: minor update to docstrings
  attribute/set.go
  exporters/otlp/otlptrace/exporter.go
  exporters/stdout/stdouttrace/trace.go
  exporters/zipkin/zipkin.go
  sdk/resource/resource.go
  sdk/trace/batch_span_processor.go
  sdk/trace/provider.go
Labels: Skip Changelog

#4835 Add the `sdk/metric/internal/exemplar` package
  sdk/metric/go.mod
  sdk/metric/internal/exemplar/doc.go
  sdk/metric/internal/exemplar/reservoir.go
  sdk/metric/internal/exemplar/reservoir_test.go
Labels: Skip Changelog

#4849 example/dice: Do not use semconv
  example/dice/doc.go
  example/dice/main.go
  example/dice/otel.go
Labels: Skip Changelog

#4850 Add the Drop exemplar Reservoir implementation
  sdk/metric/internal/exemplar/drop.go
  sdk/metric/internal/exemplar/drop_test.go
Labels: Skip Changelog

#4851 Add the SampledFilter exemplar Reservoir implementation
  sdk/metric/internal/exemplar/filter.go
  sdk/metric/internal/exemplar/filter_test.go
Labels: Skip Changelog

#4852 Add the random fixed size exemplar reservoir
  sdk/metric/internal/exemplar/rand.go
  sdk/metric/internal/exemplar/rand_test.go
  sdk/metric/internal/exemplar/reservoir_test.go
  sdk/metric/internal/exemplar/storage.go
Labels: Skip Changelog

#4855 fix: Fix stdouttrace/example_test to make the trace_id same.
  exporters/stdout/stdouttrace/example_test.go
Labels: documentation, Skip Changelog

#4872 stdouttrace: Refine example
  exporters/stdout/stdouttrace/example_test.go
Labels: documentation, Skip Changelog

#4871 Add the experimental exemplar feature
  CHANGELOG.md
  sdk/metric/EXPERIMENTAL.md
  sdk/metric/benchmark_test.go
  sdk/metric/exemplar.go
  sdk/metric/internal/aggregate/aggregate.go
  sdk/metric/internal/aggregate/aggregate_test.go
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/exponential_histogram_test.go
  sdk/metric/internal/aggregate/histogram.go
  sdk/metric/internal/aggregate/histogram_test.go
  sdk/metric/internal/aggregate/lastvalue.go
  sdk/metric/internal/aggregate/sum.go
  sdk/metric/pipeline.go
  sdk/metric/pipeline_test.go
Labels: area:metrics

#4873 Remove the Flush method from Exemplar
  sdk/metric/internal/exemplar/drop.go
  sdk/metric/internal/exemplar/filter_test.go
  sdk/metric/internal/exemplar/rand.go
  sdk/metric/internal/exemplar/reservoir.go
  sdk/metric/internal/exemplar/reservoir_test.go
  sdk/metric/internal/exemplar/storage.go
Labels: area:metrics, Skip Changelog
