Repository open-telemetry/opentelemetry-go, pull requests merged in 2024-06, with the labels that each got.

#5448 sdk/log: Add processor benchmarks
  sdk/log/bench_test.go
Labels: pkg:SDK, area:logs, Skip Changelog

#5456 Guard rng in exemplar rand computation
  CHANGELOG.md
  sdk/metric/internal/exemplar/rand.go
  sdk/metric/internal/exemplar/rand_test.go
Labels: bug

#5463 add `log` package to depguard linter
  .golangci.yml
Labels: Skip Changelog

#5489 Bump min Go version used in CI
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
Labels: Skip Changelog

#5444 Add the sdk/internal/x package
  sdk/internal/x/README.md
  sdk/internal/x/x.go
  sdk/internal/x/x_test.go
Labels: Skip Changelog

#5383 Add implementation of otlploggrpc configuration
  exporters/otlp/otlplog/otlploggrpc/config.go
  exporters/otlp/otlplog/otlploggrpc/config_test.go
  exporters/otlp/otlplog/otlploggrpc/go.mod
Labels: Skip Changelog

#5507 Move evantorrie to emeritus status
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#5506 Add missing word in WithView() doc string
  sdk/metric/config.go
Labels: Skip Changelog

#5494 fix(baggage): validate chars panic with 0x80
  CHANGELOG.md
  baggage/baggage.go
  baggage/baggage_test.go
Labels: bug, area:baggage

#5508 Correct the comment for the priority of options and environments on otlptracegrpc
  CHANGELOG.md
  exporters/otlp/otlptrace/otlptracegrpc/client_unit_test.go
  exporters/otlp/otlptrace/otlptracegrpc/options.go
Labels: area:trace, pkg:exporter:otlp

#5517 Fix timestamp handling for the lastvalue aggregation
  CHANGELOG.md
  sdk/metric/internal/aggregate/lastvalue.go
  sdk/metric/internal/aggregate/lastvalue_test.go
Labels: pkg:SDK, area:metrics

#5524 Add tenv linter
  .golangci.yml
Labels: Skip Changelog

#5532 Do not fail CI on codecov create report
  .github/workflows/ci.yml
Labels: Skip Changelog

#5529 Add unconvert linter
  .golangci.yml
  bridge/opencensus/internal/ocmetric/metric.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/oconf/options_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/transform/metricdata.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/oconf/options_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/transform/metricdata.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/otlpconfig/options_test.go
  exporters/otlp/otlptrace/otlptracehttp/internal/otlpconfig/options_test.go
  internal/shared/otlp/otlpmetric/oconf/options_test.go.tmpl
  internal/shared/otlp/otlpmetric/transform/metricdata.go.tmpl
  internal/shared/otlp/otlptrace/otlpconfig/options_test.go.tmpl
  sdk/metric/internal/exemplar/reservoir_test.go
  semconv/internal/v2/net.go
  semconv/internal/v3/net.go
  semconv/internal/v4/net.go
Labels: Skip Changelog

#5531 Add unparam linter
  .golangci.yml
  exporters/stdout/stdouttrace/config.go
  exporters/stdout/stdouttrace/trace.go
  log/keyvalue_test.go
  sdk/internal/x/x_test.go
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/benchmark_test.go
  sdk/trace/util_test.go
Labels: Skip Changelog

#5492 Add example for synchronous gauge
  metric/example_test.go
Labels: Skip Changelog

#5523 Add `newClient` method for otlploggrpc gRPC client
  exporters/otlp/otlplog/otlploggrpc/client.go
  exporters/otlp/otlplog/otlploggrpc/client_test.go
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.sum
Labels: Skip Changelog

#5533 Verify versions.yaml is up to date in CI
  .github/workflows/ci.yml
  Makefile
Labels: pkg:tooling, Skip Changelog

#5534 Decouple codecov upload from coverage testing
  .github/workflows/ci.yml
Labels: Skip Changelog

#5535 Add errorlint linter
  .golangci.yml
  baggage/baggage.go
  exporters/otlp/otlplog/otlploggrpc/config.go
  exporters/otlp/otlplog/otlploggrpc/internal/retry/retry.go
  exporters/otlp/otlplog/otlploghttp/client.go
  exporters/otlp/otlplog/otlploghttp/internal/retry/retry.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/exporter.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/retry/retry.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/transform/error.go
  exporters/otlp/otlpmetric/otlpmetrichttp/client.go
  exporters/otlp/otlpmetric/otlpmetrichttp/exporter.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/retry/retry.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/transform/error.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/retry/retry.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
  exporters/otlp/otlptrace/otlptracehttp/internal/retry/retry.go
  exporters/prometheus/exporter.go
  exporters/zipkin/zipkin.go
  internal/shared/otlp/otlpmetric/transform/error.go.tmpl
  internal/shared/otlp/retry/retry.go.tmpl
  sdk/metric/periodic_reader.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/provider.go
Labels: Skip Changelog

#5550 sdk/log: Add altering Processor example
  sdk/log/example_test.go
  sdk/log/record.go
Labels: documentation, pkg:SDK, area:logs, Skip Changelog

#5546 Split the set and add attributes benchmarks
  sdk/log/record_test.go
Labels: Skip Changelog

#5547 Add walk attributes benchmark
  sdk/log/record_test.go
Labels: Skip Changelog

#5548 Add benchmark retrieving a new logger
  sdk/log/provider_test.go
Labels: Skip Changelog

#5554 Split the span start/end benchmarks and test start with links and attributes
  sdk/trace/span_test.go
  sdk/trace/trace_test.go
Labels: Skip Changelog
