Repository open-telemetry/opentelemetry-go, pull requests merged in 2024-12, with the labels that each got.

#6009 log: Change EnabledParameters to have a field instead of getter and setter
  CHANGELOG.md
  log/DESIGN.md
  log/logger.go
  log/logtest/recorder_test.go
  sdk/log/logger_test.go
Labels: pkg:API, area:logs

#6015 chore: fix a typo in TestMeterCreatesInstruments
  sdk/metric/meter_test.go
Labels: Skip Changelog

#6030 Cache successful requests in lychee
  .github/workflows/links-fail-fast.yml
  .github/workflows/links.yml
Labels: Skip Changelog

#6032 Fix sdk/log record attr value limit
  CHANGELOG.md
  sdk/log/record.go
  sdk/log/record_test.go
Labels: bug, pkg:SDK, area:logs

#6035 Release v1.33.0
  CHANGELOG.md
  bridge/opencensus/go.mod
  bridge/opencensus/test/go.mod
  bridge/opencensus/version.go
  bridge/opentracing/go.mod
  bridge/opentracing/test/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/version.go
  exporters/otlp/otlplog/otlploghttp/go.mod
  exporters/otlp/otlplog/otlploghttp/version.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/version.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/version.go
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/version.go
  exporters/prometheus/go.mod
  exporters/stdout/stdoutlog/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  log/go.mod
  metric/go.mod
  sdk/go.mod
  sdk/log/go.mod
  sdk/metric/go.mod
  sdk/metric/version.go
  sdk/version.go
  trace/go.mod
  version.go
  versions.yaml
Labels: Unlock Released Changelog

#6042 Fix broken link
  RELEASING.md
Labels: Skip Changelog
