Repository open-telemetry/opentelemetry-go, pull requests merged in 2024-05, with the labels that each got.

#5278 Test scope and resource transforms in `otlploghttp`
  exporters/otlp/otlplog/otlploghttp/internal/transform/log_test.go
Labels: area:logs, Skip Changelog, pkg:exporter:otlp

#5279 Add README template to semconvkit
  internal/tools/semconvkit/templates/README.md.tmpl
Labels: Skip Changelog

#5299 docs: Update Go logs status to alpha in README.md
  README.md
Labels: documentation, area:logs, Skip Changelog

#5298 docs: Add logs exporters in README.md
  README.md
Labels: documentation, area:logs, Skip Changelog

#5275 Use reflect to construct a Record in `logtest`
  exporters/otlp/otlplog/otlploghttp/internal/transform/log_test.go
  exporters/stdout/stdoutlog/exporter_test.go
  sdk/log/logtest/example_test.go
  sdk/log/logtest/factory.go
  sdk/log/logtest/factory_test.go
Labels: pkg:testing, pkg:SDK, area:logs, Skip Changelog

#5302 Fix type error in float64 instrument documentation
  metric/asyncfloat64.go
  metric/syncfloat64.go
Labels: documentation, Skip Changelog

#5301 Fix HistogramConfig documentation
  metric/syncfloat64.go
  metric/syncint64.go
Labels: documentation, Skip Changelog

#5159 Emit attributes slices as their json representation
  CHANGELOG.md
  attribute/key_test.go
  attribute/value.go
  sdk/resource/resource_test.go
Labels: bug, pkg:attribute

#5285 Refactor exemplars to not use generic argument
  sdk/metric/exemplar.go
  sdk/metric/internal/aggregate/aggregate.go
  sdk/metric/internal/aggregate/aggregate_test.go
  sdk/metric/internal/aggregate/exemplar.go
  sdk/metric/internal/aggregate/exemplar_test.go
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/histogram.go
  sdk/metric/internal/aggregate/lastvalue.go
  sdk/metric/internal/aggregate/sum.go
  sdk/metric/internal/exemplar/drop.go
  sdk/metric/internal/exemplar/drop_test.go
  sdk/metric/internal/exemplar/exemplar.go
  sdk/metric/internal/exemplar/filter.go
  sdk/metric/internal/exemplar/filter_test.go
  sdk/metric/internal/exemplar/hist.go
  sdk/metric/internal/exemplar/hist_test.go
  sdk/metric/internal/exemplar/rand.go
  sdk/metric/internal/exemplar/rand_test.go
  sdk/metric/internal/exemplar/reservoir.go
  sdk/metric/internal/exemplar/reservoir_test.go
  sdk/metric/internal/exemplar/storage.go
  sdk/metric/internal/exemplar/value.go
  sdk/metric/internal/exemplar/value_test.go
  sdk/metric/pipeline.go
Labels: pkg:SDK, area:metrics, Skip Changelog

#5314 Upgrade default go verison to 1.22.3
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
Labels: Skip Changelog

#5303 Rename synchronous instrument names in global test
  internal/global/meter_test.go
Labels: pkg:testing, Skip Changelog

#5115 Merge Span.AddLink tests
  sdk/trace/trace_test.go
Labels: Skip Changelog

#5098 exporters/otlp/otlptrace: fix incorrect documentation
  exporters/otlp/otlptrace/otlptracegrpc/internal/otlpconfig/options.go
  exporters/otlp/otlptrace/otlptracegrpc/options.go
  exporters/otlp/otlptrace/otlptracehttp/internal/otlpconfig/options.go
  exporters/otlp/otlptrace/otlptracehttp/options.go
  internal/shared/otlp/otlptrace/otlpconfig/options.go.tmpl
Labels: Skip Changelog

#5313 Generate `internal/retry` in `otlploggrpc`
  exporters/otlp/otlplog/otlploggrpc/config.go
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.sum
  exporters/otlp/otlplog/otlploggrpc/internal/gen.go
  exporters/otlp/otlplog/otlploggrpc/internal/retry/retry.go
  exporters/otlp/otlplog/otlploggrpc/internal/retry/retry_test.go
Labels: Skip Changelog

#5319 Move Aneurysm9 to emeritus status
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#5323 Test metric aggregate times
  sdk/metric/internal/aggregate/aggregate_test.go
  sdk/metric/internal/aggregate/exponential_histogram_test.go
  sdk/metric/internal/aggregate/histogram_test.go
  sdk/metric/internal/aggregate/lastvalue_test.go
  sdk/metric/internal/aggregate/sum_test.go
Labels: pkg:testing, pkg:SDK, area:metrics, Skip Changelog

#5311 Fix empty log body printed by stdoutlog exporter
  CHANGELOG.md
  exporters/stdout/stdoutlog/exporter_test.go
  exporters/stdout/stdoutlog/record.go
Labels: area:logs, pkg:exporter:stdout

#5284 Update `RELEASING.md` to obtain steps to verify the changes for contrib
  .github/ISSUE_TEMPLATE/version_release.md
  RELEASING.md
Labels: Skip Changelog

#5347 sdk/log: Document how Processor and Exporter interfaces can be extended
  CONTRIBUTING.md
  sdk/log/DESIGN.md
Labels: documentation, pkg:SDK, area:logs, Skip Changelog

#5346 Remove dependabot version updates
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/create-dependabot-pr.yml
  .github/workflows/dependabot.yml
  .github/workflows/scripts/dependabot-pr.sh
  Makefile
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: Skip Changelog

#5349 Add logs to dice example
  CHANGELOG.md
  example/dice/go.mod
  example/dice/go.sum
  example/dice/main.go
  example/dice/otel.go
  example/dice/rolldice.go
  example/dice/rolldice_go1.21.go
  example/dice/rolldice_go1.22.go
Labels: pkg:example, area:logs

#5306 log: Fix comparison of unordered map values
  CHANGELOG.md
  log/keyvalue.go
  log/keyvalue_bench_test.go
  log/keyvalue_test.go
Labels: pkg:API, area:logs

#5358 Fix logger provider var name in dice example
  example/dice/otel.go
Labels: pkg:example, Skip Changelog

#5304 Add the synchronous gauge to the metric API and SDK
  CHANGELOG.md
  internal/global/instruments.go
  internal/global/instruments_test.go
  internal/global/meter.go
  internal/global/meter_test.go
  internal/global/meter_types_test.go
  metric/embedded/embedded.go
  metric/instrument.go
  metric/meter.go
  metric/noop/noop.go
  metric/noop/noop_test.go
  metric/syncfloat64.go
  metric/syncfloat64_test.go
  metric/syncint64.go
  metric/syncint64_test.go
  sdk/metric/instrument.go
  sdk/metric/instrument_test.go
  sdk/metric/instrumentkind_string.go
  sdk/metric/meter.go
  sdk/metric/pipeline.go
  sdk/metric/pipeline_registry_test.go
  sdk/metric/reader.go
  sdk/metric/reader_test.go
  sdk/metric/view_test.go
Labels: pkg:API, pkg:SDK, area:metrics

#5365 Split log/logtest into a recorder and a logger
  CHANGELOG.md
  log/logtest/recorder.go
  log/logtest/recorder_test.go
Labels: bug, area:logs

#5375 Identify logger with schemaURL in global logger provider
  CHANGELOG.md
  log/internal/global/log.go
  log/internal/global/log_test.go
Labels: bug, area:logs

#5385 Fix exported instrument kind const value change
  sdk/metric/instrument.go
  sdk/metric/instrumentkind_string.go
  sdk/metric/pipeline_registry_test.go
Labels: bug, Skip Changelog

#5386 Recheck log message in TestBatchProcessor
  sdk/log/batch_test.go
Labels: bug, Skip Changelog

#5378 Pool `otlploghttp` transform maps
  exporters/otlp/otlplog/otlploghttp/internal/transform/log.go
  exporters/otlp/otlplog/otlploghttp/internal/transform/log_test.go
Labels: area:logs, Skip Changelog, pkg:exporter:otlp

#5411 Fix test name in otlploghttp
  exporters/otlp/otlplog/otlploghttp/config_test.go
Labels: Skip Changelog

#5407 sdk/log: Fix BenchmarkLoggerNewRecord to not drop attributes
  sdk/log/logger_bench_test.go
Labels: Skip Changelog

#5376 Log a warning when log Record attribute is dropped
  CHANGELOG.md
  sdk/log/record.go
  sdk/log/record_test.go
Labels: pkg:SDK, area:logs

#5421 sdk/log: Fix TestBatchProcessor/DroppedLogs flaky test
  sdk/log/batch_test.go
Labels: Skip Changelog

#5426 Identify global `Tracer`s and `Meter`s with their schema URLs
  CHANGELOG.md
  internal/global/meter.go
  internal/global/meter_test.go
  internal/global/trace.go
  internal/global/trace_test.go
Labels: bug, area:metrics, area:trace

#5416 sdk/log: Fix TestBatchProcessor/ForceFlush/ErrorPartialFlush flaky test
  sdk/log/batch_test.go
Labels: Skip Changelog

#5431 Export the Instrument IsEmpty method
  CHANGELOG.md
  sdk/metric/instrument.go
  sdk/metric/view.go
Labels: pkg:SDK, area:metrics

#5433 Remove zeroInstrumentKind
  sdk/metric/instrument.go
Labels: pkg:SDK, area:metrics, Skip Changelog

#5434 Log warning when a trace attribute/event/link is discarded due to limits
  CHANGELOG.md
  sdk/trace/evictedqueue.go
  sdk/trace/evictedqueue_test.go
  sdk/trace/span.go
  sdk/trace/span_test.go
  sdk/trace/tracer.go
Labels: pkg:SDK, area:trace

#5267 Remove opentelemetry-proto in .gitsubmodule
  .gitmodules
Labels: Skip Changelog

#5435 Document instrument name requirements
  CHANGELOG.md
  metric/doc.go
  metric/meter.go
Labels: pkg:API, documentation, area:metrics

#5443 Move `MonotonicEndTime` to only use
  sdk/internal/internal.go
  sdk/trace/span.go
Labels: pkg:SDK, area:trace, Skip Changelog
