Repository open-telemetry/opentelemetry-go, pull requests merged in 2025-07, with the labels that each got.

#6938 log/logtest: improve Transform usage in the example
  log/logtest/example_test.go
Labels: area:logs, Skip Changelog

#6969 Ignore link to semconv model in Makefile
  .lycheeignore
Labels: Skip Changelog

#6968 sdk/log: Add WithAllowKeyDuplication logger provider option
  CHANGELOG.md
  sdk/log/logger.go
  sdk/log/logger_test.go
  sdk/log/provider.go
  sdk/log/provider_test.go
  sdk/log/record.go
  sdk/log/record_test.go
Labels: pkg:SDK, area:logs

#6998 chore(semconv): follow weaver folder structure
  Makefile
  semconv/templates/registry/go/attribute_group.go.j2
  semconv/templates/registry/go/helpers.j2
  semconv/templates/registry/go/instrument.j2
  semconv/templates/registry/go/metric.go.j2
Labels: Skip Changelog

#7047 Revert grpc upgrade to v1.74.*
  bridge/opentracing/go.mod
  bridge/opentracing/go.sum
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.sum
  exporters/otlp/otlplog/otlploghttp/go.mod
  exporters/otlp/otlplog/otlploghttp/go.sum
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.sum
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/go.sum
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.sum
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.sum
  trace/internal/telemetry/test/go.mod
  trace/internal/telemetry/test/go.sum
Labels: dependencies, Skip Changelog

#7064 docs: unify doc comments for functions returning bool
  attribute/encoder.go
  attribute/iterator.go
  attribute/key.go
  attribute/kv.go
  attribute/set.go
  bridge/opencensus/internal/span.go
  log/keyvalue.go
  log/logger.go
  sdk/internal/x/x.go
  sdk/log/filter_processor.go
  sdk/metric/instrument.go
  sdk/metric/internal/x/x.go
  sdk/resource/os_release_unix.go
  sdk/resource/resource.go
  sdk/trace/internal/x/x.go
  sdk/trace/span.go
  trace/config.go
  trace/internal/telemetry/attr.go
  trace/internal/telemetry/id.go
  trace/internal/telemetry/value.go
  trace/trace.go
Labels: Skip Changelog

#7053 Add Flc as an approver
  CODEOWNERS
  CONTRIBUTING.md
Labels: Skip Changelog

#7093 Remove notice about internaltest which is not generated anymore
  internal/internaltest/doc.go
  internal/internaltest/text_map_carrier.go
  internal/internaltest/text_map_carrier_test.go
  internal/internaltest/text_map_propagator.go
  internal/internaltest/text_map_propagator_test.go
Labels: documentation, Skip Changelog

#7095 chore: enable gocritic linter
  .golangci.yml
  attribute/encoder.go
  attribute/filter.go
  baggage/baggage.go
  bridge/opencensus/trace_test.go
  bridge/opentracing/bridge_test.go
  exporters/otlp/otlplog/otlploggrpc/client.go
  exporters/otlp/otlplog/otlploggrpc/config.go
  exporters/otlp/otlplog/otlploggrpc/config_test.go
  exporters/otlp/otlplog/otlploghttp/client.go
  exporters/otlp/otlplog/otlploghttp/config_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/client.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
  exporters/prometheus/exporter.go
  exporters/zipkin/model.go
  exporters/zipkin/zipkin.go
  exporters/zipkin/zipkin_test.go
  internal/global/internal_logging_test.go
  propagation/baggage_test.go
  propagation/trace_context_benchmark_test.go
  sdk/internal/x/x.go
  sdk/log/ring_test.go
  sdk/metric/exemplar/fixed_size_reservoir.go
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/exponential_histogram_test.go
  sdk/metric/meter.go
  sdk/metric/pipeline_test.go
  sdk/resource/os_release_unix.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/internal/x/x.go
  sdk/trace/tracer.go
  semconv/internal/http_test.go
  semconv/internal/v2/http.go
  semconv/internal/v3/http.go
  semconv/internal/v4/http.go
  trace/trace.go
  trace/tracestate.go
Labels: Skip Changelog
