Repository open-telemetry/opentelemetry-go, pull requests merged in 2025-02, with the labels that each got.

#6235 Use archive URL for weaver registry
  Makefile
  RELEASING.md
Labels: pkg:tooling, Skip Changelog

#6239 sdk/log: Assign fltrProcessors on provider creation instead of lazy
  sdk/log/logger.go
  sdk/log/logger_bench_test.go
  sdk/log/logger_test.go
  sdk/log/provider.go
Labels: area:logs, Skip Changelog

#6203 Add an auto-instrumentable no-op implementation to the `trace` package
  trace/auto.go
  trace/auto_test.go
  trace/internal/telemetry/attr.go
  trace/internal/telemetry/attr_test.go
  trace/internal/telemetry/bench_test.go
  trace/internal/telemetry/conv_test.go
  trace/internal/telemetry/doc.go
  trace/internal/telemetry/id.go
  trace/internal/telemetry/number.go
  trace/internal/telemetry/resource.go
  trace/internal/telemetry/resource_test.go
  trace/internal/telemetry/scope.go
  trace/internal/telemetry/scope_test.go
  trace/internal/telemetry/span.go
  trace/internal/telemetry/span_test.go
  trace/internal/telemetry/status.go
  trace/internal/telemetry/test/conversion_test.go
  trace/internal/telemetry/test/doc.go
  trace/internal/telemetry/test/go.mod
  trace/internal/telemetry/test/go.sum
  trace/internal/telemetry/traces.go
  trace/internal/telemetry/traces_test.go
  trace/internal/telemetry/value.go
  trace/noop.go
  versions.yaml
Labels: Skip Changelog

#6247 Create scorecard.yml to enable OSSF Scorecard reporting
  .github/workflows/scorecard.yml
Labels: Skip Changelog

#6267 Use renovate best-practices
  renovate.json
Labels: Skip Changelog

#6257 Fix comment of the RecordOnly sampling decision
  sdk/trace/sampling.go
Labels: Skip Changelog

#6268 Default github workflow permission read-all
  .github/workflows/benchmark.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/codespell.yaml
  .github/workflows/links-fail-fast.yml
  .github/workflows/links.yml
  .github/workflows/markdown-fail-fast.yml
  .github/workflows/markdown.yml
  .github/workflows/protect-released-changelog.yml
Labels: Skip Changelog

#6269 Add an OpenSSF badge to README.md
  README.md
Labels: Skip Changelog

#6284 Close stale issues and PRs after 2 years of inactivity
  .github/workflows/close-stale.yml
Labels: Skip Changelog

#6272 Document and check resource comparability
  CHANGELOG.md
  sdk/resource/resource.go
Labels: Skip Changelog

#6313 Replace tenv with usetesting
  .golangci.yml
  sdk/resource/host_id_readfile_test.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/span_limits_test.go
Labels: Skip Changelog

#6315 sdk/log: Change BenchmarkLoggerNewRecord to BenchmarkLoggerEmit
  sdk/log/logger_bench_test.go
Labels: pkg:SDK, area:logs, Skip Changelog

#6317 sdk/log: Add FilterProcessor and EnabledParameters
  CHANGELOG.md
  log/logger.go
  sdk/log/doc.go
  sdk/log/example_test.go
  sdk/log/filter_processor.go
  sdk/log/internal/x/README.md
  sdk/log/internal/x/x.go
  sdk/log/logger.go
  sdk/log/logger_test.go
  sdk/log/processor.go
  sdk/log/provider.go
  sdk/log/provider_test.go
Labels: pkg:SDK, area:logs

#6334 [chore] Add a policy on adding tests
  CONTRIBUTING.md
Labels: documentation
