Repository open-telemetry/opentelemetry-go, pull requests merged in 2025-08, with the labels that each got.

#7114 chore: enable extra-rules from gofumpt
  .golangci.yml
  bridge/opencensus/internal/oc2otel/span_context_test.go
  bridge/opencensus/internal/otel2oc/span_context_test.go
  bridge/opencensus/trace_test.go
  bridge/opentracing/bridge.go
  bridge/opentracing/bridge_test.go
  exporters/otlp/otlplog/otlploggrpc/client.go
  exporters/otlp/otlplog/otlploggrpc/client_test.go
  exporters/otlp/otlplog/otlploggrpc/exporter.go
  exporters/otlp/otlplog/otlploggrpc/exporter_test.go
  exporters/otlp/otlplog/otlploghttp/client.go
  exporters/otlp/otlplog/otlploghttp/client_test.go
  exporters/otlp/otlplog/otlploghttp/exporter_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/client.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/exporter.go
  exporters/otlp/otlpmetric/otlpmetrichttp/client.go
  exporters/otlp/otlpmetric/otlpmetrichttp/client_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/exporter.go
  exporters/otlp/otlptrace/exporter_test.go
  exporters/otlp/otlptrace/internal/tracetransform/attribute.go
  exporters/otlp/otlptrace/internal/tracetransform/attribute_test.go
  exporters/otlp/otlptrace/internal/tracetransform/instrumentation.go
  exporters/otlp/otlptrace/internal/tracetransform/instrumentation_test.go
  exporters/otlp/otlptrace/internal/tracetransform/resource.go
  exporters/otlp/otlptrace/internal/tracetransform/span.go
  exporters/otlp/otlptrace/internal/tracetransform/span_test.go
  exporters/otlp/otlptrace/otlptracegrpc/client.go
  exporters/otlp/otlptrace/otlptracegrpc/client_test.go
  exporters/otlp/otlptrace/otlptracegrpc/mock_collector_test.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
  exporters/otlp/otlptrace/otlptracehttp/client_test.go
  exporters/otlp/otlptrace/otlptracehttp/mock_collector_test.go
  exporters/stdout/stdoutlog/exporter_test.go
  internal/global/internal_logging_test.go
  internal/global/trace.go
  internal/global/trace_test.go
  internal/tools/semconvkit/main.go
  internal/tools/verifyreadmes/main.go
  propagation/propagation.go
  propagation/propagators_test.go
  sdk/log/bench_test.go
  sdk/log/ring_test.go
  sdk/metric/meter.go
  sdk/trace/util_test.go
  semconv/internal/http.go
  semconv/internal/http_test.go
  trace/internal/telemetry/id.go
  trace/internal/telemetry/test/conversion_test.go
  trace/trace_test.go
Labels: Skip Changelog

#7123 Add benchmark for map access using attribute Equivalent
  attribute/benchmark_test.go
Labels: Skip Changelog

#7129 Add security insights document to repository
  CONTRIBUTING.md
  SECURITY-INSIGHTS.yml
Labels: documentation, Skip Changelog

#7130 chore: enable unused-receiver rule from revive
  .golangci.yml
  bridge/opencensus/internal/tracer.go
  bridge/opencensus/internal/tracer_test.go
  bridge/opentracing/bridge.go
  bridge/opentracing/bridge_test.go
  bridge/opentracing/mix_test.go
  bridge/opentracing/mock.go
  bridge/opentracing/provider_test.go
  exporters/otlp/otlplog/otlploggrpc/client.go
  exporters/otlp/otlplog/otlploggrpc/exporter.go
  exporters/otlp/otlplog/otlploghttp/client_test.go
  exporters/otlp/otlplog/otlploghttp/exporter.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/exporter.go
  exporters/otlp/otlpmetric/otlpmetrichttp/exporter.go
  exporters/otlp/otlptrace/exporter_test.go
  exporters/otlp/otlptrace/otlptracehttp/client.go
  exporters/prometheus/exporter.go
  exporters/stdout/stdoutlog/exporter.go
  exporters/stdout/stdoutmetric/exporter.go
  internal/global/alternate_meter_test.go
  internal/global/meter_test.go
  internal/global/meter_types_test.go
  propagation/baggage.go
  propagation/propagation_test.go
  propagation/trace_context.go
  sdk/log/bench_test.go
  sdk/log/example_test.go
  sdk/log/logtest/example_test.go
  sdk/log/provider_test.go
  sdk/log/simple_test.go
  sdk/metric/exemplar/fixed_size_reservoir.go
  sdk/metric/internal/aggregate/drop.go
  sdk/metric/pipeline.go
  sdk/metric/reader.go
  sdk/resource/resource_test.go
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/id_generator.go
  sdk/trace/provider_test.go
  sdk/trace/sampling.go
  sdk/trace/simple_span_processor.go
  sdk/trace/snapshot.go
  sdk/trace/span_limits_test.go
  sdk/trace/span_processor_annotator_example_test.go
  sdk/trace/trace_test.go
  sdk/trace/tracetest/exporter.go
  sdk/trace/tracetest/recorder.go
  semconv/internal/v2/http.go
  semconv/internal/v3/http.go
  semconv/internal/v4/http.go
  trace/auto.go
  trace/noop.go
  trace/noop/noop.go
Labels: Skip Changelog

#7197 Flatten `stdouttrace` `Exporter.initSelfObservability` into `Exporter.New`
  exporters/stdout/stdouttrace/trace.go
  exporters/stdout/stdouttrace/trace_test.go
Labels: Skip Changelog, pkg:exporter:stdout

#7195 Fix component name for stdouttrace
  CHANGELOG.md
  exporters/stdout/stdouttrace/trace.go
  exporters/stdout/stdouttrace/trace_test.go
Labels: pkg:exporter:stdout

#7196 Restructure component ID counting in stdouttrace
  exporters/stdout/stdouttrace/internal/counter/counter.go
  exporters/stdout/stdouttrace/internal/counter/counter_test.go
  exporters/stdout/stdouttrace/trace.go
  exporters/stdout/stdouttrace/trace_test.go
Labels: Skip Changelog, pkg:exporter:stdout

#7155 sdk/trace: More trace id tests
  sdk/trace/trace_test.go
Labels: Skip Changelog

#7228 refactor(logger): Flatten `logger.initSelfObservability` into `logger.newLoggerr` and use `t.Cleanup` instead of defer
  sdk/log/logger.go
  sdk/log/logger_test.go
Labels: Skip Changelog

#7233 Fix CPUModeSystem variable name
  semconv/templates/registry/go/helpers.j2
  semconv/v1.36.0/systemconv/metric.go
Labels: Skip Changelog, pkg:semconv

#7222 Return early in semconv generated packages if no attributes passed
  semconv/templates/registry/go/instrument.j2
  semconv/v1.36.0/azureconv/metric.go
  semconv/v1.36.0/cicdconv/metric.go
  semconv/v1.36.0/containerconv/metric.go
  semconv/v1.36.0/dbconv/metric.go
  semconv/v1.36.0/dnsconv/metric.go
  semconv/v1.36.0/faasconv/metric.go
  semconv/v1.36.0/genaiconv/metric.go
  semconv/v1.36.0/goconv/metric.go
  semconv/v1.36.0/httpconv/metric.go
  semconv/v1.36.0/hwconv/metric.go
  semconv/v1.36.0/k8sconv/metric.go
  semconv/v1.36.0/messagingconv/metric.go
  semconv/v1.36.0/otelconv/metric.go
  semconv/v1.36.0/processconv/metric.go
  semconv/v1.36.0/rpcconv/metric.go
  semconv/v1.36.0/signalrconv/metric.go
  semconv/v1.36.0/systemconv/metric.go
  semconv/v1.36.0/vcsconv/metric.go
Labels: Skip Changelog

#7248 Add copyright header to generated semconv packages
  semconv/templates/registry/go/metric.go.j2
  semconv/v1.36.0/azureconv/metric.go
  semconv/v1.36.0/cicdconv/metric.go
  semconv/v1.36.0/containerconv/metric.go
  semconv/v1.36.0/dbconv/metric.go
  semconv/v1.36.0/dnsconv/metric.go
  semconv/v1.36.0/faasconv/metric.go
  semconv/v1.36.0/genaiconv/metric.go
  semconv/v1.36.0/goconv/metric.go
  semconv/v1.36.0/httpconv/metric.go
  semconv/v1.36.0/hwconv/metric.go
  semconv/v1.36.0/k8sconv/metric.go
  semconv/v1.36.0/messagingconv/metric.go
  semconv/v1.36.0/otelconv/metric.go
  semconv/v1.36.0/processconv/metric.go
  semconv/v1.36.0/rpcconv/metric.go
  semconv/v1.36.0/signalrconv/metric.go
  semconv/v1.36.0/systemconv/metric.go
  semconv/v1.36.0/vcsconv/metric.go
Labels: Skip Changelog

#7260 Upgrade semconv dependencies to v1.37.0
  bridge/opentracing/mock.go
  exporters/otlp/otlplog/otlploggrpc/client_test.go
  exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go
  exporters/otlp/otlplog/otlploghttp/client_test.go
  exporters/otlp/otlplog/otlploghttp/internal/transform/log_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/otest/client.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/transform/metricdata_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/otest/client.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/transform/metricdata_test.go
  exporters/otlp/otlptrace/internal/tracetransform/span_test.go
  exporters/prometheus/exporter_test.go
  exporters/stdout/stdoutmetric/example_test.go
  exporters/stdout/stdouttrace/example_test.go
  exporters/stdout/stdouttrace/trace.go
  exporters/stdout/stdouttrace/trace_test.go
  exporters/zipkin/model.go
  exporters/zipkin/model_test.go
  exporters/zipkin/zipkin_test.go
  internal/shared/otlp/otlplog/transform/log_test.go.tmpl
  internal/shared/otlp/otlpmetric/otest/client.go.tmpl
  internal/shared/otlp/otlpmetric/transform/metricdata_test.go.tmpl
  metric/example_test.go
  sdk/log/logger.go
  sdk/log/logger_test.go
  sdk/metric/example_test.go
  sdk/resource/builtin.go
  sdk/resource/container.go
  sdk/resource/env.go
  sdk/resource/env_test.go
  sdk/resource/host_id.go
  sdk/resource/os.go
  sdk/resource/os_test.go
  sdk/resource/process.go
  sdk/resource/resource_experimental_test.go
  sdk/resource/resource_test.go
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/provider.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  sdk/trace/tracer.go
  trace/auto.go
  trace/auto_test.go
Labels: Skip Changelog

#7262 Add benchmark for set equality
  attribute/benchmark_test.go
Labels: Skip Changelog

#7263 Statically define trace observability attributes
  sdk/trace/span.go
  sdk/trace/span_test.go
  sdk/trace/trace_test.go
  sdk/trace/tracer.go
Labels: Skip Changelog

#7271 Release v1.38.0
  CHANGELOG.md
  bridge/opencensus/go.mod
  bridge/opencensus/test/go.mod
  bridge/opencensus/version.go
  bridge/opentracing/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/version.go
  exporters/otlp/otlplog/otlploghttp/go.mod
  exporters/otlp/otlplog/otlploghttp/version.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/version.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/version.go
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/version.go
  exporters/prometheus/go.mod
  exporters/stdout/stdoutlog/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  log/go.mod
  log/logtest/go.mod
  metric/go.mod
  sdk/go.mod
  sdk/log/go.mod
  sdk/log/logtest/go.mod
  sdk/metric/go.mod
  sdk/metric/version.go
  sdk/version.go
  trace/go.mod
  trace/internal/telemetry/test/go.mod
  version.go
  versions.yaml
Labels: Unlock Released Changelog
