Repository open-telemetry/opentelemetry-go, pull requests merged in 2025-10, with the labels that each got.

#7423 Allow optimizing locking for built-in exemplar reservoirs
  sdk/metric/exemplar/fixed_size_reservoir.go
  sdk/metric/exemplar/fixed_size_reservoir_test.go
  sdk/metric/exemplar/histogram_reservoir.go
  sdk/metric/exemplar/storage.go
  sdk/metric/internal/aggregate/filtered_reservoir.go
  sdk/metric/internal/aggregate/filtered_reservoir_test.go
  sdk/metric/internal/reservoir/concurrent_safe.go
  sdk/metric/internal/reservoir/doc.go
Labels: Skip Changelog

#7404 Add the `internal/observ` package to `otlptracegrpc`
  .lycheeignore
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/partialsuccess.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/partialsuccess.go
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/internal/observ/instrumentation.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/observ/instrumentation_test.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/partialsuccess.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/version.go
  exporters/otlp/otlptrace/otlptracehttp/internal/partialsuccess.go
  internal/shared/otlp/partialsuccess.go.tmpl
  versions.yaml
Labels: Skip Changelog

#7427 Use sync.Map and atomics to improve sum performance
  CHANGELOG.md
  sdk/metric/exemplar/fixed_size_reservoir.go
  sdk/metric/exemplar/histogram_reservoir.go
  sdk/metric/exemplar/storage.go
  sdk/metric/internal/aggregate/aggregate.go
  sdk/metric/internal/aggregate/atomic.go
  sdk/metric/internal/aggregate/atomic_test.go
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/filtered_reservoir.go
  sdk/metric/internal/aggregate/histogram.go
  sdk/metric/internal/aggregate/lastvalue.go
  sdk/metric/internal/aggregate/limit.go
  sdk/metric/internal/aggregate/limit_test.go
  sdk/metric/internal/aggregate/sum.go
Labels: area:metrics

#7453 Document the ordering guarantees provided by the metrics SDK
  sdk/metric/doc.go
Labels: Skip Changelog

#7459 Instrument the `otlptracegrpc` exporter
  CHANGELOG.md
  exporters/otlp/otlptrace/otlptracegrpc/client.go
  exporters/otlp/otlptrace/otlptracegrpc/client_test.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/counter/counter.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/counter/counter_test.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/gen.go
  exporters/otlp/otlptrace/otlptracegrpc/mock_collector_test.go
Labels: pkg:exporter:otlp
