Repository open-telemetry/opentelemetry-go, pull requests merged in 2025-05, with the labels that each got.

#6599 Remove harness from internaltest and add doc template
  internal/gen.go
  internal/internaltest/doc.go
  internal/internaltest/harness.go
  internal/shared/internaltest/doc.go.tmpl
  internal/shared/internaltest/harness.go.tmpl
  sdk/internal/gen.go
  sdk/internal/internaltest/doc.go
  sdk/internal/internaltest/harness.go
Labels: Skip Changelog

#6724 Pin GitHub action digest with semver
  renovate.json
Labels: Skip Changelog

#6732 all: replace math/rand with math/rand/v2
  baggage/baggage_test.go
  bridge/opencensus/internal/ocmetric/metric_test.go
  bridge/opentracing/internal/mock.go
  metric/example_test.go
  sdk/metric/exemplar/fixed_size_reservoir.go
  sdk/metric/exemplar/fixed_size_reservoir_test.go
  sdk/resource/benchmark_test.go
  sdk/trace/id_generator.go
  sdk/trace/provider_test.go
  sdk/trace/sampling_test.go
Labels: Skip Changelog

#6782 Add `semconv/v1.32.0`
  CHANGELOG.md
  semconv/helpers.j2
  semconv/instrument.j2
  semconv/metric.go.j2
  semconv/v1.32.0/MIGRATION.md
  semconv/v1.32.0/README.md
  semconv/v1.32.0/attribute_group.go
  semconv/v1.32.0/azureconv/metric.go
  semconv/v1.32.0/cicdconv/metric.go
  semconv/v1.32.0/containerconv/metric.go
  semconv/v1.32.0/cpuconv/metric.go
  semconv/v1.32.0/dbconv/metric.go
  semconv/v1.32.0/dnsconv/metric.go
  semconv/v1.32.0/doc.go
  semconv/v1.32.0/exception.go
  semconv/v1.32.0/faasconv/metric.go
  semconv/v1.32.0/genaiconv/metric.go
  semconv/v1.32.0/goconv/metric.go
  semconv/v1.32.0/httpconv/metric.go
  semconv/v1.32.0/hwconv/metric.go
  semconv/v1.32.0/k8sconv/metric.go
  semconv/v1.32.0/messagingconv/metric.go
  semconv/v1.32.0/otelconv/metric.go
  semconv/v1.32.0/processconv/metric.go
  semconv/v1.32.0/rpcconv/metric.go
  semconv/v1.32.0/schema.go
  semconv/v1.32.0/signalrconv/metric.go
  semconv/v1.32.0/systemconv/metric.go
  semconv/v1.32.0/vcsconv/metric.go
  semconv/weaver.yaml
Labels: pkg:semconv

#6793 Release v1.36.0/v0.58.0/v0.12.0
  CHANGELOG.md
  bridge/opencensus/go.mod
  bridge/opencensus/test/go.mod
  bridge/opencensus/version.go
  bridge/opentracing/go.mod
  bridge/opentracing/test/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/version.go
  exporters/otlp/otlplog/otlploghttp/go.mod
  exporters/otlp/otlplog/otlploghttp/version.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/version.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/version.go
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/version.go
  exporters/prometheus/go.mod
  exporters/stdout/stdoutlog/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  log/go.mod
  log/logtest/go.mod
  metric/go.mod
  sdk/go.mod
  sdk/log/go.mod
  sdk/log/logtest/go.mod
  sdk/metric/go.mod
  sdk/metric/version.go
  sdk/version.go
  trace/go.mod
  trace/internal/telemetry/test/go.mod
  version.go
  versions.yaml
Labels: Unlock Released Changelog

#6802 Release experimental logs 0.12.1
  CHANGELOG.md
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/version.go
  exporters/otlp/otlplog/otlploghttp/go.mod
  exporters/otlp/otlplog/otlploghttp/version.go
  exporters/stdout/stdoutlog/go.mod
  log/logtest/go.mod
  sdk/log/go.mod
  sdk/log/logtest/go.mod
  versions.yaml
Labels: Unlock Released Changelog

#6805 Fix broken link in changelog
  CHANGELOG.md
Labels: Unlock Released Changelog

#6777 remove internal/matchers
  .golangci.yml
  internal/gen.go
  internal/matchers/expectation.go
  internal/matchers/expecter.go
  internal/matchers/package.go
  internal/matchers/temporal_matcher.go
Labels: Skip Changelog

#6783 Update the required approvals policy
  CONTRIBUTING.md
Labels: Skip Changelog

#6813 bridge/opencensus: add test for OTelSpanContextToOC function
  bridge/opencensus/trace_test.go
Labels: Skip Changelog

#5947 prometheus: Add otel_scope_schema_url and otel_scope_[attribute] labels
  CHANGELOG.md
  exporters/prometheus/exporter.go
  exporters/prometheus/testdata/conflict_help_two_counters_1.txt
  exporters/prometheus/testdata/conflict_help_two_counters_2.txt
  exporters/prometheus/testdata/conflict_help_two_histograms_1.txt
  exporters/prometheus/testdata/conflict_help_two_histograms_2.txt
  exporters/prometheus/testdata/conflict_help_two_updowncounters_1.txt
  exporters/prometheus/testdata/conflict_help_two_updowncounters_2.txt
  exporters/prometheus/testdata/conflict_type_counter_and_updowncounter_1.txt
  exporters/prometheus/testdata/conflict_type_counter_and_updowncounter_2.txt
  exporters/prometheus/testdata/conflict_type_histogram_and_updowncounter_1.txt
  exporters/prometheus/testdata/conflict_type_histogram_and_updowncounter_2.txt
  exporters/prometheus/testdata/conflict_unit_two_counters.txt
  exporters/prometheus/testdata/conflict_unit_two_histograms.txt
  exporters/prometheus/testdata/conflict_unit_two_updowncounters.txt
  exporters/prometheus/testdata/counter.txt
  exporters/prometheus/testdata/counter_disabled_suffix.txt
  exporters/prometheus/testdata/counter_utf8.txt
  exporters/prometheus/testdata/counter_with_unit_suffix.txt
  exporters/prometheus/testdata/custom_resource.txt
  exporters/prometheus/testdata/empty_resource.txt
  exporters/prometheus/testdata/exponential_histogram.txt
  exporters/prometheus/testdata/gauge.txt
  exporters/prometheus/testdata/histogram.txt
  exporters/prometheus/testdata/multi_scopes.txt
  exporters/prometheus/testdata/no_conflict_two_counters.txt
  exporters/prometheus/testdata/no_conflict_two_histograms.txt
  exporters/prometheus/testdata/no_conflict_two_updowncounters.txt
  exporters/prometheus/testdata/non_monotonic_sum_does_not_add_exemplars.txt
  exporters/prometheus/testdata/sanitized_labels.txt
  exporters/prometheus/testdata/sanitized_names.txt
  exporters/prometheus/testdata/with_allow_resource_attributes_filter.txt
  exporters/prometheus/testdata/with_namespace.txt
  exporters/prometheus/testdata/with_resource_attributes_filter.txt
  exporters/prometheus/testdata/without_target_info.txt
Labels: pkg:exporter:prometheus

#6825 log,sdk/log: add EventName to EnabledParameters
  CHANGELOG.md
  log/logger.go
  sdk/log/filter_processor.go
  sdk/log/logger.go
  sdk/log/logger_test.go
Labels: pkg:API, pkg:SDK, area:logs

#6828 Upgrade semconv to v1.34.0 for OTLP templates
  exporters/otlp/otlplog/otlploggrpc/client_test.go
  exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go
  exporters/otlp/otlplog/otlploghttp/client_test.go
  exporters/otlp/otlplog/otlploghttp/internal/transform/log_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/otest/client.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/transform/metricdata_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/otest/client.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/transform/metricdata_test.go
  exporters/otlp/otlptrace/internal/tracetransform/span_test.go
  internal/shared/otlp/otlplog/transform/log_test.go.tmpl
  internal/shared/otlp/otlpmetric/otest/client.go.tmpl
  internal/shared/otlp/otlpmetric/transform/metricdata_test.go.tmpl
Labels: Skip Changelog

#6831 Upgrade semconv to 1.34.0 in exporters/prometheus
  exporters/prometheus/exporter_test.go
Labels: Skip Changelog

#6833 Upgrade semconv to 1.34.0 in sdk/metric
  sdk/metric/example_test.go
Labels: Skip Changelog

#6837 Fix semconv instrument types
  semconv/v1.33.0/MIGRATION.md
  semconv/v1.33.0/goconv/metric.go
  semconv/v1.33.0/systemconv/metric.go
  semconv/v1.34.0/goconv/metric.go
  semconv/v1.34.0/systemconv/metric.go
  semconv/weaver.yaml
Labels: Skip Changelog

#6852 Add the FOSSA license scan badge shield
  README.md
Labels: documentation, Skip Changelog

#6853 Add a CLO monitor exemption for Artifact Hub
  .clomonitor.yml
Labels: Skip Changelog

#6846 sdk/trace: Remove internaltest package
  internal/gen.go
  internal/shared/internaltest/doc.go.tmpl
  internal/shared/internaltest/env.go.tmpl
  internal/shared/internaltest/env_test.go.tmpl
  internal/shared/internaltest/errors.go.tmpl
  internal/shared/internaltest/harness.go.tmpl
  internal/shared/internaltest/text_map_carrier.go.tmpl
  internal/shared/internaltest/text_map_carrier_test.go.tmpl
  internal/shared/internaltest/text_map_propagator.go.tmpl
  internal/shared/internaltest/text_map_propagator_test.go.tmpl
  sdk/internal/env/env_test.go
  sdk/internal/gen.go
  sdk/internal/internaltest/doc.go
  sdk/internal/internaltest/env.go
  sdk/internal/internaltest/env_test.go
  sdk/internal/internaltest/errors.go
  sdk/internal/internaltest/harness.go
  sdk/internal/internaltest/text_map_carrier.go
  sdk/internal/internaltest/text_map_carrier_test.go
  sdk/internal/internaltest/text_map_propagator.go
  sdk/internal/internaltest/text_map_propagator_test.go
Labels: Skip Changelog
