Repository open-telemetry/opentelemetry-go, pull requests merged in 2025-06, with the labels that each got.

#6864 sdk/log: Record.Resource to return *resource.Resource
  CHANGELOG.md
  exporters/stdout/stdoutlog/record.go
  sdk/log/logtest/factory_test.go
  sdk/log/record.go
  sdk/log/record_test.go
Labels: pkg:SDK, area:logs

#6850 Only check links in changed files for fail-fast workflow
  .github/workflows/links-fail-fast.yml
Labels: pkg:tooling, Skip Changelog

#6855 Add release artifacts signing to the release process
  CONTRIBUTING.md
  RELEASING.md
Labels: Skip Changelog

#6907 Remove internal matchers
  internal/shared/matchers/expectation.go.tmpl
  internal/shared/matchers/expecter.go.tmpl
  internal/shared/matchers/temporal_matcher.go.tmpl
  sdk/internal/gen.go
  sdk/internal/matchers/expectation.go
  sdk/internal/matchers/expecter.go
  sdk/internal/matchers/temporal_matcher.go
  sdk/trace/util_test.go
Labels: Skip Changelog

#6916 chore: flatten bridge/opentracing/internal package
  bridge/opentracing/bridge_grpc_test.go
  bridge/opentracing/bridge_test.go
  bridge/opentracing/go.mod
  bridge/opentracing/go.sum
  bridge/opentracing/internal/doc.go
  bridge/opentracing/mix_test.go
  bridge/opentracing/mock.go
  bridge/opentracing/provider_test.go
  bridge/opentracing/test/go.mod
  bridge/opentracing/test/go.sum
  versions.yaml
Labels: Skip Changelog

#6925 Release 1.37.0/0.59.0/0.13.0
  CHANGELOG.md
  bridge/opencensus/go.mod
  bridge/opencensus/test/go.mod
  bridge/opencensus/version.go
  bridge/opentracing/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/version.go
  exporters/otlp/otlplog/otlploghttp/go.mod
  exporters/otlp/otlplog/otlploghttp/version.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/version.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/version.go
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/version.go
  exporters/prometheus/go.mod
  exporters/stdout/stdoutlog/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  log/go.mod
  log/logtest/go.mod
  metric/go.mod
  sdk/go.mod
  sdk/log/go.mod
  sdk/log/logtest/go.mod
  sdk/metric/go.mod
  sdk/metric/version.go
  sdk/version.go
  trace/go.mod
  trace/internal/telemetry/test/go.mod
  version.go
  versions.yaml
Labels: Unlock Released Changelog

#6942 Standardize sections listing maintainer, approver, etc
  CONTRIBUTING.md
Labels: Skip Changelog
