Repository open-telemetry/opentelemetry-go, pull requests merged in 2025-03, with the labels that each got.

#6396 Look at stale issues in ascending order
  .github/workflows/close-stale.yml
Labels: Skip Changelog

#6400 Move trace sdk tests from trace_test into trace package
  sdk/trace/batch_span_processor_test.go
  sdk/trace/benchmark_test.go
  sdk/trace/simple_span_processor_test.go
  sdk/trace/span_processor_test.go
  sdk/trace/util_test.go
Labels: Skip Changelog

#6407 Release v1.35.0/v0.57.0/v0.11.0
  CHANGELOG.md
  bridge/opencensus/go.mod
  bridge/opencensus/test/go.mod
  bridge/opencensus/version.go
  bridge/opentracing/go.mod
  bridge/opentracing/test/go.mod
  exporters/otlp/otlplog/otlploggrpc/go.mod
  exporters/otlp/otlplog/otlploggrpc/version.go
  exporters/otlp/otlplog/otlploghttp/go.mod
  exporters/otlp/otlplog/otlploghttp/version.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/go.mod
  exporters/otlp/otlpmetric/otlpmetricgrpc/version.go
  exporters/otlp/otlpmetric/otlpmetrichttp/go.mod
  exporters/otlp/otlpmetric/otlpmetrichttp/version.go
  exporters/otlp/otlptrace/go.mod
  exporters/otlp/otlptrace/otlptracegrpc/go.mod
  exporters/otlp/otlptrace/otlptracehttp/go.mod
  exporters/otlp/otlptrace/version.go
  exporters/prometheus/go.mod
  exporters/stdout/stdoutlog/go.mod
  exporters/stdout/stdoutmetric/go.mod
  exporters/stdout/stdouttrace/go.mod
  exporters/zipkin/go.mod
  go.mod
  log/go.mod
  metric/go.mod
  sdk/go.mod
  sdk/log/go.mod
  sdk/metric/go.mod
  sdk/metric/version.go
  sdk/version.go
  trace/go.mod
  trace/internal/telemetry/test/go.mod
  version.go
  versions.yaml
Labels: Unlock Released Changelog

#6423 Update exporters README.md - otlploggrpc added
  exporters/README.md
Labels: documentation, Skip Changelog

#6420 Promote Alex Kats to triager
  CONTRIBUTING.md
Labels: Skip Changelog

#6434 trace/auto pass stack allocated span context var to ebpf
  trace/auto.go
Labels: Skip Changelog

#6451 Fix close stale value to be relative
  .github/workflows/close-stale.yml
Labels: Skip Changelog

#6449 Ignore deprecation warnings about NameValidationScheme
  CHANGELOG.md
  exporters/prometheus/config.go
  exporters/prometheus/exporter.go
  exporters/prometheus/exporter_test.go
Labels: Skip Changelog

#6518 Fix codeql permission
  .github/workflows/codeql-analysis.yml
Labels: Skip Changelog

#6504 Update release process in RELEASING.md
  .github/ISSUE_TEMPLATE/version_release.md
  RELEASING.md
Labels: Skip Changelog

#6517 Refactor `fail` method in matchers
  exporters/zipkin/internal/matchers/expectation.go
  internal/matchers/expectation.go
  internal/shared/matchers/expectation.go.tmpl
  sdk/internal/matchers/expectation.go
Labels: Skip Changelog

#6555 Remove unused get_main_pkgs.sh script
  get_main_pkgs.sh
Labels: Skip Changelog

#6554 zipkin: test zipkin exporter model conversion for bool, float64, and string slices
  exporters/zipkin/model_test.go
Labels: Skip Changelog

#6552 sdk/trace: Manage trace environment variables in testing package
  sdk/trace/batch_span_processor_test.go
  sdk/trace/provider_test.go
  sdk/trace/span_limits_test.go
  sdk/trace/trace_test.go
Labels: Skip Changelog

#6551 chore(sdk): Replace all uses of the internaltest package in metric
  sdk/metric/config_test.go
Labels: Skip Changelog

#6556 Remove Unused env.go and env_test.go; Update gen.go in internal
  internal/gen.go
  internal/internaltest/env.go
  internal/internaltest/env_test.go
Labels: Skip Changelog

#6558 Fix (Issue: 6529):updated lint-markdown run as dockeruser
  Makefile
Labels: Skip Changelog

#6559 internal/internaltest: Remove errors.go
  internal/gen.go
  internal/internaltest/errors.go
Labels: Skip Changelog
