Repository open-telemetry/opentelemetry-go, pull requests merged in 2025-01, with the labels that each got.

#6100 [chore] Move the changelog guard
  CHANGELOG.md
Labels: Unlock Released Changelog

#6098 Only run links check on main branch merge
  .github/workflows/links-fail-fast.yml
Labels: Skip Changelog

#6144 docs: update badge link
  README.md
Labels: Skip Changelog

#6160 Fix demo links
  RELEASING.md
Labels: Skip Changelog

#6201 chore: Group renovate build-tools updates
  renovate.json
Labels: Skip Changelog

#6206 chore: Update Logs API design doc
  log/DESIGN.md
Labels: Skip Changelog

#6223 Update codespell target
  .gitignore
  Makefile
  dependencies.Dockerfile
Labels: Skip Changelog

#5898 Weaver
  Makefile
  RELEASING.md
  dependencies.Dockerfile
  semconv/attribute_group.go.j2
  semconv/capitalizations.txt
  semconv/helpers.j2
  semconv/metric.go.j2
  semconv/metric_template.j2
  semconv/template.j2
  semconv/weaver.yaml
Labels: pkg:tooling, Skip Changelog
