Repository open-telemetry/opentelemetry-go, pull requests merged in 2025-09, with the labels that each got.

#7273 Fix missing link in changelog
  CHANGELOG.md
Labels: Unlock Released Changelog

#7288 Fix schema urls
  log/logger_test.go
  metric/config_test.go
  sdk/metric/example_test.go
  sdk/metric/view_test.go
Labels: Skip Changelog

#7306 Don't track min and max when disabled
  CHANGELOG.md
  sdk/metric/internal/aggregate/histogram.go
  sdk/metric/internal/aggregate/histogram_test.go
Labels: area:metrics

#7305 Add benchmark for exponential histogram measurements
  sdk/metric/benchmark_test.go
Labels: Skip Changelog

#7287 trace,metric,log: add WithInstrumentationAttributeSet option
  CHANGELOG.md
  log/logger.go
  log/logger_test.go
  metric/config.go
  metric/config_test.go
  trace/config.go
  trace/config_test.go
Labels: enhancement, pkg:API, area:metrics, area:trace, area:logs

#7307 Encapsulate `stdouttrace.Exporter` instrumentation in internal package
  .codespellignore
  exporters/stdout/stdouttrace/internal/observ/instrumentation.go
  exporters/stdout/stdouttrace/internal/observ/instrumentation_test.go
  exporters/stdout/stdouttrace/internal/version.go
  exporters/stdout/stdouttrace/trace.go
  exporters/stdout/stdouttrace/trace_test.go
  versions.yaml
Labels: Skip Changelog

#7328 Do not allocate instrument options if possible in generated semconv packages
  semconv/templates/registry/go/metric.go.j2
  semconv/v1.37.0/azureconv/metric.go
  semconv/v1.37.0/cicdconv/metric.go
  semconv/v1.37.0/containerconv/metric.go
  semconv/v1.37.0/dbconv/metric.go
  semconv/v1.37.0/dnsconv/metric.go
  semconv/v1.37.0/faasconv/metric.go
  semconv/v1.37.0/genaiconv/metric.go
  semconv/v1.37.0/goconv/metric.go
  semconv/v1.37.0/httpconv/metric.go
  semconv/v1.37.0/hwconv/metric.go
  semconv/v1.37.0/k8sconv/metric.go
  semconv/v1.37.0/messagingconv/metric.go
  semconv/v1.37.0/otelconv/metric.go
  semconv/v1.37.0/processconv/metric.go
  semconv/v1.37.0/rpcconv/metric.go
  semconv/v1.37.0/signalrconv/metric.go
  semconv/v1.37.0/systemconv/metric.go
  semconv/v1.37.0/vcsconv/metric.go
Labels: Skip Changelog

#7332 Encapsulate SDK BatchSpanProcessor observability
  sdk/trace/batch_span_processor.go
  sdk/trace/batch_span_processor_test.go
  sdk/trace/internal/observ/batch_span_processor.go
  sdk/trace/internal/observ/batch_span_processor_test.go
  sdk/trace/internal/observ/doc.go
  sdk/trace/internal/observ/observ_test.go
Labels: Skip Changelog

#7331 Encapsulate SDK Tracer observability
  sdk/trace/internal/observ/tracer.go
  sdk/trace/internal/observ/tracer_test.go
  sdk/trace/provider.go
  sdk/trace/provider_test.go
  sdk/trace/span.go
  sdk/trace/trace_test.go
  sdk/trace/tracer.go
Labels: Skip Changelog

#7378 sdk/log: add TestRecordMethodsInputConcurrentSafe
  sdk/log/race_off_test.go
  sdk/log/race_on_test.go
  sdk/log/record_test.go
Labels: Skip Changelog

#7401 Add experimental `x` package to `otlptracegrpc`
  exporters/otlp/otlptrace/otlptracegrpc/internal/gen.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/x/README.md
  exporters/otlp/otlptrace/otlptracegrpc/internal/x/observ.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/x/observ_test.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/x/x.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/x/x_test.go
Labels: Skip Changelog

#7407 Add benchmark for synchronous gauge measurement
  sdk/metric/benchmark_test.go
Labels: Skip Changelog

#7422 Only enforce cardinality limits when the attribute set does not already exist
  sdk/metric/internal/aggregate/exponential_histogram.go
  sdk/metric/internal/aggregate/histogram.go
  sdk/metric/internal/aggregate/lastvalue.go
  sdk/metric/internal/aggregate/sum.go
Labels: Skip Changelog
