Repository open-telemetry/opentelemetry-go, pull requests merged in 2025-04, with the labels that each got.

#6579 Add example for SetTextMapPropagator
  propagation/example_test.go
Labels: Skip Changelog

#6566 Remove the exporters/zipkin/internal package
  exporters/zipkin/env_test.go
  exporters/zipkin/internal/gen.go
  exporters/zipkin/internal/internaltest/env.go
  exporters/zipkin/internal/internaltest/env_test.go
  exporters/zipkin/internal/internaltest/errors.go
  exporters/zipkin/internal/internaltest/harness.go
  exporters/zipkin/internal/internaltest/text_map_carrier.go
  exporters/zipkin/internal/internaltest/text_map_carrier_test.go
  exporters/zipkin/internal/internaltest/text_map_propagator.go
  exporters/zipkin/internal/internaltest/text_map_propagator_test.go
  exporters/zipkin/internal/matchers/expectation.go
  exporters/zipkin/internal/matchers/expecter.go
  exporters/zipkin/internal/matchers/temporal_matcher.go
  exporters/zipkin/zipkin_test.go
Labels: Skip Changelog

#6583 opentracing: test `LogFields` and `LogKV` in the opentracing bridge
  bridge/opentracing/bridge_test.go
Labels: Skip Changelog

#6582 Reference markdownlint docker image in dependencies.Dockerfile
  Makefile
  dependencies.Dockerfile
Labels: Skip Changelog

#6586 Remove the lint-modules make target
  Makefile
Labels: Skip Changelog

#6576 Add a unit test to verify the functionality of WithClient for zipkin exporter
  exporters/zipkin/zipkin_test.go
Labels: Skip Changelog

#6570 openteracing: test SetTag and bridgeFieldEncoder in the opentracing bridge
  bridge/opentracing/bridge_test.go
Labels: Skip Changelog

#6580 Functionality moved from internal/attribute to attribute
  .golangci.yml
  attribute/internal/attribute.go
  attribute/internal/attribute_test.go
  attribute/value.go
Labels: Skip Changelog

#6597 add extra test SetTag of a span in the opentracing bridge and don't use types, use string literals instead.
  bridge/opentracing/bridge_test.go
Labels: Skip Changelog

#6600 opencensus: add TestOCSpanContextToOTel
  bridge/opencensus/trace_test.go
Labels: Skip Changelog

#6589 sdk/trace: Move testing harness to trace
  sdk/trace/trace_test.go
  sdk/trace/util_test.go
Labels: Skip Changelog

#6578 chore: move functionality from internal/rawhelpers.go to attribute
  attribute/rawhelpers.go
  attribute/value.go
  internal/gen.go
  internal/rawhelpers.go
Labels: Skip Changelog

#6507 log/logtest: Change Recorder.Result
  CHANGELOG.md
  log/logtest/recorder.go
  log/logtest/recorder_test.go
Labels: area:logs

#6598 Rewrite verify_readmes.sh script in Go
  Makefile
  internal/tools/verifyreadmes/main.go
  verify_readmes.sh
Labels: Skip Changelog

#6651 Update the milestone issue search URL
  RELEASING.md
Labels: Skip Changelog

#6670 Clarify comments for the `WithRetry` option in exporters
  exporters/otlp/otlplog/otlploggrpc/config.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/config.go
  exporters/otlp/otlptrace/otlptracegrpc/options.go
Labels: Skip Changelog

#6675 Do not discourage direct usage of Logs API
  log/doc.go
  log/embedded/embedded.go
  log/global/log.go
  log/noop/noop.go
  sdk/log/doc.go
Labels: documentation, Skip Changelog

#6684 Fix semconv generation to support acronyms/initialisms and normative key words
  semconv/helpers.j2
  semconv/v1.31.0/attribute_group.go
Labels: bug, documentation, Skip Changelog

#6685 Relax grpc errors to allow for upgrade
  exporters/otlp/otlplog/otlploggrpc/internal/retry/retry_test.go
  exporters/otlp/otlplog/otlploghttp/internal/retry/retry_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/client_test.go
  exporters/otlp/otlpmetric/otlpmetricgrpc/internal/retry/retry_test.go
  exporters/otlp/otlpmetric/otlpmetrichttp/internal/retry/retry_test.go
  exporters/otlp/otlptrace/otlptracegrpc/internal/retry/retry_test.go
  exporters/otlp/otlptrace/otlptracehttp/internal/retry/retry_test.go
  internal/shared/otlp/retry/retry_test.go.tmpl
Labels: Skip Changelog

#6690 Fix tracestate benchmarks
  trace/tracestate_test.go
Labels: Skip Changelog

#6703 chore: Add OSS-Fuzz badge
  README.md
Labels: Skip Changelog
